function AJAXRULES(k,u){if(KgbLib_CheckNullity(k))return;var host="/";var edges={"ars":"/","chbx-lp":"/","chbx-0":"/","eval":"/","nwfd":"/","psmn-lp":"/","rct":"/","rel":"/","srhbx":"/"};var user=!KgbLib_CheckNullity(u)?u:"";var t=(new Date).getTime();var AR_TAB={"STUS":{"urqid":"STUS","url":host+"stus.php","wcrdtl":false},"TQR_ART_PULL":{"urqid":"TQR_ART_PULL","url":edges["ars"]+"ajax/TPLA@profil/"+t,"wcrdtl":true},"TQR_PULL_TR_FM_WAIO":{"urqid":"TQR_PULL_TR_FM_WAIO","url":host+"ajax/TPTF_WAIO@profil/"+
t,"wcrdtl":false},"TQR_SEARCH":{"urqid":"TQR_SEARCH","url":edges["srhbx"]+"ajax/Q@profil/"+t,"wcrdtl":true},"PM_SBPL_RPS":{"urqid":"PM_SBPL_RPS","url":edges["psmn-lp"]+"ajax/PM_SBPL_RPS@profil/"+t,"wcrdtl":true},"FKSA_EVAL_AX":{"urqid":"FKSA_EVAL_AX","url":host+"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"FKSA_PLES":{"urqid":"FKSA_PL_ES","url":host+"ajax/FKSA_PL_ES@focus/"+t,"wcrdtl":false},"FKSA_PLRS":{"urqid":"FKSA_PL_MS","url":host+"ajax/FKSA_PL_MS@focus/"+t,"wcrdtl":false},"FKSA_PLSMPL":{"urqid":"FKSA_PL_SMPL",
"url":host+"ajax/FKSA_PL_SMPL@focus/"+t,"wcrdtl":false},"CHBX_SEARCH":{"urqid":"CHBX_SEARCH","url":edges["chbx-0"]+"ajax/"+user+"/CHBX_SRH@profil/"+t,"wcrdtl":true},"CHBX_SUB_M":{"urqid":"CHBX_SUB_M","url":edges["chbx-0"]+"ajax/"+user+"/CHBX_SUB_M@profil/"+t,"wcrdtl":true},"CHBX_PL_MS":{"urqid":"CHBX_PL_MS","url":edges["chbx-lp"]+"ajax/"+user+"/CHBX_PL_MS@profil/"+t,"wcrdtl":true},"CHBX_DL_MS":{"urqid":"CHBX_DL_MS","url":edges["chbx-0"]+"ajax/"+user+"/CHBX_DL_MS@profil/"+t,"wcrdtl":true},"CHBX_DL_CS":{"urqid":"CHBX_DL_CS",
"url":edges["chbx-0"]+"ajax/"+user+"/CHBX_DL_CS@profil/"+t,"wcrdtl":true},"CHBX_PL_CNV":{"urqid":"CHBX_PL_CNV","url":edges["chbx-lp"]+"ajax/"+user+"/CHBX_PL_CNV@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_BKFLG":{"urqid":"TMLNR_BRAIN_BKFLG","url":edges["rel"]+"ajax/"+user+"/TMLNR_BN_BKFLG@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_RHFLG":{"urqid":"TMLNR_BRAIN_RHFLG","url":edges["rel"]+"ajax/"+user+"/TMLNR_BN_RHFLG@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_PLCATG":{"urqid":"TMLNR_BRAIN_PLCATG","url":host+"ajax/"+
user+"/TMLNR_BN_PLCATG@profil/"+t,"wcrdtl":true},"ULTMT_FOLL":{"urqid":"ULTMT_FOLL","url":edges["rel"]+"ajax/TMLNR_GOFLWREL@profil/"+t,"wcrdtl":true},"ULTMT_UFOLL":{"urqid":"ULTMT_FOLL","url":edges["rel"]+"ajax/TMLNR_GOFLWREL@profil/"+t,"wcrdtl":true},"TMLNR_ADD_IMLART":{"urqid":"TMLNR_ADD_IMLART","url":host+"ajax/"+user+"/TMLNR_ADD_IMLART@profil/"+t,"wcrdtl":false},"TMLNR_ADD_TRART":{"urqid":"TMLNR_ADD_TRART","url":host+"ajax/"+user+"/TMLNR_ADD_ITRART@profil/"+t,"wcrdtl":false},"TMLNR_CHECK_GET_ART_INTR":{"urqid":"TMLNR_CHECK_GET_ART_INTR",
"url":edges["ars"]+"ajax/TMLNR_PITRS_NWR@profil/"+t,"wcrdtl":true},"TMLNR_CHECK_GET_ART_IML":{"urqid":"TMLNR_CHECK_GET_ART_IML","url":edges["ars"]+"ajax/TMLNR_PIMLS_NWR@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_GETMYTRS":{"urqid":"TMLNR_BRAIN_GETMYTRS","url":host+"ajax/"+user+"/TMLNR_BN_GETMYTRS@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_GETFOLGTRS":{"urqid":"TMLNR_BRAIN_GETFOLGTRS","url":host+"ajax/"+user+"/TMLNR_BN_GETFLGTRS@profil/"+t,"wcrdtl":true},"TMLNR_SIG_DSMATRCCT":{"urqid":"TMLNR_SIG_DSMATRCCT",
"url":host+"ajax/"+user+"/TMLNR_BN_DSMATRCCT@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_GETMYFOLW":{"urqid":"TMLNR_BRAIN_GETMYFOLW","url":edges["rel"]+"ajax/"+user+"/TMLNR_BN_MYFOLW@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_GETMYFOLG":{"urqid":"TMLNR_BRAIN_GETMYFOLG","url":edges["rel"]+"ajax/"+user+"/TMLNR_BN_MYFOLG@profil/"+t,"wcrdtl":true},"TMLNR_BRAIN_NEWTREND":{"urqid":"TMLNR_BRAIN_NEWTREND","url":host+"ajax/"+user+"/TMLNR_BN_NWTRD@profil/"+t,"wcrdtl":true},"TMLNR_DEL_MyTR":{"urqid":"TMLNR_DEL_MyTR",
"url":host+"ajax/"+user+"/TMLNR_BN_DELTRD@profil/"+t,"wcrdtl":true},"TMLNR_SET_COVER":{"urqid":"TMLNR_SET_COVER","url":host+"ajax/"+user+"/TMLNR_SETCOV@profil/"+t,"wcrdtl":true},"TMLNR_RST_COVER":{"urqid":"TMLNR_RST_COVER","url":host+"ajax/"+user+"/TMLNR_RSTCVR@profil/"+t,"wcrdtl":true},"TMLNR_SET_PFLPIC":{"urqid":"TMLNR_SET_PFLPIC","url":host+"ajax/"+user+"/TMLNR_SETPPIC@profil/"+t,"wcrdtl":true},"TMLNR_SET_DFTPIC":{"urqid":"TMLNR_SET_DFTPIC","url":host+"ajax/"+user+"/TMLNR_SET_DPPIC@profil/"+t,
"wcrdtl":true},"GET_ARP_VIA_POSTID":{"urqid":"GET_ARP_VIA_POSTID","url":host+"ajax/TMLNR_GTARP@profil/"+t,"wcrdtl":true},"ARP_PULL_REACTS":{"urqid":"ARP_PULL_REACTS","url":edges["rct"]+"ajax/TMLNR_ARP_PLRCTS@profil/"+t,"wcrdtl":true},"ARP_DEL_ART":{"urqid":"ARP_DEL_ART","url":edges["ars"]+"ajax/TMLNR_DELART@profil/"+t,"wcrdtl":true},"ADD_R_IN_ARP":{"urqid":"ADD_R_IN_ARP","url":edges["rct"]+"ajax/TMLNR_ARP_ADDRCT@profil/"+t,"wcrdtl":true},"DEL_R_IN_ARP":{"urqid":"DEL_R_IN_ARP","url":edges["rct"]+"ajax/TMLNR_ARP_DELRCT@profil/"+
t,"wcrdtl":true},"TMLNR_CHECK_GET_PDART":{"urqid":"TMLNR_CHECK_GET_PDART","url":edges["ars"]+"ajax/TMLNR_GTPDARTS@profil/"+t,"wcrdtl":true},"NWFD_GET_ARTS":{"urqid":"NWFD_GET_ARTS","url":edges["nwfd"]+"ajax/NWFD_GARTS@profil/"+t,"wcrdtl":true},"NWFD_GET_ARTS_FROM":{"urqid":"NWFD_GET_ARTS_FROM","url":edges["nwfd"]+"ajax/NWFD_GARTS_FM@profil/"+t,"wcrdtl":true},"CR_NW_TRDART":{"urqid":"CR_NW_TRDART","url":host+"ajax/TRPG_NW_ART@trend/"+t,"wcrdtl":false},"SAVE_USER_BIO":{"urqid":"SAVE_USER_BIO","url":host+
"ajax/"+user+"/TMLNR_SAVE_PFLBIO@profil/"+t,"wcrdtl":true},"TRPG_CHECK_PDPOSTS":{"urqid":"TRPG_CHECK_PDPOSTS","url":edges["ars"]+"ajax/TRPG_GARTS_FM@trend/"+t,"wcrdtl":true},"TRPG_GET_STGS":{"urqid":"TRPG_GET_STGS","url":host+"ajax/TRPG_GT_STGS@trend/"+t,"wcrdtl":true},"TRPG_SV_NW_STS":{"urqid":"TRPG_SV_NW_STS","url":host+"ajax/TRPG_ST_STGS@trend/"+t,"wcrdtl":true},"TRPG_SET_TCOV":{"urqid":"TRPG_SET_TCOV","url":host+"ajax/TRPG_SET_TCOV@trend/"+t,"wcrdtl":true},"TRPG_DEL_TCOV":{"urqid":"TRPG_DEL_TCOV",
"url":host+"ajax/TRPG_RSTCVR@trend/"+t,"wcrdtl":true},"EVAL_RHCOOL":{"urqid":"EVAL_RHCOOL","url":edges["eval"]+"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"EVAL_RHDSLK":{"urqid":"EVAL_RHDSLK","url":edges["eval"]+"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"EVAL_RHSPCL":{"urqid":"EVAL_RHSPCL","url":edges["eval"]+"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"EVAL_BKCOOL":{"urqid":"EVAL_BKCOOL","url":edges["eval"]+"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"EVAL_BKDSLK":{"urqid":"EVAL_BKDSLK","url":edges["eval"]+
"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"EVAL_BKSPCL":{"urqid":"EVAL_BKSPCL","url":edges["eval"]+"ajax/EVAL_ACT@profil/"+t,"wcrdtl":true},"UNQ_DEL_REACT":{"urqid":"UNQ_DEL_REACT","url":edges["rct"]+"ajax/UNQ_DELRCT@profil/"+t,"wcrdtl":true},"UNQ_ADD_REACT":{"urqid":"UNQ_ADD_REACT","url":edges["rct"]+"ajax/UNQ_ADDRCT@profil/"+t,"wcrdtl":true},"UNQ_GET_ALL_REACT_LIMIT":{"urqid":"UNQ_GET_ALL_REACT_LIMIT","url":edges["rct"]+"ajax/UNQ_GETALL_RCTS@profil/"+t,"wcrdtl":true},"UNQ_PULL_VIPs_PLUS":{"urqid":"UNQ_PULL_VIPs_PLUS",
"url":edges["eval"]+"ajax/UNQ_PLVIPS_PLUS@profil/"+t,"wcrdtl":true},"UNQ_PULL_EVALs":{"urqid":"UNQ_PULL_EVALs","url":host+"ajax/UNQ_PLEVALS@profil/"+t,"wcrdtl":false},"UNQ_DEL_TMLNR_ART":{"urqid":"UNQ_DEL_TMLNR_ART","url":host+"ajax/TMLNR_DELART@profil/"+t,"wcrdtl":true},"FRDS_ACCEPT":{"urqid":"FRDS_ACCEPT","url":edges["rel"]+"ajax/FRDCTR_ACPT@profil/"+t,"wcrdtl":true},"FRDS_DECLINE":{"urqid":"FRDS_DECLINE","url":edges["rel"]+"ajax/FRDCTR_DCLN@profil/"+t,"wcrdtl":true},"FRDS_GET_NEW_RQTS":{"urqid":"FRDS_GET_NEW_RQTS",
"url":edges["rel"]+"ajax/FRDCTR_GNRQTS@profil/"+t,"wcrdtl":true},"FRDS_GET_ALL_FRDS":{"urqid":"FRDS_GET_ALL_FRDS","url":edges["rel"]+"ajax/FRDCTR_GMFRD@profil/"+t,"wcrdtl":true},"FRDS_TRY_FRIEND":{"urqid":"FRDS_TRY_FRIEND","url":edges["rel"]+"ajax/FRD_GOFRD@profil/"+t,"wcrdtl":true},"FRDS_TRY_UNFRIEND":{"urqid":"FRDS_TRY_UNFRIEND","url":edges["rel"]+"ajax/FRDCTR_UFRD@profil/"+t,"wcrdtl":true},"TRPG_TRY_ABO_OPER":{"urqid":"TRPG_TRY_ABO_OPER","url":host+"ajax/TRPG_GN_ABO@trend/"+t,"wcrdtl":true},"INS_PULLDATAS":{"urqid":"INS_PULLDATAS",
"url":host+"ajax/INS_SRH@inscription/"+t,"wcrdtl":false},"INS_FNL":{"urqid":"INS_FNL","url":host+"ajax/INS_FNL_OPE@inscription/"+t,"wcrdtl":false},"CNX_TRYCNX":{"urqid":"CNX_TRYCNX","url":host+"ajax/CNX_TRYCNX@connexion/"+t,"wcrdtl":true},"CNX_TDLACT":{"urqid":"CNX_TDLACT","url":host+"ajax/CNX_TDLACT@connexion/"+t,"wcrdtl":true},"TQR_REC_L":{"urqid":"TQR_REC_L","url":host+"ajax/REC_TRYREC_L@recovery/"+t,"wcrdtl":false},"TQR_REC_F":{"urqid":"TQR_REC_F","url":host+"ajax/REC_TRYREC_F@recovery/"+t,"wcrdtl":true},
"STGS_SUBT_PFL":{"urqid":"STGS_SUBT_PFL","url":host+"ajax/"+user+"/STGS_SUBT_PFL@settings/"+t,"wcrdtl":true},"STGS_SUBT_ACC":{"urqid":"STGS_SUBT_ACC","url":host+"ajax/"+user+"/STGS_SUBT_ACC@settings/"+t,"wcrdtl":true},"STGS_SUBT_PWD":{"urqid":"STGS_SUBT_PWD","url":host+"ajax/"+user+"/STGS_SUBT_PWD@settings/"+t,"wcrdtl":true},"STGS_SUBT_SEC_CO":{"urqid":"STGS_SUBT_SECCO","url":host+"ajax/"+user+"/STGS_SUBT_SECCO@settings/"+t,"wcrdtl":true},"STGS_SUBT_DELACC":{"urqid":"STGS_SUBT_DELACC","url":host+
"ajax/"+user+"/STGS_SUBT_DELACC@settings/"+t,"wcrdtl":true},"BGZY_SUB":{"urqid":"BGZY_SUB","url":host+"ajax/"+user+"/BGZY_SUB@profil/"+t,"wcrdtl":true},"TQREX_STPRFRCS":{"urqid":"TQREX_STPRFRCS","url":host+"ajax/TQR_SVEXPREF@profil/"+t,"wcrdtl":true},"FVLK_ADD_FAV":{"urqid":"FVLK_ADD_FAV","url":host+"ajax/TAPP_FVLK_ADD_FAV@profil/"+t,"wcrdtl":false},"FVLK_VST_FAV":{"urqid":"FVLK_VST_FAV","url":host+"ajax/TAPP_FVLK_VST_FAV@profil/"+t,"wcrdtl":false},"FVLK_DEL_FAV":{"urqid":"FVLK_DEL_FAV","url":host+
"ajax/TAPP_FVLK_DEL_FAV@profil/"+t,"wcrdtl":false},"FVLK_GET_FST_FAV":{"urqid":"FVLK_GET_FST_FAV","url":host+"ajax/TAPP_FVLK_FST_FAV@profil/"+t,"wcrdtl":false},"FVLK_GET_FRM_FAV":{"urqid":"FVLK_GET_FRM_FAV","url":host+"ajax/TAPP_FVLK_FRM_FAV@profil/"+t,"wcrdtl":false},"RCMD_SUBMIT":{"urqid":"RCMD_SUBMIT","url":host+"ajax/TQR_RCMDTO_SUBMIT@recoma/"+t,"wcrdtl":false},"TQR_EC_REDO":{"urqid":"TQR_EC_REDO","url":host+"ajax/TQR_EC_REDO@profil/"+t,"wcrdtl":false},"TQR_SUGG_GETALL":{"urqid":"TQR_SUGG_GETALL",
"url":host+"ajax/TQR_SUGG_GA@profil/"+t,"wcrdtl":false},"TQR_TSTY_ADD":{"urqid":"TQR_TSTY_ADD","url":host+"ajax/TQR_TSTY_ADD@profil/"+t,"wcrdtl":false},"TQR_TSTY_DEL":{"urqid":"TQR_TSTY_DEL","url":host+"ajax/TQR_TSTY_DL@profil/"+t,"wcrdtl":false},"TQR_TSTY_PIN":{"urqid":"TQR_TSTY_PIN","url":host+"ajax/TQR_TSTY_PIN@profil/"+t,"wcrdtl":false},"TQR_TSTY_GET":{"urqid":"TQR_TSTY_GET","url":host+"ajax/TQR_TSTY_GT@profil/"+t,"wcrdtl":false},"TQR_TSTY_GET_CONF":{"urqid":"TQR_TSTY_GET_CONF","url":host+"ajax/"+
user+"/TQR_TSTY_GET_CF@profil/"+t,"wcrdtl":false},"TQR_TSTY_SET_CONF":{"urqid":"TQR_TSTY_SET_CONF","url":host+"ajax/"+user+"/TQR_TSTY_SET_CF@profil/"+t,"wcrdtl":false},"TQR_LASTA_GACTV":{"urqid":"TQR_LASTA_GACTV","url":host+"ajax/TQR_LASTA_GA@profil/"+t,"wcrdtl":false},"CHBX_NTY_GN":{"urqid":"CHBX_NTY_GN","url":edges["chbx-lp"]+"ajax/"+user+"/CHBX_NTY_GN@profil/"+t,"wcrdtl":false},"CHBX_NTY_SN":{"urqid":"CHBX_NTY_SN","url":edges["chbx-lp"]+"ajax/"+user+"/CHBX_NTY_SN@profil/"+t,"wcrdtl":false},"TQR_HVIEW_GDS":{"urqid":"TQR_HVIEW_GDS",
"url":host+"ajax/TQR_HVIEW_GDS@thehashview/"+t,"wcrdtl":false},"FKSA_ADD_RCT":{"urqid":"FKSA_ADD_RCT","url":host+"ajax/TQR_GENRC_ADD_ARC@profil/"+t,"wcrdtl":true},"FKSA_DEL_RCT":{"urqid":"FKSA_DEL_RCT","url":host+"ajax/TQR_GENRC_DEL_ARC@profil/"+t,"wcrdtl":true},"TQR_TSTY_XTAC":{"urqid":"TQR_TSTY_XTAC","url":host+"ajax/TQR_TSTY_XA@profil/"+t,"wcrdtl":false},"TQR_TBUV_PL_TSR":{"urqid":"TQR_TBUV_PL_TSR","url":host+"ajax/TQR_TBUV_TSR_PL@profil/"+t,"wcrdtl":false},"TQR_TBUV_ADD_TSR":{"urqid":"TQR_TBUV_ADD_TSR",
"url":host+"ajax/TQR_TBUV_TSR_AD@profil/"+t,"wcrdtl":false},"TQR_TBUV_DEL_TSR":{"urqid":"TQR_TBUV_DEL_TSR","url":host+"ajax/TQR_TBUV_TSR_DL@profil/"+t,"wcrdtl":false},"TQR_TBUV_PL_TSL":{"urqid":"TQR_TBUV_PL_TSL","url":host+"ajax/TQR_TBUV_TSL_PL@profil/"+t,"wcrdtl":false},"TQR_ART_FAV":{"urqid":"TQR_ART_FAV","url":host+"ajax/TQR_ARFAV_FAV@profil/"+t,"wcrdtl":false},"TQR_ART_LDMR":{"urqid":"TQR_ART_LDMR","url":host+"ajax/TQR_ARFAV_LDMR@profil/"+t,"wcrdtl":false},"TQR_LTC_SSN_NEW":{"urqid":"TQR_LTC_SSN_NEW",
"url":host+"ajax/TQR_LTC_SSN_NEW@profil/"+t,"wcrdtl":true},"TQR_LTC_MSG_SEND":{"urqid":"TQR_LTC_MSG_SEND","url":host+"ajax/TQR_LTC_MSG_SND@profil/"+t,"wcrdtl":true},"TQR_TIA_EXPLR_PL":{"urqid":"TQR_TIA_EXPLR_PL","url":host+"ajax/TQR_TIA_EXPLR_PL@profil/"+t,"wcrdtl":true},"TQR_TIA_PCQR_PL":{"urqid":"TQR_TIA_PCQR_PL","url":host+"ajax/TQR_TIA_PCQR_PL@profil/"+t,"wcrdtl":true},"TQR_TIA_MYSRY_ADD":{"urqid":"TQR_TIA_MYSRY_ADD","url":host+"ajax/TQR_TIA_MYSRY_ADD@profil/"+t,"wcrdtl":true},"TQR_TIA_MYSRY_DLMM":{"urqid":"TQR_TIA_MYSRY_ADD",
"url":host+"ajax/TQR_TIA_MYSRY_DEL@profil/"+t,"wcrdtl":true},"TQR_TIA_MYSRY_PLMM":{"urqid":"TQR_TIA_MYSRY_PLMM","url":host+"ajax/TQR_TIA_MYSRY_PLMM@profil/"+t,"wcrdtl":true},"TQR_TIA_MYSRY_EVLMM":{"urqid":"TQR_TIA_MYSRY_EVLMM","url":host+"ajax/TQR_TIA_MYSRY_VOTE@profil/"+t,"wcrdtl":true},"TQR_SUGG_GT_DCORA":{"urqid":"TQR_SUGG_GETALL","url":host+"ajax/TQR_SUGG_GA@profil/"+t,"wcrdtl":false},"TQR_RLC_PLAC":{"urqid":"TQR_RLC_PLAC","url":host+"ajax/TQR_RLC_PLAC@profil/"+t,"wcrdtl":false}};if(!AR_TAB.hasOwnProperty(k))return false;
else return AR_TAB[k]};
