try{$(document).mousedown(function(e){var $revcl=$(".kgb_el_can_revs");var $bfucl=$(".bind-fluser");var $getlinkcl=$(".get-link-trig");var $delpost=$(".del-the-post");var $concTr=$(".bind-conxtr");var $delMytr=$(".bind-delmytr");var $pmGoVstdMytr=$(".bind-pm-gvstd");var $chTrCover=$(".jb-tr-chcov-trg");var $delTrCvr=$(".bind-deltrcov");var $trOpFil=$(".bind-tr-filters");var $trOpEdit=$(".bind-tr-trpg-edit");var $trOpCr=$(".bind-tr-trpg-cr");var $irr=$(".jb-irr, .jb-irr-wchlop *");var $rld=$(".jb-rld");
var $goto=$(".bind-goto");var $chbxOpt=$(".jb-chbx-opt-chc-tgr");var $AtHmMn=$(".jb-tmlnr-athm-mn");var $flbmn=$(".jb-flb-mn");var $tlkbOpt=$(".jb-tqr-tsty-art-opt").filter("[data-action='post-pin-start'],[data-action='post-del-start']");var $ubxMns=$(".jb-ubx-menu-choices");var $insMrTrg=$(".jb-ins-mr-trg");if($revcl.is(e.target))Revs_HandleClick(e);else if($bfucl.is(e.target))(new FPH_Receiver).Routeur(e.target);else if($getlinkcl.is(e.target))(new RichPost_Receiver).Routeur(e.target);else if($delpost.is(e.target))(new RichPost_Receiver).Routeur(e.target);
else if($concTr.is(e.target))(new TrOpe_Receiver).Routeur(e.target);else if($delMytr.is(e.target))(new TrOpe_Receiver).Routeur(e.target);else if($chTrCover.is(e.target))Kxlib_PreventDefault(e);else if($delTrCvr.is(e.target))(new TrHeader_Receiver).Routeur(e.target);else if($trOpFil.is(e.target))(new TrFilters_Receiver).Routeur(e.target);else if($trOpEdit.is(e.target))(new TrendEdit_Receiver).Routeur(e.target);else if($trOpCr.is(e.target))(new TrendEdit_Receiver).Routeur(e.target);else if($insMrTrg.is(e.target)){Kxlib_PreventDefault(e);
(new Ins_Receiver).Routeur(e.target)}else if($irr.is(e.target)){Kxlib_PreventDefault(e);Kxlib_StopPropagation(e);window.location.href="/login";return false}else if($rld.is(e.target)){Kxlib_PreventDefault(e);window.location.reload();return}else if($goto.is(e.target))window.location.href=$(e.target).attr("href");else if($chbxOpt.is(e.target))Kxlib_PreventDefault(e);else if($AtHmMn.is(e.target))(new ACHR_Receiver).Routeur(e.target);else if($flbmn.is(e.target))(new _FE_ENTY_FRD_RCVR).Routeur(e.target);
else if($tlkbOpt.is(e.target))$(e.target).trigger("cusmclick",e);else if($ubxMns.is(e.target))if($(e.target).data("action")&&$.inArray($(e.target).data("action"),["go_url","invite_friends"])!==-1&&!KgbLib_CheckNullity($(e.target).prop("href"))){var url=$(e.target).prop("href");window.location.href=url}else if($(e.target).data("action")&&$.inArray($(e.target).data("action"),["open_frdreq","bugzy"])!==-1){Kxlib_PreventDefault(e);$(e.target).trigger("tqr_cuev_click")}})}catch(ex){console.log('A "likely" fatal error occurred while processing an onclick event.')}
try{window.hasfocus=true;$(window).focus(function(){window.hasfocus=true}).blur(function(){window.hasfocus=false})}catch(ex){}try{window.isUnloading=false;$(window).on("beforeunload",function(){window.isUnloading=true})}catch(ex){}try{var currMousePos={x:-1,y:-1};$(document).mousemove(function(e){window.mouse_x=e.pageX;window.mouse_y=e.pageY})}catch(ex){}
try{window.mouseOnGame=false;$(document).mouseleave(function(e){window.mouseOnGame=false});$(document).mouseenter(function(e){window.mouseOnGame=true})}catch(ex){}var saveSelection,restoreSelection;
if(window.getSelection&&document.createRange){saveSelection=function(containerEl){var range=window.getSelection().getRangeAt(0);var preSelectionRange=range.cloneRange();preSelectionRange.selectNodeContents(containerEl);preSelectionRange.setEnd(range.startContainer,range.startOffset);var start=preSelectionRange.toString().length;return{start:start,end:start+range.toString().length}};restoreSelection=function(containerEl,savedSel){var charIndex=0,range=document.createRange();range.setStart(containerEl,
0);range.collapse(true);var nodeStack=[containerEl],node,foundStart=false,stop=false;while(!stop&&(node=nodeStack.pop()))if(node.nodeType==3){var nextCharIndex=charIndex+node.length;if(!foundStart&&savedSel.start>=charIndex&&savedSel.start<=nextCharIndex){range.setStart(node,savedSel.start-charIndex);foundStart=true}if(foundStart&&savedSel.end>=charIndex&&savedSel.end<=nextCharIndex){range.setEnd(node,savedSel.end-charIndex);stop=true}charIndex=nextCharIndex}else{var i=node.childNodes.length;while(i--)nodeStack.push(node.childNodes[i])}var sel=
window.getSelection();sel.removeAllRanges();sel.addRange(range)}}else if(document.selection&&document.body.createTextRange){saveSelection=function(containerEl){var selectedTextRange=document.selection.createRange();var preSelectionTextRange=document.body.createTextRange();preSelectionTextRange.moveToElementText(containerEl);preSelectionTextRange.setEndPoint("EndToStart",selectedTextRange);var start=preSelectionTextRange.text.length;return{start:start,end:start+selectedTextRange.text.length}};restoreSelection=
function(containerEl,savedSel){var textRange=document.body.createTextRange();textRange.moveToElementText(containerEl);textRange.collapse(true);textRange.moveEnd("character",savedSel.end);textRange.moveStart("character",savedSel.start);textRange.select()}}function geneventhandler(){$("#start-here").click(function(){})}
function setSelectionRange(input,selectionStart,selectionEnd){if(input.setSelectionRange){input.focus();input.setSelectionRange(selectionStart,selectionEnd)}else if(input.createTextRange){var range=input.createTextRange();range.collapse(true);range.moveEnd("character",selectionEnd);range.moveStart("character",selectionStart);range.select()}}
function getCaretCharacterOffsetWithin(element){var caretOffset=0;var doc=element.ownerDocument||element.document;var win=doc.defaultView||doc.parentWindow;var sel;if(typeof win.getSelection!="undefined"){var range=win.getSelection().getRangeAt(0);var preCaretRange=range.cloneRange();preCaretRange.selectNodeContents(element);preCaretRange.setEnd(range.endContainer,range.endOffset);caretOffset=preCaretRange.toString().length}else if((sel=doc.selection)&&sel.type!="Control"){var textRange=sel.createRange();
var preCaretTextRange=doc.body.createTextRange();preCaretTextRange.moveToElementText(element);preCaretTextRange.setEndPoint("EndToEnd",textRange);caretOffset=preCaretTextRange.text.length}return caretOffset}function showCaretPos(){var el=document.getElementById("npost_txt");return getCaretCharacterOffsetWithin(el)}
function handleHashtagInput(obj,k){if(k===32){var _rx=new RegExp(" #([a-zA-Z_]{2,}|[d]+[a-zA-Z_]{2,})");var _m=$(obj).html();var _ar=_m.match(_rx);if(_ar){var savedSelection=saveSelection(document.getElementById("npost_txt"));_m=_m.replace(_rx," <a class='kgb_blue_link gkb_blue_hyperlink' href='https://www.google.fr/?q=$1'>#$1</a>");$(obj).html(_m);restoreSelection(document.getElementById("npost_txt"),savedSelection)}}}
(function(){geneventhandler();$("#npost_txt").keyup(function(e){handleHashtagInput(this,e.which);$(".gkb_blue_hyperlink").click(function(){});$(".gkb_blue_hyperlink").hover(function(){$(this).toggleClass("gkb_blue_hyperlink_h")},function(){$(this).toggleClass("gkb_blue_hyperlink_h")})})})();var _com_action_sub_has_prior=false;
(function(){$(".action_a").focusout(function(e){if(e.target===this){e.stopPropagation();$(this).parent().children(".action_foll_choices").addClass("this_hide")}});$(".action_a").click(function(e){Kxlib_PreventDefault(e);$(this).focus();if(!$(this).parent().children(".action_foll_choices").hasClass("this_hide")){$(this).parent().children(".action_foll_choices").addClass("this_hide");$(this).blur();return}$(".action_foll_choices").not(this).addClass("this_hide");$(this).parent().children(".action_foll_choices").toggleClass("this_hide")});
$(".action_a").hover(function(){},function(){})})();$("#warning_bar_close_a").click(function(){$(this).parent().parent().toggleClass("this_hide")});function CountChar_IsHash(e){var _altgr=false;if(e.type==="keydown"&&e.which===17){_altgr=true;return false}else if(e.type==="keyup"&&e.which===17){_altgr=false;return false}if(e.type==="keyup"&&e.which===51){_hash=true;return true}else if(e.type==="keydown"&&e.which===51){_hash=false;return false}return false}
function CountChar_SkipHash(o){if(typeof o==="undefined")return;var t=$(o).val();var rn1=/(\#)(?=(?:(?=[a-z\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00c6\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00e6\u1eaf\u1ea1\u1eb6\u1eb7\u1eb0\u1eb1\u1ea2\u1ea3\u00de\u00df\u00fe\u00c7\u00e7\u0110\u0111\u0189\u0256\u00d0\u00f0\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u1ec1\u1ec7\u0118\u0119\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u0142\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u0398\u00f2\u00f3\u00f4\u00f5\u00f6\u01a1\u1edf\u00f8\u00d1\u00f1\u2c63\u1d7d\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u1ef1\u00ff\u00dd\u00fd\u0160\u017d\u017e\u017c])|(?:[\d_](?=[a-z\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00c6\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00e6\u1eaf\u1ea1\u1eb6\u1eb7\u1eb0\u1eb1\u1ea2\u1ea3\u00de\u00df\u00fe\u00c7\u00e7\u0110\u0111\u0189\u0256\u00d0\u00f0\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u1ec1\u1ec7\u0118\u0119\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u0142\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u0398\u00f2\u00f3\u00f4\u00f5\u00f6\u01a1\u1edf\u00f8\u00d1\u00f1\u2c63\u1d7d\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u1ef1\u00ff\u00dd\u00fd\u0160\u017d\u017e\u017c])))[a-z\d_\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00c6\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00e6\u1eaf\u1ea1\u1eb6\u1eb7\u1eb0\u1eb1\u1ea2\u1ea3\u00de\u00df\u00fe\u00c7\u00e7\u0110\u0111\u0189\u0256\u00d0\u00f0\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u1ec1\u1ec7\u0118\u0119\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u0142\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u0398\u00f2\u00f3\u00f4\u00f5\u00f6\u01a1\u1edf\u00f8\u00d1\u00f1\u2c63\u1d7d\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u1ef1\u00ff\u00dd\u00fd\u0160\u017d\u017e\u017c]+)/gi;
var rn2=/(\@)(?=(?=.*[a-z])[\w\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00c6\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00e6\u1eaf\u1ea1\u1eb6\u1eb7\u1eb0\u1eb1\u1ea2\u1ea3\u00de\u00df\u00fe\u00c7\u00e7\u0110\u0111\u0189\u0256\u00d0\u00f0\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u1ec1\u1ec7\u0118\u0119\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u0142\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u0398\u00f2\u00f3\u00f4\u00f5\u00f6\u01a1\u1edf\u00f8\u00d1\u00f1\u2c63\u1d7d\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u1ef1\u00ff\u00dd\u00fd\u0160\u017d\u017e\u017c]{2,20})/gi;
if($(o).hasClass("skip_sharp"))try{if(t.indexOf("#")!==-1|t.indexOf("@")!==-1){t=t.replace(rn1,"");t=t.replace(rn2,"");return t.length}else return t.length}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}else return t.length}
function CountChar_SkipHash2(t){try{if(!(typeof t==="string"&&t))return;var rn1=/(\#)(?![\#\s]+)(?=.+)/g;var rn2=/(\@)(?![\@\s]+)(?=.+)/g;if(t.indexOf("#")!==-1|t.indexOf("@")!==-1){t=t.replace(rn1,"");t=t.replace(rn2,"");return t.length}else return t.length}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}}
function CountChar_HandleTypeInInput(e){var t=$(this),_nb=0,_max=$(this).data("maxch"),_tarSel=Kxlib_ValidIdSel($(this).data("target"));_nb=CountChar_SkipHash(t);var _newNb=_max-_nb;if(_newNb<0)$(_tarSel).addClass("red");else $(_tarSel).removeClass("red");$(_tarSel).html(_newNb)}$(".check_char").bind("keyup keydown focus blur change",CountChar_HandleTypeInInput);
function Revs_HandleClick(e){$obj=$(e.target);var _rvTxt=$obj.data("revs");if(!KgbLib_CheckNullity(_rvTxt)){var _txt=$obj.html();$obj.data("revs",_txt);$obj.html(_rvTxt)}}$(".back_to_60s a").click(function(e){Kxlib_PreventDefault(e);$("#toptop").animatescroll({element:".in_slave_list",padding:20});$(".in_slave_list").scrollTop(0);$(".in_slave_list").perfectScrollbar();$(".in_slave_list").perfectScrollbar("update")});
$(".kxlib-reset-form").click(function(e){Kxlib_PreventDefault(e);try{var tar=$(this).data("target");Kxlib_ResetForm(tar)}catch(e){return}});$(".jb-kxlib-close").click(function(e){Kxlib_PreventDefault(e);$(Kxlib_ValidIdSel($(this).data("target"))).addClass("this_hide")});$("a.this_noway, a.this_noway *").click(function(e){Kxlib_PreventDefault(e)});
$(".jb-cnxsgn-o-ws-tgr").click(function(e){Kxlib_PreventDefault(e);var h=$(".jb-cnxsgn-o-whysgn-mx").height();var t__;if($(".jb-cnxsgn-o-whysgn-mx").css("top")==="0px"|$(this).hasClass("closed")){t__=h*-1;$(this).switchClass("closed","open")}else{t__="0px";$(this).switchClass("open","closed")}$(".jb-cnxsgn-o-whysgn-mx").stop(true,true).animate({top:t__})});$(".jb-asdr-w-ads-wa-lk").click(function(e){Kxlib_PreventDefault(e);$(".jb-cnxsgn-ovly-sprt").removeClass("this_hide")});
$(".fcb_img").off("hover").hover(function(e){$(this).children(".fcb_img_link").addClass("fcb_img_link_hover");$(this).parent().children(".bot_fade").addClass("bot_fade_sp");var $par=$(this).closest(".fcb_img");if($par.find(".jb-tqr-artml-onhvr-tm").length)$par.find(".jb-tqr-artml-onhvr-tm").removeClass("this_hide");if($par.find(".jb-tqr-am-ax-box").length)$par.find(".jb-tqr-am-ax-box").removeClass("this_hide")},function(e){$(this).children(".fcb_img_link").removeClass("fcb_img_link_hover");$(this).parent().children(".bot_fade").removeClass("bot_fade_sp");
var $par=$(this).closest(".fcb_img");if($par.find(".jb-tqr-artml-onhvr-tm").length)$par.find(".jb-tqr-artml-onhvr-tm").addClass("this_hide");if($par.find(".jb-tqr-am-ax-box").length)$par.find(".jb-tqr-am-ax-box").addClass("this_hide")});$(".jb-tmlnr-loadm-trg[data-scp='ml'], .jb-tmlnr-loadm-trg[data-scp='tr'], .jb-tmlnr-loadm-trg[data-scp='fv']").hover(function(){$(this).closest(".jb-nwfd-loadm-box.tmlnr").addClass("hover")},function(){$(this).closest(".jb-nwfd-loadm-box.tmlnr").removeClass("hover")});
$(".jb-trpg-loadm-trg").hover(function(){$(this).closest(".jb-trpg-loadm-box").addClass("hover")},function(){$(this).closest(".jb-trpg-loadm-box").removeClass("hover")});if($("div[s-id='TQR_WLC_INS']").length)$(".jb-tqr-why-signup-ftr-mxe").remove();
$(".jb-tqr-why-sgu-tle-tgr").click(function(e){Kxlib_PreventDefault(e);if($(".jb-tqr-why-signup-bmx").data("stt")==="hell"){$(".jb-tqr-why-sgu-clz").addClass("this_hide");$(".jb-tqr-why-signup-bmx").stop(true,true).animate({bottom:0},function(){$(this).data("stt","heaven")})}else $(".jb-tqr-why-signup-bmx").stop(true,true).animate({bottom:-504},function(){$(this).data("stt","hell");$(".jb-tqr-why-sgu-clz").removeClass("this_hide")})});
$(".jb-tqr-why-sgu-clz").click(function(e){Kxlib_PreventDefault(e);$(".jb-tqr-why-signup-bmx").stop(true,true).fadeOut(1E3).remove()});$(".jb-tqr-btm-lock-clz").click(function(e){Kxlib_PreventDefault(e);$(".jb-tqr-btm-lock-fd").stop(true,true).fadeOut(function(){$(this).addClass("this_hide").removeAttr("style")});$(".jb-tqr-btm-lock").stop(true,true).fadeOut(function(){$(this).addClass("this_hide").removeAttr("style")})});
var docCookies={getItem:function(sKey){if(!sKey)return null;return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null},setItem:function(sKey,sValue,vEnd,sPath,sDomain,bSecure){if(!sKey||/^(?:expires|max\-age|path|domain|secure)$/i.test(sKey))return false;var sExpires="";if(vEnd)switch(vEnd.constructor){case Number:sExpires=vEnd===Infinity?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":
"; max-age="+vEnd;break;case String:sExpires="; expires="+vEnd;break;case Date:sExpires="; expires="+vEnd.toUTCString();break}document.cookie=encodeURIComponent(sKey)+"="+encodeURIComponent(sValue)+sExpires+(sDomain?"; domain="+sDomain:"")+(sPath?"; path="+sPath:"")+(bSecure?"; secure":"");return true},removeItem:function(sKey,sPath,sDomain){if(!this.hasItem(sKey))return false;document.cookie=encodeURIComponent(sKey)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(sDomain?"; domain="+sDomain:"")+(sPath?
"; path="+sPath:"");return true},hasItem:function(sKey){if(!sKey)return false;return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie)},keys:function(){var aKeys=document.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/);for(var nLen=aKeys.length,nIdx=0;nIdx<nLen;nIdx++)aKeys[nIdx]=decodeURIComponent(aKeys[nIdx]);return aKeys},getAllItems:function(JSONmode){if(JSONmode&&document.cookie){var aKeys=
this.keys(),vlky={};for(var nLen=aKeys.length,nIdx=0;nIdx<nLen;nIdx++)vlky[decodeURIComponent(aKeys[nIdx])]=this.getItem(decodeURIComponent(aKeys[nIdx]));return vlky}else return document.cookie}};
