function KxDate(ml){this.y;this.m;this.d;this.h;this.mi;this.s;this.ml;this.UTC=0;this.gt;this.gtUTC;this.yr;this._ResetAllFields=function(){this.y=this.m=this.d=this.h=this.mi=this.s=this.ml=null};this.YearIsLeap=function(yr){return yr%400===0||yr%4===0&&!(yr%100===0)?true:false};this._GetLocalTMZ=function(){var foo=new Date;var bar=new KxDate;var tp1=foo.getHours()-bar.getHours();tp1*=36E5;var tp2=foo.getMinutes()-bar.getMinutes();tp2*=6E4;var tp3=tp1+tp2;return tp3};this.RemoveTimeFromTSTP=function(){var y=
this.getYear(),m=this.getMonth(),d=this.getDate();return d.toString()+m.toString()+y.toString()};this.RemoveTimeFromTSTP2=function(){var y=this.getFullYear(),m=this.getMonth(),d=this.getDate();m+=1;d=d<10?"0"+d:d;m=m<10?"0"+m:m;return y.toString()+m.toString()+d.toString()};this.WriteDate=function(u){var sd="";var auj=new KxDate;auj.SetUTC(this.UTC);var tp=auj.getTime()-864E5;var hier=new KxDate(tp);hier.SetUTC(this.UTC);if(this.getDate().toString()+this.getMonth().toString()+this.getYear().toString()===
auj.getDate().toString()+auj.getMonth().toString()+auj.getYear().toString())return Kxlib_getDolphinsValue("TIME_TODAY");else if(this.getDate().toString()+this.getMonth().toString()+this.getYear().toString()===hier.getDate().toString()+hier.getMonth().toString()+hier.getYear().toString())return Kxlib_getDolphinsValue("TIME_YESTD");if(this.getYear()===auj.getYear())if(Kxlib_getDolphinsValue("TG_USER_TMLANG")==="UNV"){sd=this.getDate().toString();sd+=" ";sd+=Kxlib_getDolphinsValue("TG_MONTH_"+this.getMonth().toString());
return sd}else{sd=Kxlib_getDolphinsValue("TG_MONTH_"+this.getMonth().toString());sd+=" ";sd+=this.getDate().toString();return sd}else{sd=this.getDate().toString();sd+=" ";sd+=Kxlib_getDolphinsValue("TG_MONTH_"+this.getMonth().toString());sd+=" ";sd+=this.getYear().toString();return sd}};this.getFullYear=function(){var yr=1970,ytr,cry=1970,lgt=this.gtUTC,halt=(new Date).getFullYear();var anb=31536E6;var ab=316224E5;while(true){if(this.YearIsLeap(yr))ytr=ab;else ytr=anb;lgt-=ytr;if(lgt===0){this.y=
++yr;return this.y;break}else if(lgt<0){this.y=yr;return this.y;break}if(yr>halt)break;++yr}return this.y};this.getYear=function(){var y=this.getFullYear();var ny=parseInt(y.toString().substr(2,2));return ny};this._GetRestAfterYearOpe=function(){var yr=1970,ytr,cry=1970,lgt=this.gtUTC,halt=(new Date).getFullYear();var anb=31536E6;var ab=316224E5;while(true){if(this.YearIsLeap(yr))ytr=ab;else ytr=anb;var lgt_bf=lgt;lgt-=ytr;if(lgt===0){this.y=++yr;var foo=[0,this.YearIsLeap(this.y)?ab:anb];return foo;
break}else if(lgt<0){this.y=yr;var bar=[lgt_bf,this.YearIsLeap(this.y)?true:false];return bar;break}if(yr>halt){this.y=yr;break}++yr}return this.y};this.getMonth=function(){var foo=this._GetRestAfterYearOpe();var c=0,mtr=foo[0],isLeap=foo[1];if(!$.isArray(foo))return;if(foo[0]<26784E5)return c;for(c;c<12;c++){switch(c){case 0:case 2:case 4:case 6:case 7:case 9:case 11:mtr-=31*864E5;break;case 3:case 5:case 8:case 10:mtr-=30*864E5;break;case 1:mtr-=isLeap?29*864E5:28*864E5;break}if(mtr===0){this.m=
++c;return this.m;break}else if(mtr<0){this.m=c;return this.m;break}}};this._GetRestAfterMonthOpe=function(){var foo=this._GetRestAfterYearOpe();var c=0,mtr=foo[0],isLeap=foo[1],mtr_bf=0;if(foo[0]<26784E5)return foo[0];for(c;c<12;c++){mtr_bf=mtr;switch(c){case 0:case 2:case 4:case 6:case 7:case 9:case 11:mtr-=31*864E5;break;case 3:case 5:case 8:case 10:mtr-=30*864E5;break;case 1:mtr-=isLeap?29*864E5:28*864E5;break}if(mtr===0){this.m=++c;return 0;break}else if(mtr<0){this.m=c;return mtr_bf;break}}};
this.getDate=function(){var lft=this._GetRestAfterMonthOpe(),cn=1;if(lft<864E5)return 1;while(true){lft-=864E5;if(lft===0){this.d=++cn;return this.d;break}else if(lft<0){this.d=cn;return this.d;break}if(cn>31)break;++cn}};this._GetRestAfterDateOpe=function(){var lft=this._GetRestAfterMonthOpe(),cn=1,lft_bf=0;if(lft<864E5)return lft;while(true){lft_bf=lft;lft-=864E5;if(lft===0){this.d=++cn;return 0;break}else if(lft<0){this.d=cn;return lft_bf;break}if(cn>31)break;++cn}};this.getHours=function(){var lft=
this._GetRestAfterDateOpe(),cn=0,lft_bf=0;if(lft<36E5)return 0;while(true){lft_bf=lft;lft-=36E5;if(lft===0){this.h=++cn;return this.h;break}else if(lft<0){this.h=cn;return this.h;break}if(cn>23)break;++cn}};this._GetRestAfterHoursOpe=function(){var lft=this._GetRestAfterDateOpe(),cn=0,lft_bf=0;if(lft<36E5)return lft;while(true){lft_bf=lft;lft-=36E5;if(lft===0){this.h=++cn;return 0;break}else if(lft<0){this.h=cn;return lft_bf;break}if(cn>23)break;++cn}};this.getMinutes=function(){var lft=this._GetRestAfterHoursOpe(),
cn=0,lft_bf=0;if(lft<6E4)return 0;while(true){lft_bf=lft;lft-=6E4;if(lft===0){this.mi=++cn;return this.mi;break}else if(lft<0){this.mi=cn;return this.mi;break}if(cn>59)break;++cn}};this._GetRestAfterMinutesOpe=function(){var lft=this._GetRestAfterHoursOpe(),cn=0,lft_bf=0;if(lft<6E4)return lft;while(true){lft_bf=lft;lft-=6E4;if(lft===0){this.mi=++cn;return 0;break}else if(lft<0){this.mi=cn;return lft_bf;break}if(cn>59)break;++cn}};this.getSeconds=function(){var lft=this._GetRestAfterMinutesOpe(),cn=
0,lft_bf=0;if(lft<1E3)return 0;while(true){lft_bf=lft;lft-=1E3;if(lft===0){this.s=++cn;return this.s;break}else if(lft<0){this.s=cn;return this.s;break}if(cn>59)break;++cn}};this._GetRestAfterSecondsOpe=function(){var lft=this._GetRestAfterMinutesOpe(),cn=0,lft_bf=0;if(lft<1E3)return lft;while(true){lft_bf=lft;lft-=1E3;if(lft===0){this.s=++cn;return lft;break}else if(lft<0){this.s=cn;return lft_bf;break}if(cn>59)break;++cn}};this.getMilliseconds=function(){var lft=this._GetRestAfterSecondsOpe();this.ml=
lft;return this.ml};this.getTime=function(){return this.gt};this.SetUTC=function(a){switch(typeof a){case "boolean":case "undefined":if(KgbLib_CheckNullity(a)){if(!KgbLib_CheckNullity(this.UTC)){this._ResetAllFields();this.UTC=0;this.gtUTC=this.gt}}else{this.UTC=this._GetLocalTMZ();this.gtUTC=this.gt+this.UTC}break;case "string":if(!KgbLib_CheckNullity(a)){var ml=1,v=0;if(a.toString().indexOf("-")!==-1){a=a.toString().replace("-","");ml=-1}else if(a.toString().indexOf("+")!==-1)a=a.toString().replace("+",
"");if(a.toString().indexOf(":")!==-1){var b=a.toString().split(":");v=parseInt(b[0])*36E5;v+=parseInt(b[1])*6E4;v*=ml}else{v=parseInt(a)*36E5;v*=ml}this.UTC=v;this.gtUTC=this.gt+this.UTC}break;case "number":this.gtUTC=this.gt+a;this._ResetAllFields();this.UTC=a;break}};var th=this;(function(){if(typeof ml==="boolean"&&ml){th.UTC=th._GetLocalTMZ();th.gtUTC=ml+th.UTC;th._ResetAllFields()}else if(typeof ml==="number"){th.gt=ml;th.gtUTC=ml}else if(typeof ml==="string"&&(new Date(parseInt(ml))).getTime()>
0){th.gt=parseInt(ml);th.gtUTC=parseInt(ml)}else if(typeof ml==="undefined"){th.gt=(new Date).getTime();th.gtUTC=(new Date).getTime()}})()};
