Kxlib_GetColumn=function(cn,o){if(!(typeof o==="object"&&Object.keys(o).length)|!((typeof cn==="string"||typeof cn==="number")&&cn))return;var no=[];var fnd=0;for(var x in o){var e=o[x];if(typeof cn==="number"){var t__=Object.keys(e);cn=t__[cn]!==undefined?t__[cn]:null}if(cn&&e!==undefined&&e.hasOwnProperty(cn)&&e[cn]){no.push(e[cn]);++fnd}}return fnd?no:false};
function KgbLib_CheckNullity(arg){if(!(arg===null|typeof arg==="undefined"|arg===""|arg==="''"|(arg&&arg.length===0))&&!$.isArray(arg))return false;else if(!(arg===null|typeof arg==="undefined"|arg===""|(arg&&arg.length===0))&&$.isArray(arg))$.each(arg,function(i,v){if(KgbLib_CheckNullity(v))return true});else return true;return false}
function KgbLib_ReverseText(id,attr_source,do_it){if(KgbLib_CheckNullity([id,attr_source]))return;do_it=KgbLib_CheckNullity(do_it)?false:true;try{$o=$(id);var _n=$o.data(attr_source)}catch(e){return e}if(KgbLib_CheckNullity(_n)&&_n===""&&!do_it)return 0;var _old=$o.html();$o.html(_n);$o.data(attr_source,_old);return 1}
function CreateCookie(name,value,days){var expires;if(days){var date=new Date;date.setTime(date.getTime()+days*24*60*60*1E3);expires="; expires="+date.toGMTString()}else expires="";document.cookie=name+"="+value+expires+"; path=/"}function EraseCookie(name){CreateCookie(name,"",-1)}
function ReadCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(";");for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)===" ")c=c.substring(1,c.length);if(c.indexOf(nameEQ)===0)return c.substring(nameEQ.length,c.length)}return null}
function Kx_XHR_Send(data,before,oncomplete,onsuccess,onerror,options){try{if(window.isUnloading===true){console.log("NOTICE : Your asynchronous request has been aborted due to an unloading event");return}before=typeof before!=="undefined"&&typeof before==="function"?before:function(){};oncomplete=typeof oncomplete!=="undefined"&&typeof oncomplete==="function"?oncomplete:function(jqXHR,err){};url=typeof options==="object"&&options.hasOwnProperty("url")&&typeof options.url==="string"&&options.url?
options.url:null;type=typeof options==="object"&&options.hasOwnProperty("type")&&typeof options.type==="string"&&options.type?options.type:null;wcrdtl=typeof options==="object"&&options.hasOwnProperty("wcrdtl")&&typeof options.wcrdtl==="boolean"?options.wcrdtl:false;var xhr=$.ajax({data:data,url:url,type:type,xhrFields:{withCredentials:wcrdtl},contentType:"application/x-www-form-urlencoded; charset=UTF-8",error:onerror,beforeSend:before,complete:oncomplete,success:onsuccess});return xhr}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}}function Kx_XHR_Get(type,requrl,onerror,onsuccess){$.ajax({url:requrl,type:"get",dataType:"json",error:onerror,beforeSend:function(){},complete:function(){},success:onsuccess});return false}function Kxlib_IsSquare(h,w){return h/w===1?1:0}function Kxlib_ObjectChild_Count(a){if(KgbLib_CheckNullity(a))return;var s=0,o=a;for(k in o)if(o.hasOwnProperty(k))s++;return s}
function Kxlib_encodeURL(str){if(KgbLib_CheckNullity(s))return;return str.replace(/\+/g,"-").replace(/\//g,"_").replace(/\=+$/,"")}function Kxlib_EscapeHTMLEntity(s){if(KgbLib_CheckNullity(s))return;return s.replace(/[<]+/g,"&#60;").replace(/[>]+/g,"&#62;").replace(/\"/g,"&quot;")}function Kxlib_EscapeComa(s){if(KgbLib_CheckNullity(s))return;return s.replace(/\,/g,"&#44;")}
function Kxlib_EscapeForDataCache(s){if(KgbLib_CheckNullity(s))return;return s.replace(/\,/g,"\\&#44;").replace(/\[/g,"&#91;").replace(/\]/g,"&#93;").replace(/\"/g,"\\&quot;").replace(/\'/g,"\\&#39;").replace(/\\/g,"\\&#92;")}function Kxlib_Decode_EscapeForDataCache(s){if(KgbLib_CheckNullity(s)&&s!=="''")return;return s.replace(/\\{2}(?:,)/g,"&#44;").replace(/\\{2}(?:"")/g,"&quot;").replace(/\\{2}(?:')/g,"&#39;").replace(/\\{2}(?!,|')/g,"&#92;").replace(/&#92;n/g,"<br/>")}
function Kxlib_getDolphinsValue(a){try{var m=DOLPHINS_H(a);return KgbLib_CheckNullity(m)?false:m}catch(ex){return}}function Kxlib_GetAjaxRules(uq,uz){if(KgbLib_CheckNullity(uq))return;try{var o=!KgbLib_CheckNullity(uz)?AJAXRULES(uq,uz):AJAXRULES(uq);if(KgbLib_CheckNullity(o))return false;else return o}catch(ex){return-1}}function Kxlib_GetFeatRules(c){if(KgbLib_CheckNullity(c))return;var ob=window.FeatRules;if(KgbLib_CheckNullity(ob))return;return!ob.hasOwnProperty(c)?false:ob[c]}
function Kxlib_DebugVars(a,fa){if(KgbLib_CheckNullity(ENV_VARS("SYS_ENV_RUNG_MODE"))||ENV_VARS("SYS_ENV_RUNG_MODE")!=="DEV"&&ENV_VARS("SYS_ENV_RUNG_MODE")!=="TEST"&&ENV_VARS("SYS_ENV_RUNG_MODE")!=="DEBUG")return;if(!KgbLib_CheckNullity(ENV_VARS("SYS_ENV_SHW_DBGVARS_MD"))&&ENV_VARS("SYS_ENV_SHW_DBGVARS_MD")===0)return;if(KgbLib_CheckNullity(a)){var dt=new Date;var dis="FR_TIME_MODE ["+dt.getDate()+"-"+dt.getMonth()+"-"+dt.getFullYear()+" | "+dt.getHours()+":"+dt.getMinutes()+":"+dt.getSeconds()+":"+
dt.getMilliseconds()+"]";dis+=" : ";dis+="La variable est de type NULL";if(fa&&ENV_VARS("SYS_ENV_SHW_DBGVARS_MD")!==2)alert(dis);else if(ENV_VARS("SYS_ENV_SHW_DBGVARS_MD")!==1);return}if(!$.isArray(a))return;var m="";if(a.length===1)m="VAL => "+a[0];else{var n=0;$.each(a,function(x,v){++n;if(m==="")m="VAL"+n+" => "+v+";";else m+=" VAL"+n+" => "+v+";"})}if(fa&&ENV_VARS("SYS_ENV_SHW_DBGVARS_MD")!==2){var dt=new Date;var dis="FR_TIME_MODE ["+dt.getDate()+"-"+dt.getMonth()+"-"+dt.getFullYear()+" | "+
dt.getHours()+":"+dt.getMinutes()+":"+dt.getSeconds()+":"+dt.getMilliseconds()+"]";dis+=" : ";m=KgbLib_CheckNullity(m)?"void":m;dis+=m;alert(dis)}else if(ENV_VARS("SYS_ENV_SHW_DBGVARS_MD")!==1)console.log(m)}function Kxlib_ResetForm(s){try{if(KgbLib_CheckNullity(s))return;var ns=Kxlib_ValidIdSel(s);$(ns).each(function(){this.reset()});$(ns).trigger("formcleared")}catch(e){return}}
function Kxlib_ClearForm(s){if(KgbLib_CheckNullity(s))return;var ns=Kxlib_ValidIdSel(s);try{var frm_elements=document.getElementById(s).elements;$(frm_elements).each(function(){var field_type=this.type.toLowerCase();switch(field_type){case "text":case "password":case "textarea":case "hidden":this.value="";break;case "radio":case "checkbox":if(this.checked)this.checked=false;break;case "select-one":case "select-multi":if($(this).find("option[value='init']").length)$(this).find("option[value='init']").attr("selected",
true);else this.selectedIndex=-1;break;default:break}})}catch(e){return}$(ns).trigger("formcleared")}function Kxlib_ResetFormElt(e){if(KgbLib_CheckNullity(e))return;var o=Kxlib_ValidIdSel(e);$(o).wrap("<form>").closest("form").get(0).reset();$(o).unwrap()}function Kxlib_Trim(s){return s.replace(/^\s+|\s+$/gm,"")}function Kxlib_Strip_Specials(s){return s.replace(/([<>\-'"/]+)/g,function(m){return"\\"+m})}
function Kxlib_Extract_All_DMD(s){if(KgbLib_CheckNullity(s))return;var d;d=s.match(/%([a-zA-Z\d_-]+)%(?=[\s]{1}|)/g);if(Array.isArray(d)&&d.length)return d;else return false}function Kxlib_DolphinsReplaceDmd(s,c,r){if(KgbLib_CheckNullity(c)||KgbLib_CheckNullity(r)||KgbLib_CheckNullity(s)||typeof s!=="string")return;c=!c.match(/^\%.+\%$/)?"%"+c+"%":c;if(s.indexOf(c)>-1)return s.replace(new RegExp(c,"g"),r);else return false}
function Kxlib_IsIE(){if($("html").is(".ie6, .ie7, .ie8, ie9"))return true;else{var ua=window.navigator.userAgent;var msie=ua.indexOf("MSIE ");if(msie>0||!!navigator.userAgent.match(/Trident.*rv\:11\./))return true;else return false}}
function Kxlib_NvgtrSayWho(){var ua=navigator.userAgent,tem,M=ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(M[1])){tem=/\brv[ :]+(\d+)/g.exec(ua)||[];return{name:"IE",version:tem[1]||""}}if(M[1]==="Chrome"){tem=ua.match(/\bOPR\/(\d+)/);if(tem!==null)return{name:"Opera",version:tem[1]}}M=M[2]?[M[1],M[2]]:[navigator.appName,navigator.appVersion,"-?"];if((tem=ua.match(/version\/(\d+)/i))!==null)M.splice(1,1,tem[1]);return{name:M[0],version:M[1]}}
function Kxlib_NvgtrIsMobile(){return/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,
4))?true:false}function Kxlib_ValidIdSel(a){return a.toString().indexOf("#")===-1?"#"+a:a}function Kxlib_ValidClassSel(a){return a.toString().indexOf(".")===-1?"."+a:a}function Kxlib_ValidUser(a){return a.toString().indexOf("@")===-1?"@"+a:a}function Kxlib_ToPxUnit(a){return typeof a==="string"?a+"px":a.toString()+"px"}function Kxlib_Exists(s){var ns=Kxlib_ValidIdSel(s);return $(ns).length?true:false}
function Kxlib_ValidMyEval(a){if(KgbLib_CheckNullity(a))return;switch(a.toString().toLowerCase()){case "p2":case "p1":case "m1":return a;break;default:return"";break}return""}
function Kxlib_Log(m){return;if(KgbLib_CheckNullity(window.rm)||window.rm!=="DEV"&&window.rm!=="TEST"&&window.rm!=="DEBUG")return;var dt=new Date;var dis="FR_TIME_MODE ["+dt.getDate()+"-"+dt.getMonth()+"-"+dt.getFullYear()+" | "+dt.getHours()+":"+dt.getMinutes()+":"+dt.getSeconds()+":"+dt.getMilliseconds()+"]";dis+=" => ";m=KgbLib_CheckNullity(m)?"void":m;dis+=m;Kxlib_DebugVars([is])}
function Kxlib_GetPagegProperties(){var r={"pg":$("meta[property='tq:pg']").attr("content"),"ver":$("meta[property='tq:ver']").attr("content")};return r}
function Kxlib_GetOwnerPgPropIfExist(){try{if($("meta[property='tq:ufn']").length){var r={"ueid":$("meta[property='tq:ueid']").attr("content"),"uppic":$("meta[property='tq:uppic']").attr("content"),"ufn":$("meta[property='tq:ufn']").attr("content"),"upsd":$("meta[property='tq:upsd']").attr("content"),"uhref":$("meta[property='tq:uhref']").attr("content"),"udl":$("meta[property='tq:udl']").attr("content"),"ucity":$("meta[property='tq:ucity']").attr("content"),"ucn":$("meta[property='tq:ucn']").attr("content")};
return r}}catch(ex){a}}function Kxlib_GetCurUserPropIfExist(){if($("#user-id-card").length&&!KgbLib_CheckNullity($("#user-id-card").data("cache"))){var s=$("#user-id-card").data("cache");var d=Kxlib_DataCacheToArray(s)[0];var r={"ueid":d[0],"ufn":d[1],"upsd":d[2],"uppic":d[3],"uhref":d[4],"ucity":d[5],"rel":d[6]};return r}return}
function Kxlib_ChangeActorsUrel(r){if(KgbLib_CheckNullity(r))return;try{var c=$("#user-id-card").data("cache");if(KgbLib_CheckNullity(c))return;var s=Kxlib_AlterDataCacheAt(c,r.toLowerCase(),0,6);$("#user-id-card").data("cache",s);return s}catch(e){return-1}}
function Kxlib_GetTrendPropIfExist(){if($("meta[property='tq:ufn']").length){var r={"trid":$("meta[property='tq:trid']").attr("content"),"trttl":$("meta[property='tq:trtitle']").attr("content"),"trdesc":$("meta[property='tq:trdesc']").attr("content"),"trcat":$("meta[property='tq:trcat']").attr("content"),"trakx":$("meta[property='tq:trakx']").attr("content"),"trgrat":$("meta[property='tq:trgrat']").attr("content")};return r}}
function Kxlib_DCGetSection(st){if(KgbLib_CheckNullity(st)||typeof st!=="string")return;st=Kxlib_TrimReplace(st,"");var l=st.match(/\'([\s\S]*?)\'(?=(?:\,|$))/g);if(l===null){var s=st.replace(/\[|\]/g,"");return s.split(",")}$.each(l,function(x,v){v=Kxlib_TrimReplace(v,"");if(v==="''")l[x]="";else l[x]=Kxlib_Decode_EscapeForDataCache(v)});return l}
function Kxlib_DataCacheToArray(s){if(KgbLib_CheckNullity(s)|typeof s!=="string")return;var t=s.match(/\[(?!\[)([\s\S]*?)\](?!')/g);if(t.length===1){var s=t[0];return[Kxlib_DCGetSection(s),1]}else if(t.length>1)try{var r=new Array;$.each(t,function(x,v){r.push(Kxlib_DCGetSection(v))});return[r,t.length]}catch(e){return-1}else return 0}
function Kxlib_GetDataCacheAt(t,x1,x2){if(KgbLib_CheckNullity(t)||KgbLib_CheckNullity(x1))return;var x=t.match(/^\[(?!\[)([\s\S]*?)\](?=(?:\,|$))$/);if(!x)return 0;var r=Kxlib_DataCacheToArray(t);if(typeof r[0][x1]==="undefined")return;else{if(KgbLib_CheckNullity(x2))return r[0][x1].toString();if(typeof r[0][x1][x2]==="undefined")return;return r[0][x1][x2]}}
function Kxlib_AlterDataCacheAt(t,n,x1,x2){if(KgbLib_CheckNullity(t)|typeof n==="undefined"|KgbLib_CheckNullity(x1)|$.isArray(n))return;try{var x=t.match(/^\[(?!\[)([\s\S]*?)\](?=(?:\,|$))$/);if(!x)return 0;var r=Kxlib_DataCacheToArray(t),s="";if(typeof r[0][x1]==="undefined")return;else if(KgbLib_CheckNullity(x2)){$.each(r[0],function(x,v){if(x1===x)s+=n;else s+="['"+v.join("','")+"']";if(x<r[0].length-1)s+=","});return s}else if(r[1]===1)if(typeof r[0][x2]==="undefined")return;else{r[0][x2]=n;if(r[0].length===
1)return"['"+r[0][x2]+"']";else{s="['"+r[0].join("','")+"']";return s}}else if(r[1]>1)if(typeof r[0][x1][x2]==="undefined")return;else{r[0][x1][x2]=n;$.each(r[0],function(x,v){if(v.length===1)s+="['"+v+"']";else s+="['"+v.join("','")+"']";if(x<r[0].length-1)s+=","});return s}else return s}catch(e){}}function Kxlib_ReplaceAt(str,index,chr){if(index>str.length-1)return str;return str.substr(0,index)+chr+str.substr(index+1)}
function Kxlib_TrimReplace(str,chr){try{var l=str.length;if(l===1||l===2)return str;return chr+str.substr(1,l-2)+chr}catch(e){}}function Kxlib_ReplaceIfUndefined(e,re){re=typeof re==="undefined"?"":re;if(typeof e!=="undefined"&&e!==null&&($.isArray(e)||typeof e==="object")){$.each(e,function(x,v){if(typeof v==="undefined"||v===null)e[x]=re;else if($.isArray(v)||typeof e==="object")e[x]=Kxlib_ReplaceIfUndefined(v,re)});return e}else if(KgbLib_CheckNullity(e))return re;return e}
function Kxlib_AjaxIsErrVolatile(s){if(KgbLib_CheckNullity(s))return;var r=s.match(/^\s?__ERR_VOL_.+/)?true:false;return r}function Kxlib_HandleCurrUserGone(){location.reload()}function Kxlib_HandleTrdMustReload(t,m,f,r,isb){if(KgbLib_CheckNullity(m)|KgbLib_CheckNullity(r)|KgbLib_CheckNullity(isb))return;var bbd=isb===true?new BlackBoardDialog:new WhiteBoardDialog;var o={title:t,message:m,fly:f,redir:r};bbd.Dialog(o)}
function Kxlib_AJAX_HandleFailed(gc,o){var dc="ERR_COM_AJAX_FAIL";var ce=KgbLib_CheckNullity(gc)?dc:gc;var Nty=new Notifyzing;if(KgbLib_CheckNullity(o))Nty.FromUserAction(ce,null,true);else Nty.FromUserAction(ce,o,true)}function Kxlib_AJAX_HandleDeny(gc,o){var dc="ERR_COM_AJAX_DENY";var ce=KgbLib_CheckNullity(gc)?dc:gc;var Nty=new Notifyzing;if(KgbLib_CheckNullity(o))Nty.FromUserAction(ce,null,true);else Nty.FromUserAction(ce,o,true)}
function Kxlib_AjaxGblOnErr(xhr,ts){if(KgbLib_CheckNullity(xhr)&&KgbLib_CheckNullity(ts))return;switch(ts){case "timeout":break;case "error":break;case "abort":break;case "timeout":break;case "parsererror":break;default:ts=null;break}if(!xhr.hasOwnProperty("status")|!xhr.status)return false;switch(xhr.status){case 301:break;case 302:break;case 400:break;case 401:console.clear();var KD=new Kxlib_Dialog;KD.title=null;KD.message="Vous n'\u00eates sans doute pas autoris\u00e9 \u00e0 effectuer cette action. Veuillez recharger la page, pour tenter de r\u00e9soudre le probl\u00e8me.";
KD.valid={text:"Recharger",actionType:"reload",action:null};KD.abort=null;KD.extralink=null;KD.isrestrictive=true;KD.background="transparent-white";KD.execute();break;case 404:break;case 500:break;default:break}}
function Kxlib_Dialog(){this.title;this.message;this.valid={};Object.defineProperty(this.valid,"text",{enumerable:true,configurable:true,writable:true,value:null});Object.defineProperty(this.valid,"actionType",{enumerable:true,configurable:true,writable:true,value:null});Object.defineProperty(this.valid,"action",{enumerable:true,configurable:true,writable:true,value:null});this.abort={};Object.defineProperty(this.abort,"text",{enumerable:true,configurable:true,writable:true,value:null});Object.defineProperty(this.abort,
"actionType",{enumerable:true,configurable:true,writable:true,value:null});Object.defineProperty(this.abort,"action",{enumerable:true,configurable:true,writable:true,value:null});this.extralink={};Object.defineProperty(this.extralink,"text",{enumerable:true,configurable:true,writable:true,value:null});Object.defineProperty(this.extralink,"action",{enumerable:true,configurable:true,writable:true,value:null});this.isrestrictive;this.background;this.uniquemode=true;var th=this;try{var _f_Gdf=function(){var ds=
{actionType:/^(?:link|classbind|close|reload|home)$/i,isrestrictive:[false,true]};return ds};th.execute=function(){if(th.uniquemode===true&&_f_Opened())return;var cr=_f_Controls();if(cr!==true)return cr;_f_Prepare();_f_ShwDialg()};th.test=function(){th.title="Mon super titre";th.message="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla pulvinar semper luctus. Pellentesque justo felis, placerat sed lacus non, tempus maximus lacus. Morbi at libero sit amet justo cras amet.";th.valid={text:null,
actionType:"link",action:"/help"};th.abort={text:null,actionType:"close",action:null};th.extralink={text:"Leatn more",action:"/help"};th.isrestrictive=true;th.background="transparent-lightwhite";th.execute()};var _f_Opened=function(){return $(".jb-kldlg-sprt").length&&!$(".jb-kldlg-sprt").hasClass("this_hide")?true:false};var _f_Controls=function(){var err=[];if(!th.message)err.push("message");var atsa=["close","reload","home"];if(!KgbLib_CheckNullity(th.valid)&&!th.valid.actionType|(th.valid.actionType&&
!_f_Gdf().actionType.test(th.valid.actionType))|($.inArray(th.valid.actionType,atsa)===-1&&!th.valid.action))err.push("valid");if(!KgbLib_CheckNullity(th.abort)&&!th.abort.actionType|(th.abort.actionType&&!_f_Gdf().actionType.test(th.abort.actionType))|($.inArray(th.valid.actionType,atsa)===-1&&!th.valid.action))err.push("abort");if(!KgbLib_CheckNullity(th.extralink)&&!th.extralink.action)err.push("extralink");return err.length?err:true};var _f_Prepare=function(){var h;if(!KgbLib_CheckNullity(th.title)&&
!(!KgbLib_CheckNullity(th.valid)|!KgbLib_CheckNullity(th.abort)|!KgbLib_CheckNullity(th.extralink))){$(".jb-kldlg-bdy-ftr").remove();h=180}else if(KgbLib_CheckNullity(th.title)&&!KgbLib_CheckNullity(th.valid)|!KgbLib_CheckNullity(th.abort)|!KgbLib_CheckNullity(th.extralink)){$(".jb-kldlg-bdy-hdr").remove();h=170}else if(KgbLib_CheckNullity(th.title)&&!(!KgbLib_CheckNullity(th.valid)|!KgbLib_CheckNullity(th.abort)|!KgbLib_CheckNullity(th.extralink))){$(".jb-kldlg-bdy-ftr").remove();$(".jb-kldlg-bdy-hdr").remove();
h=135}if(th.message.length<205){$(".jb-kldlg-bdy-bdy").height(50);h=h?h-50:$(".jb-kldlg-bdy").height()-50;$(".jb-kldlg-bdy").height(h)}else $(".jb-kldlg-bdy").height(h);if(th.title)$(".jb-kldlg-tle").html(th.title);$(".jb-kldlg-bdy-m").html(th.message);if(th.valid&&$(".jb-kldlg-action[data-action=valid]").length){if(th.valid.text)$(".jb-kldlg-action[data-action=valid]").text(th.valid.text);if(th.valid.actionType==="link")$(".jb-kldlg-action[data-action=valid]").attr("href",th.valid.action);else if(th.valid.actionType===
"classbind")$(".jb-kldlg-action[data-action=valid]").addClass(th.valid.action);else if(th.valid.actionType==="close")$(".jb-kldlg-action[data-action=valid]").click(function(e){Kxlib_PreventDefault(e);$(".jb-kldlg-sprt").addClass("this_hide")});else if(th.valid.actionType==="reload")$(".jb-kldlg-action[data-action=valid]").addClass("jb-rld");else if(th.valid.actionType==="home")$(".jb-kldlg-action[data-action=valid]").click(function(e){Kxlib_PreventDefault(e);window.location.href="/"})}else if(th.valid&&
!$(".jb-kldlg-action[data-action=valid]").length)$(".jb-kldlg-bdy-ftr").remove();else $(".jb-kldlg-action[data-action=valid]").remove();if(th.abort&&$(".jb-kldlg-action[data-action=abort]").length){if(th.abort.text)$(".jb-kldlg-action[data-action=abort]").text(th.abort.text);if(th.abort.actionType==="link")$(".jb-kldlg-action[data-action=abort]").attr("href",th.abort.action);else if(th.abort.actionType==="classbind")$(".jb-kldlg-action[data-action=abort]").addClass(th.abort.action);else if(th.abort.actionType===
"close")$(".jb-kldlg-action[data-action=abort]").click(function(e){Kxlib_PreventDefault(e);$(".jb-kldlg-sprt").addClass("this_hide")});else if(th.abort.actionType==="reload")$(".jb-kldlg-action[data-action=abort]").addClass("jb-rld");else if(th.abort.actionType==="home")$(".jb-kldlg-action[data-action=abort]").click(function(e){Kxlib_PreventDefault(e);window.location.href="/"})}else if(th.abort&&!$(".jb-kldlg-action[data-action=abort]").length)$(".jb-kldlg-bdy-ftr").remove();else $(".jb-kldlg-action[data-action=abort]").remove();
if(th.extralink&&$(".jb-kldlg-lm").length){if(th.extralink.text)$(".jb-kldlg-lm").html(th.extralink.text);$(".jb-kldlg-lm").attr("href",th.extralink.action)}else $(".jb-kldlg-lm").remove();if(th.isrestrictive)$(".jb-kldlg-fmr").remove();if(th.background){switch(th.background.toLowerCase()){case "transparent-lightwhite":th.background="rgba(255,255,255,0.4)";break;case "transparent-white":th.background="rgba(255,255,255,0.8)";break;case "transparent-lightblack":th.background="rgba(0,0,0,0.4)";break;
case "transparent-black":th.background="rgba(0,0,0,0.8)";break;default:break}$(".jb-kldlg-sprt").css({"background-color":th.background})}return true};var _f_ShwDialg=function(){$(".jb-kldlg-sprt").removeClass("this_hide")};var _f_HdDialg=function(){$(".jb-kldlg-sprt").addClass("this_hide")}}catch(ex){}}function Kxlib_Decode_After_Encode(s){if(KgbLib_CheckNullity(s))return;var ns=$("<div/>").html(s).text();return ns}
function Kxlib_GetExtFileURL(c,p,opt){if(!(!KgbLib_CheckNullity(c)&&typeof c==="string")|!(!KgbLib_CheckNullity(p)&&typeof p==="string"))return;if(p.charAt(0)==="/")p=p.substring(1);var u;switch(c.toLowerCase()){case "sys_url_aud":u=ENV_VARS("SYS_URL_AUD_PATH");if(!u)return;u=u+p;if(!KgbLib_CheckNullity(opt)&&$.inArray("_WITH_ROOTABS_OPTION",opt)!==-1)u=ENV_VARS("SYS_URL_AUD_ROOTABS")+u;break;case "sys_url_img":u=ENV_VARS("SYS_URL_IMG_PATH");if(!u)return;u=u+p;if(!KgbLib_CheckNullity(opt)&&$.inArray("_WITH_ROOTABS_OPTION",
opt)!==-1)u=ENV_VARS("SYS_URL_IMG_ROOTABS")+u;break;case "sys_url_script":u=ENV_VARS("SYS_URL_SCRIPT_PATH");if(!u)return;u=u+p;break;case "sys_url_style":u=ENV_VARS("SYS_URL_STYLE_PATH");if(!u)return;u=u+p;break;default:return}return u}function Kxlib_PreventDefault(e){if(KgbLib_CheckNullity(e))return;try{if(e.preventDefault)e.preventDefault();else e.returnValue=false}catch(e){}}
function Kxlib_StopPropagation(e){if(KgbLib_CheckNullity(e))return;try{if(e.stopPropagation)e.stopPropagation();else{window.event.cancelBubble=true;e.cancelBubble=true;return}}catch(e){}}
function Kxlib_UsertagFactory(s,p,c){if(KgbLib_CheckNullity(s)|typeof s!=="string"|KgbLib_CheckNullity(p)|!$.isArray(p)|KgbLib_CheckNullity(c)|typeof c!=="string")return;var ns__=s;$.each(p,function(x,v){ns__=ns__.replace(new RegExp("@"+v+"","gi"),"<a class='"+c+"' href='/"+v.toLowerCase()+"'>@"+v+"</a>")});return ns__}
function Kxlib_SplitByUsertags(s){if(KgbLib_CheckNullity(s)|typeof s!=="string")return;var r,match,uts=[];var ptrn=/(<a class='(?:tqr-unq-user|tqr-arp-user)' href='\/\@?[\w]+'>(\@[\w]+)<\/a>)/g;var uts=s.match();while(match=ptrn.exec(s))uts.push([match[1],match[2]]);if(uts){var pcs=[];ts__=s;$.each(uts,function(x,e){if(typeof e==="object"&&e.length===2&&s!==undefined){var p__=ts__.split(new RegExp(e[0].toString()));pcs.push(p__[0]);pcs.push(e);z__=p__[0].toString()+e[0].toString();ts__=ts__.replace(z__,
"");s=p__[1]}});pcs.push(s);r=pcs;r=[];var $tst=$("<div/>");$.each(pcs,function(x,e){if($.isArray(e)){var $a__=$("<a/>",{"class":"tqr-unq-user","href":"/"+e[1].toString().toLowerCase()}).text(e[1].toString());$tst.append($a__)}else if(typeof e==="string"&&e){var sp__=$("<span/>").text(e);$tst.append(sp__)}});r=$tst}else r=s;return $tst}
function Kxlib_ActivateURLIC(t,us){try{if(KgbLib_CheckNullity(t)|KgbLib_CheckNullity(us))return;var tx=Kxlib_Decode_After_Encode(t);var aldy=spltr=[];$.each(us,function(x,utb){if(aldy&&$.inArray(utb.uic_url,aldy)!==-1)return true;var hrf=/^https?:\/\//i.test(utb.uic_url)?utb.uic_url:"http://"+utb.uic_url;var a=$("<a/>",{"data-ds":JSON.stringify(utb),"data-item":utb.uicid,"target":"_blank","href":hrf,"class":"tqr-uic-a jb-tqr-uic-a"}).data("ds",JSON.stringify(utb)).text(utb.uic_url);var atx=$("<div/>").append($(a).clone()).html();
var re;if(/^www./i.test(utb.uic_url)||/^https?:\/\//i.test(utb.uic_url)){re=new RegExp(utb.uic_url,"g");tx=tx.replace(re,atx)}else{re=new RegExp("(?:((?:(?:\\s|^$)|(?:[^a-z\\/]{2,}))\\.?)("+utb.uic_url+"\\/?)(?!(?:[a-z\\d])|(?:\\/[^\\s])))|(?:^("+utb.uic_url+"\\/?)(?!(?:[a-z\\d])|(?:\\/[^\\s])))","gi");tx=tx.replace(re,function(a,b,c,d){return b?b+atx:atx})}aldy.push(utb);spltr.push(atx)});return tx}catch(ex){}}
function Kxlib_GetFirstDomSortedByTimeBy(gsl,prop,caz){if(KgbLib_CheckNullity(gsl)|KgbLib_CheckNullity(prop)|KgbLib_CheckNullity(caz))return;if(!$(gsl).length)return false;if(!$(gsl).filter("["+prop+"]").length)return false;if($.inArray(caz.toUpperCase(),["FIRST","LAST"])===-1)return false;var srt_lst=[];$.each($(gsl).filter("["+prop+"]"),function(x,e){if(typeof parseInt($(e).attr(prop))==="number"){srt_lst.push([e,parseInt($(e).attr(prop))]);srt_lst.sort(function(a,b){return a[1]-b[1]})}});if(KgbLib_CheckNullity(srt_lst))return-1;
else if(caz.toUpperCase()==="LAST")return srt_lst[0][0];else{var ln__=srt_lst.length;return srt_lst[--ln__][0]}}function Kxlib_FstLetterCap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function Kxlib_SetDataWith(ustgs){try{if(KgbLib_CheckNullity(ustgs))return;var str__;if(!KgbLib_CheckNullity(ustgs)&&ustgs!==undefined&&typeof ustgs==="object"){var istgs__=[];$.each(ustgs,function(x,v){var rw__=[];$.map(v,function(e,x){rw__.push(e)});istgs__.push(rw__.join("','"))});str__=istgs__.length>1?istgs__.join("'],['"):istgs__[0];str__="['"+str__+"']"}return str__}catch(ex){Kxlib_DebugVars([ex])}}
function Kxlib_TextEmpow(t,us,ht,ul,opts){try{if(KgbLib_CheckNullity(t))return;var emt="",nt,us_cz;nt=$("<div/>").text(t).html();if(!KgbLib_CheckNullity(us)){us_cz=true;var str__=Kxlib_SetDataWith(us);var ustgs=Kxlib_DataCacheToArray(str__)[0];var ps=ustgs&&$.isArray(ustgs[0])?Kxlib_GetColumn(3,ustgs):[ustgs[3]];var us_str=Kxlib_UsertagFactory(t,ps,"tqr-unq-user");us_str=Kxlib_SplitByUsertags(us_str);emt=$("<div/>").html(us_str)}if(!KgbLib_CheckNullity(ht)){nt=emt?$(emt).html():nt;$.each(ht,function(x,
h){var c="tqr-unq-user";nt=nt.replace(new RegExp("#"+h+"(?![a-zd])","gi"),"<a class='"+c+"' href='/hview/q="+h.toLowerCase()+"&src=hash'>#"+h+"</a>")});emt=$("<div/>").html(nt)}if(opts&&opts.hasOwnProperty("ena_inner_link")&&!KgbLib_CheckNullity(opts.ena_inner_link.all)&&opts.ena_inner_link.all===true);else if(opts&&opts.hasOwnProperty("ena_inner_link")&&!KgbLib_CheckNullity(opts.ena_inner_link.only)&&opts.ena_inner_link.only==="fksa"){nt=emt?$(emt).html():nt;var uls=!KgbLib_CheckNullity(opts.ena_inner_link.local)&&
opts.ena_inner_link.local===true?nt.match(/(?:https?:\/\/)?127.0.0.1\/f(?:(?:\/sts)|(?:\/vid))?\/[\w\-_]{5,50}/gi):nt.match(/(?:https?:\/\/)?(?:(?:www\.)|(?:beta\.)|(?:dm1606\.))?trenqr\.com\/f(?:(?:\/sts)|(?:\/vid))?\/[\w\-_]{5,50}/gi);if(uls){var aldy=[];$.each(uls,function(x,ul){if(aldy&&$.inArray(ul,aldy)!==-1)return true;aldy.push(ul);var hrf=(new RegExp("^https?://","gi")).test(ul)?ul:"http://".concat(ul);var rgx="^("+ul+")|[^(?:https?://)|(?:www.)|(?:a-zd)|(?:href=')]("+ul+")";nt=nt.replace(new RegExp(rgx,
"gi"),function(a,b){return a===b?"<a class='tqr-inner-link' href='"+hrf+"'>"+ul+"</a>":a.substring(0,1)+"<a class='tqr-inner-link' href='"+hrf+"'>"+ul+"</a>"})});emt=$("<div/>").html(nt)}}var t__=emt?$("<div/>").html(emt).html():nt;emt=Kxlib_ParseEmoji(t__,opts);emt=!emt?$("<div/>").text(nt).text():emt;emt=typeof emt==="string"&&opts&&opts.hasOwnProperty("wrap_text")&&opts.wrap_text===true?$("<div/>").html(emt):emt;return emt}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}}
function Kxlib_ParseEmoji(t,opts){try{if(KgbLib_CheckNullity(t))return;var t__=twemoji.parse(t,{callback:function(icon,options){return"//twemoji.maxcdn.com/"+options.size+"/"+icon+".png"},size:opts&&opts.hasOwnProperty("emoji")&&opts.emoji.hasOwnProperty("size")&&opts.emoji.size&&$.inArray(parseInt(opts.emoji.size),[16,36,72,128])?opts.emoji.size:16});var pos_x=opts&&opts.hasOwnProperty("emoji")&&opts.emoji.hasOwnProperty("position_x")&&opts.emoji.position_x?opts.emoji.position_x.toString().concat("px"):
"auto";var pos_y=opts&&opts.hasOwnProperty("emoji")&&opts.emoji.hasOwnProperty("position_y")&&opts.emoji.position_y?opts.emoji.position_y.toString().concat("px"):"auto";var r=t__;if(opts&&opts.hasOwnProperty("emoji")&&opts.emoji.hasOwnProperty("size_css")&&opts.emoji.size_css)if(typeof r==="string"){r=$("<div/>").html(r);$(r).find(".emoji").css({height:opts.emoji.size_css.toString().concat("px"),position:"relative",top:pos_y,left:pos_x});r=$(r).html()}else $(r).find(".emoji").css({height:opts.emoji.size_css.toString().concat("px"),
position:"relative",top:pos_y,left:pos_x});return r}catch(ex){Kxlib_DebugVars([ex])}}function Kxlib_WindOverflow(hid){try{if(hid)$("html").css("overflow","hidden");else $("html").css("overflow","auto")}catch(ex){Kxlib_DebugVars([ex])}}
function Kxlib_RemTime(fut,now){try{if(KgbLib_CheckNullity(fut)|KgbLib_CheckNullity(now))return;if(now>fut)return;var delta=Math.abs(fut-now)/1E3;var days=Math.floor(delta/86400);delta-=days*86400;var hours=Math.floor(delta/3600)%24;delta-=hours*3600;var minutes=Math.floor(delta/60)%60;delta-=minutes*60;var seconds=delta%60;return{h:hours,m:minutes,s:seconds}}catch(ex){Kxlib_DebugVars([ex])}}
function Kxlib_ExtractDomain(url){if(KgbLib_CheckNullity(url))return;var domain;domain=url.indexOf("://")>-1?url.split("/")[2]:url.split("/")[0];domain=domain.split(":")[0];return domain}function Kxlib_GetAbsolutePathFromUrl(url){if(KgbLib_CheckNullity(url))return;domain=Kxlib_ExtractDomain(url);var path=url.split(domain)[1];return path}
function Kxlib_DocTitleSwNb(cn){var cur_tle=document.title;var pcs=cur_tle.match(/^(?:\(\d+\)\s)?(.+)$/i);if(!(pcs&&$.isArray(pcs))){alert("No tab");return}var ntle;if(KgbLib_CheckNullity(cn))ntle=pcs[1].indexOf("(")===0?pcs[2]:pcs[1];else ntle=document.title=pcs[1].indexOf("(")===0?"".concat("(",cn,") ",pcs[2]):"".concat("(",cn,") ",pcs[1]);document.title=ntle;return ntle}var loce=new Array;loce.push(["noanswer","Signale que le seveur n'a renvoy\u00e9 aucune donn\u00e9e."]);
loce.push(["datasmissing","Signale que le serveur a r\u00e9pondu mais n'a renvoy\u00e9 la donn\u00e9e attendue."]);loce.push(["datasready","Signale que les donn\u00e9es ont \u00e9t\u00e9 recues."]);loce.push(["formcleared","Signale que le formulaire a \u00e9t\u00e9 n\u00e9ttoy\u00e9."]);loce.push(["operended","Signale au receveur que l'op\u00e9ration en cours est termin\u00e9e."]);loce.push(["knwerror","Signale au receveur que l'op\u00e9ration a \u00e9chou\u00e9. Cependant, il s'agit d'un cas repertori\u00e9. Aussi, un code erreur est fourni."]);
loce.push(["unknwerr","Signale \u00e0 l'envoyeur que l'op\u00e9ration a \u00e9chou\u00e9 suite \u00e0 une erreur inattendue."]);loce.push(["success","Signale au receveur que l'op\u00e9ration est un succes."]);
