function MNFM(){var gt=this;var _cmft_bddvc;var _cmft_bdscrn;var _cmft_bdbrwz;var _f_Gdf=function(){var dt={"_CMFY_SCRN_MIN":{h:610,w:1345},"_CMFY_NVGTR_LIST":["OPERA","CHROME","SAFARI","FIREFOX","MSIE"],"_CMFY_NVGTR_VER_MIN":{"OPERA":"NaI","CHROME":"NaI","SAFARI":6,"FIREFOX":"NaI","MSIE":10},"_CMFY_NVGTR_UPGRD":{"OPERA":"http://www.opera.com/","CHROME":"http://www.google.com/chrome","SAFARI":"http://www.apple.com/safari/","FIREFOX":"http://www.firefox.com/","MSIE":"http://windows.microsoft.com/ie"}};
return dt};var _f_Init=function(){try{}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};this.SetPrfrcs=function(opi,dci,s,rap,x){try{if(KgbLib_CheckNullity(opi)|KgbLib_CheckNullity(dci))return;rap=KgbLib_CheckNullity(rap)?false:rap;if(KgbLib_CheckNullity(s))s=$("<span/>");var ap=_f_Srv_SetPrfrcs(opi,dci,s);if(KgbLib_CheckNullity(s)&&rap===true)return[s,ap];else if(KgbLib_CheckNullity(s)&&rap===false)return[s,null];else if(!KgbLib_CheckNullity(s)&&rap===true)return[null,ap];else return true}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};var _f_SetPrfrcs_Betver=function(x){try{if(KgbLib_CheckNullity(x))return;if($(x).data("lk")===1)return;$(x).data("lk",1);$(".jb-tqr-wrng-betver-mx").addClass("this_hide");var s=$("<span/>");gt.SetPrfrcs("_PFOP_TIABT_INR","_DEC_DSMA",s);$(s).on("operended",function(e,d){var Nty=new Notifyzing;Nty.FromUserAction("TQR_WLCM_BETA")})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CmfrtAct=function(x){try{if(KgbLib_CheckNullity(x)|$(x).data("action"))return;
var a=$(x).data("action");switch(a.toLowerCase()){case "close":_f_Cmfrt_Bbx(false);break;case "close-with-caution":if($(".jb-tqr-mnfm-btm-infbx-opt-chkbx")&&$(".jb-tqr-mnfm-btm-infbx-opt-chkbx").length&&$(".jb-tqr-mnfm-btm-infbx-opt-chkbx").is(":checked")){var jct=$(".jb-tqr-mnfm-btm-infbx-bmx").data("jct");if(!KgbLib_CheckNullity(jct))_f_CmfrtSvLclDc(jct)}_f_Cmfrt_Bbx(false);break}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CmfrtSvLclDc=function(j){try{if(KgbLib_CheckNullity(j))retrun;
j=j.toUpperCase();switch(j){case "DVC":jct="TQRCMFRT_DVC";break;case "SCN":jct="TQRCMFRT_SCN";break;case "NGT":jct="TQRCMFRT_NGT";break;default:return}if(docCookies.hasItem(jct))return;docCookies.setItem(jct,"DSMA",Infinity)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CmfrtDevice=function(){try{if(Kxlib_NvgtrIsMobile()){_cmft_bddvc=true;if(docCookies.hasItem("TQRCMFRT_DVC")&&docCookies.getItem("TQRCMFRT_DVC").toUpperCase()==="DSMA"){_cmft_bddvc=false;return}if(Kxlib_NvgtrIsMobile())var pup=
Kxlib_getDolphinsValue("TQR_CMFRT_DVC_PUP");_f_Cmfrt_Bbx("TQR_CMFRT_DVC_BBX",true)}else _cmft_bddvc=false}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CmfrtScreen=function(){try{if(screen&&(screen.height<_f_Gdf()._CMFY_SCRN_MIN.h|screen.width<_f_Gdf()._CMFY_SCRN_MIN.w&&_cmft_bddvc===false)){_cmft_bdscrn=true;if(docCookies.hasItem("TQRCMFRT_SCN")&&docCookies.getItem("TQRCMFRT_SCN").toUpperCase()==="DSMA"){_cmft_bdscrn=false;return}if(Kxlib_NvgtrIsMobile())var pup=Kxlib_getDolphinsValue("TQR_CMFRT_SCN_PUP");
_f_Cmfrt_Bbx("TQR_CMFRT_SCN_BBX",true)}else _cmft_bdscrn=false}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CmfrtBrowzer=function(){try{var ds=Kxlib_NvgtrSayWho();if(!KgbLib_CheckNullity(ds)&&(ds.hasOwnProperty("name")&&!KgbLib_CheckNullity(ds.name))&&(ds.hasOwnProperty("version")&&!KgbLib_CheckNullity(ds.version))&&_cmft_bddvc===false&&_cmft_bdscrn===false){_cmft_bdbrwz=true;if(docCookies.hasItem("TQRCMFRT_NGT")&&docCookies.getItem("TQRCMFRT_NGT").toUpperCase()==="DSMA"){_cmft_bdbrwz=
false;return}var nm=ds.name.toUpperCase();var vr=parseInt(ds.version);if($.inArray(nm,_f_Gdf()._CMFY_NVGTR_LIST)===-1)return;var vr_min=typeof _f_Gdf()._CMFY_NVGTR_VER_MIN[nm]==="number"?parseInt(_f_Gdf()._CMFY_NVGTR_VER_MIN[nm]):_f_Gdf()._CMFY_NVGTR_VER_MIN[nm];if(vr_min!=="NaI"&&vr<vr_min){if(Kxlib_NvgtrIsMobile())var pup=Kxlib_getDolphinsValue("TQR_CMFRT_NGT_PUP");_f_Cmfrt_Bbx("TQR_CMFRT_NGT_BBX",true)}}else _cmft_bdbrwz=false}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};setTimeout(function(){_f_CmfrtDevice()},
1100);setTimeout(function(){_f_CmfrtScreen()},2E3);setTimeout(function(){_f_CmfrtBrowzer()},3E3);var _Ax_SetPrfrcs=Kxlib_GetAjaxRules("TQREX_STPRFRCS");var _f_Srv_SetPrfrcs=function(opi,dci,s){if(KgbLib_CheckNullity(opi)|KgbLib_CheckNullity(dci)|KgbLib_CheckNullity(s))return;var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_OWNER_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();
break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":$(s).trigger("err",["EXPTDERR",d.err]);break;case "__ERR_VOL_FAILED":$(s).trigger("err",["EXPTDERR",d.err]);break;case "__ERR_VOL_DATAS_MSG":Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");break;case "__ERR_VOL_WRG_DATAS":$(s).trigger("err",["EXPTDERR",d.err]);break;case "__ERR_VOL_WRG_HACK":$(s).trigger("err",["EXPTDERR",d.err]);break;default:break}return}else if(!KgbLib_CheckNullity(d.return))$(s).trigger("operended");else{$(s).trigger("err",
["VOID"]);return}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true);$(s).trigger("err",["UEXPTDERR",ex]);return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return};var u=document.URL;var toSend={"urqid":_Ax_SetPrfrcs.urqid,"datas":{"opi":opi,"dci":dci,"u":u}};var ap__=Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_SetPrfrcs.url,wcrdtl:_Ax_SetPrfrcs.wcrdtl});return ap__};var _f_Cmfrt_Bbx=function(i,sh){try{if((!KgbLib_CheckNullity(sh)&&
sh===true&&KgbLib_CheckNullity(i))|!$(".jb-tqr-mnfm-btm-infbx-bmx").length)return;var scnh=screen.height;if(sh){var jct;switch(i){case "TQR_CMFRT_DVC_BBX":jct="DVC";break;case "TQR_CMFRT_SCN_BBX":jct="SCN";break;case "TQR_CMFRT_NGT_BBX":jct="NGT";break;default:return}$(".jb-tqr-mnfm-btm-infbx-bmx").data("jct",jct);var bbx=Kxlib_getDolphinsValue(i);if(!bbx)return;if(i==="TQR_CMFRT_NGT_BBX"){var $t__=$("<div/>").html(bbx);var n__=Kxlib_NvgtrSayWho().name.toUpperCase();if($.inArray(n__,_f_Gdf()._CMFY_NVGTR_LIST)===
-1)$t__.find(".go-update").remove();else $t__.find(".go-update").attr("href",_f_Gdf()._CMFY_NVGTR_UPGRD[n__]);bbx=$t__.html()}if(!$(".jb-tqr-mnfm-btm-infbx-bmx").hasClass("this_hide")){var b__=scnh*-1;$(".jb-tqr-mnfm-btm-infbx-bmx").stop(true,true).animate({bottom:b__+"px"},1E3,function(){$(this).addClass("this_hide").removeAttr("style");$(".jb-tqr-mnfm-btm-infbx-msg").html(bbx);$(".jb-tqr-mnfm-btm-infbx-bmx").hide().removeClass("this_hide").fadeIn()})}else{$(".jb-tqr-mnfm-btm-infbx-msg").html(bbx);
$(".jb-tqr-mnfm-btm-infbx-bmx").hide().removeClass("this_hide").fadeIn()}}else{var b__=scnh*-1;$(".jb-tqr-mnfm-btm-infbx-bmx").stop(true,true).animate({bottom:b__+"px"},1E3,function(){$(this).addClass("this_hide").removeAttr("style");$(".jb-tqr-mnfm-btm-infbx-msg").html("")})}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};$(".jb-tqr-wrng-betver-done").click(function(e){Kxlib_PreventDefault(e);_f_SetPrfrcs_Betver(this)});$(".jb-tqr-mnfm-btm-infbx-clz, .jb-tqr-mnfm-btm-infbx-dec-tgr").click(function(e){Kxlib_PreventDefault(e);
_f_CmfrtAct(this)});_f_Init()}new MNFM;
