function Resizing(){var _mxCtrW=1062;var _minCvrW=760;this.minTrCoverW=758;var _maxCvrW=840;var _cvrStdH=260;var _f_RszAccHdr=function(){var ccW=$(".jb-p-l-c-main").width();var ccvrW=$(".jb-acc-hdr").width();var ccvlm=$(".jb-acc-hdr").css("margin-right");ccvlm=parseInt(ccvlm.replace("px",""));if(ccW<_mxCtrW&&ccvrW===_maxCvrW&&ccvlm<50){var $img=new Image;var $th=this;$img.src=$(".jb-a-h-t-top-img").attr("src");var _img_top=$(".jb-a-h-t-top-img").css("top");$img.onload=function(){};setTimeout(function(){$(".jb-acc-spec-loc").stop(true,
true).addClass("loc_go_thi",700);$(".jb-acc-hdr, .jb-acc-hdr-top, .jb-a-h-t-top, .jb-a-h-t-top-img-mx, .jb-a-h-t-top-fade, .jb-acc-hdr-down").stop(true,true).animate({width:_minCvrW},700);if(_cvrStdH!==$img.height){var oo=new Cropper;$img=oo.Cropper_resizeWidthKeepHeightProrata($img,_minCvrW);$(".jb-a-h-t-top-img").stop(true,true).animate({top:_img_top,width:$img.width,height:$img.height},700)}},2E3)}else{var $img=new Image;var $th=this;$img.src=$(".jb-a-h-t-top-img").attr("src");$img.onload=function(){};
setTimeout(function(){$(".jb-acc-spec-loc").stop(true,true).removeClass("loc_go_thi",700);$(".jb-acc-hdr, .jb-acc-hdr-top, .jb-a-h-t-top, .jb-a-h-t-top-img-mx, .jb-a-h-t-top-fade, .jb-acc-hdr-down").stop(true,true).animate({width:_maxCvrW},700);if(_maxCvrW!==$img.width){var oo=new Cropper;$img=oo.Cropper_resizeWidthKeepHeightProrata($img,_maxCvrW);$(".jb-a-h-t-top-img").stop(true,true).animate({width:$img.width,height:$img.height},700)}},2E3)}};this.ResizeTrHeader=function(){var curCenterW=$(".jb-p-l-c-main").css("width");
curCenterW=parseInt(curCenterW.replace("px",""));var curCoverW=$("#tr-header").css("width");curCoverW=parseInt(curCoverW.replace("px",""));var ccvlm=$("#tr-header").css("margin-right");ccvlm=parseInt(ccvlm.replace("px",""));if(curCenterW<_mxCtrW&&curCoverW===_maxCvrW&&ccvlm<50){var $img=new Image;var $th=this;$img.src=$("#a-h-t-top-tr-img-max img").attr("src");$img.onload=function(){};setTimeout(function(){$("#tr-header").addClass("resz_gothiner_bloc",700);$("#tr-header-top").addClass("resz_gothiner_w",
700);$("#a-h-t-top-tr").addClass("resz_gothiner_w",700);$("#a-h-t-top-img-max").addClass("resz_gothiner_w",700);$("#a-h-t-top-tr-title").addClass("tr-title-go-thi",700);$("#a-h-t-top-tr-desc").addClass("tr-desc-go-thi",700);$(".tr-h-t-d-4").addClass("access_thi",700);$("#tr-h-t-down").addClass("resz_gothiner_w",700);if(_cvrStdH!==$img.height){var oo=new Cropper;var wi=_minCvrW;$img=oo.Cropper_resizeWidthKeepHeightProrata($img,wi);var $img=$(img).attr("id","a-h-t-top-img");$("#a-h-t-top-tr-img-max img").replaceWith($img)}},
2E3)}else{var $img=new Image;var $th=this;$img.src=$("#a-h-t-top-tr-img-max img").attr("src");$img.onload=function(){};setTimeout(function(){$("#tr-header").removeClass("resz_gothiner_bloc",700);$("#tr-header-top").removeClass("resz_gothiner_w",700);$("#a-h-t-top-tr").removeClass("resz_gothiner_w",700);$("#a-h-t-top-img-max").removeClass("resz_gothiner_w",700);$("#a-h-t-top-tr-title").removeClass("tr-title-go-thi",700);$("#a-h-t-top-tr-desc").removeClass("tr-desc-go-thi",700);$(".tr-h-t-d-4").removeClass("access_thi",
700);$("#tr-h-t-down").removeClass("resz_gothiner_w",700);if(_maxCvrW!==$img.width){var oo=new Cropper;var wi=_maxCvrW;$img=oo.Cropper_resizeWidthKeepHeightProrata($img,wi);var $img=$(img).attr("id","a-h-t-top-tr-img-img");$("#a-h-t-top-tr-img-max img").replaceWith($img)}},2E3)}};this.ResizeTrHeaderHigher=function(){$("#a-h-t-top-tr").stop(true,true).switchClass("resz-tr-hdr-smlr","resz-tr-hdr-hir",800,"easeOutSine")};this.ResizeTrHeaderSmaller=function(){$("#a-h-t-top-tr").stop(true,true).switchClass("resz-tr-hdr-hir",
"resz-tr-hdr-smlr",800,"easeOutSine")};this.Init=function(){var $p=$("#rez-pg");if(!$p.length||KgbLib_CheckNullity($p.data("pg")))return;var p=$p.data("pg");switch(p.toUpperCase()){case "TMLNR":_f_RszAccHdr();break;case "TRPG":this.ResizeTrHeader();break;default:return;break}}}
(function(){var _obj=new Resizing;$("#tr-h-an-hi").click(function(e){Kxlib_PreventDefault(e);_obj.ResizeTrHeaderHigher();if(!$(e.target).hasClass("tr-hdr-an-full")){$(e.target).stop(true,true).toggleClass("tr-hdr-an-full");$("#tr-h-an-sm").stop(true,true).toggleClass("tr-hdr-an-full")}});$("#tr-h-an-sm").click(function(e){Kxlib_PreventDefault(e);_obj.ResizeTrHeaderSmaller();if(!$(e.target).hasClass("tr-hdr-an-full")){$(e.target).stop(true,true).toggleClass("tr-hdr-an-full");$("#tr-h-an-hi").stop(true,
true).toggleClass("tr-hdr-an-full")}})})();
