var regSafe=/^[^:;="']{1,}$/;var regMail=/^[a-zA-Z0-9-_]{1,15}([.][a-zA-Z0-9-_]{1,15})*@[a-zA-Z0-9-_]{1,15}([.][a-zA-Z0-9-_]{1,15})*([.][A-Za-z0-9]{2,4})+$/;var regNickname=/^[a-zA-Z0-9-\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00c7\u00e7\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00ff\u00d1\u00f1]{2,20}$/;
function sidebarPos(){var contentOffset=$("#cnx_form_wrapper").offset().top;var sidebarOffset=contentOffset-113;$("#cnx_sidebar").css("margin-top",sidebarOffset+"px")}function cnxErrorBox(){if($("#cnx_form_error").html()==="");else;}$(document).ready(function(){sidebarPos();$("#cnx_form_login_input").focus()});function cnxErrorMsg(msg){$("#cnx_msg > p").html(msg);$("#cnx_msg").css("border-color","#ddd");$("#cnx_msg").css("background-color","#eee")}
function cnxLockCheck(){var lockTable=$(".cnx_input");var errorArray=new Array;$.each(lockTable,function(h,i){if($(i).data("su")==="lock")errorArray.push(i)});var errorCount=errorArray.length;if(errorCount>1){var msg=Kxlib_getDolphinsValue("p_err_cnx_multifield");cnxErrorMsg(msg);cnxErrorBox()}else if(errorCount===0){msg=Kxlib_getDolphinsValue("p_cnx_default");cnxErrorMsg(msg);cnxErrorBox()}else if(errorCount===1){var arg=errorArray[0];var argSelector=$(arg).attr("id");switch(argSelector){case "cnx_form_login_input":var msg=
Kxlib_getDolphinsValue("p_err_cnx_badlogin");cnxErrorMsg(msg);break;case "cnx_form_passwd_input":var msg=Kxlib_getDolphinsValue("p_err_cnx_pwbadchars");cnxErrorMsg(msg);break}cnxErrorBox()}}
function cnx_login_check(input){if(!regMail.test(input))if(!regNickname.test(input)){$("#cnx_form_login_input").addClass("error_border");$("#cnx_form_login_input").data("su","lock");cnxLockCheck()}else{$("#cnx_form_login_input").removeClass("error_border");$("#cnx_form_login_input").data("su","ulock");cnxLockCheck()}else{$("#cnx_form_login_input").removeClass("error_border");$("#cnx_form_login_input").data("su","ulock");cnxLockCheck()}}
function cnx_passwd_check(input){if(!regSafe.test(input)){$("#cnx_form_passwd_input").addClass("error_border");$("#cnx_form_passwd_input").data("su","lock");cnxLockCheck()}else{$("#cnx_form_passwd_input").removeClass("error_border");$("#cnx_form_passwd_input").data("su","ulock");cnxLockCheck()}}
function cnx_birthday_check(){if($("#cnx_day").val()==="init"&&$("#cnx_month").val()==="init"&&$("#cnx_year").val()==="init"){$("#cnx_day").removeClass("error_border");$("#cnx_month").removeClass("error_border");$("#cnx_year").removeClass("error_border");$("#cnx_dob_wrapper").data("su","ulock");cnxLockCheck()}else if($("#cnx_day").val()!=="init"&&$("#cnx_month").val()!=="init"&&$("#cnx_year").val()!=="init"){$("#cnx_day").removeClass("error_border");$("#cnx_month").removeClass("error_border");$("#cnx_year").removeClass("error_border");
$("#cnx_dob_wrapper").data("su","ulock");cnxLockCheck()}else{$("#cnx_day").addClass("error_border");$("#cnx_month").addClass("error_border");$("#cnx_year").addClass("error_border");$("#cnx_dob_wrapper").data("su","lock");cnxLockCheck()}}
$("#cnx_form_login_input").blur(function(){$("#cnx_form_passwd_input").removeClass("error_border");$("#cnx_form_login_input").removeClass("error_border");if($("#cnx_form_login_input").val()===""){$("#cnx_form_login_input").data("su","ulock");$("#cnx_form_passwd_input").data("su","ulock");cnxLockCheck()}else cnx_login_check($("#cnx_form_login_input").val());sidebarPos();sid()});
$("#cnx_form_passwd_input").blur(function(){$("#cnx_form_passwd_input").removeClass("error_border");$("#cnx_form_login_input").removeClass("error_border");if($("#cnx_form_passwd_input").val()===""){$("#cnx_form_login_input").data("su","ulock");$("#cnx_form_passwd_input").data("su","ulock");cnxLockCheck()}else cnx_passwd_check($("#cnx_form_passwd_input").val());sidebarPos();sid()});var cnx_validation_ok=true;
function cnx_login_validation(input){if(!regMail.test(input)||input==="")if(!regNickname.test(input)||input===""){cnx_validation_ok=false;$("#cnx_form_login_input").addClass("error_border")}}function cnx_passwd_validation(input){if(!regSafe.test(input)||input===""){cnx_validation_ok=false;$("#cnx_form_passwd_input").addClass("error_border")}}
function cnx_birthday_validation(){if($("#cnx_day").val()==="init"&&$("#cnx_month").val()==="init"&&$("#cnx_year").val()==="init");else if($("#cnx_day").val()!=="init"&&$("#cnx_month").val()!=="init"&&$("#cnx_year").val()!=="init");else cnx_validation_ok=false}
$("#cnx_submit").click(function(e){e.preventDefault();sidebarPos();var cnxFinalLogin=$("#cnx_form_login_input").val();var cnxFinalPasswd=$("#cnx_form_passwd_input").val();cnx_validation_ok=true;cnx_login_validation(cnxFinalLogin);cnx_passwd_validation(cnxFinalPasswd);cnx_birthday_validation();sidebarPos();var connectpage_ajax_locker=ajaxConnectPage();if(cnx_validation_ok===true&&connectpage_ajax_locker[0]===true){cnxErrorMsg(Kxlib_getDolphinsValue("p_cnx_default"));cnxErrorBox();$("#cnx_locktype").val(connectpage_ajax_locker[1]);
var date=new Date;var s=date.getSeconds();var m=date.getMinutes();var h=date.getHours();var tod=h+":"+m+":"+s;$("#cnx_tod").val(tod);$("#cnx_form").submit()}else if(cnx_validation_ok===true&&connectpage_ajax_locker[0]==="deletedacc"){sidebarPos();e.preventDefault()}else{sidebarPos();e.preventDefault()}});
function sid(){var exs=false;var cred=false;$(".cnx_hidden_grp").remove();$("#cnx_login_spinner").show();if($("#cnx_form_login_input").val()!==""&&$("#cnx_form_passwd_input").val()!==""){exs=ajaxCnxAccountExists($("#cnx_form_login_input").val());cred=ajaxCnxGCChecker()}else;if(exs===true&&cred===true&&$("#cnx_form_login_input").val()!==""&&$("#cnx_form_passwd_input").val()!==""){var sg=ajaxCnxSupergroupChecker();var tc=ajaxCnxIsThirdCrit();switch(sg){case -1:$("#cnx_msg > p").html(Kxlib_getDolphinsValue("p_cnx_srv_err"));
$("#cnx_msg").css("border-color","red");$("#cnx_msg").css("background-color","pink");case 1:if($("#cnx_birthday_group").css("display")==="none")$("#cnx_birthday_group").slideDown();if($("#cnx_supergroup").css("display")==="none")$("#cnx_supergroup").slideDown();break;case 0:case 2:case 3:case false:default:if(tc===true){if($("#cnx_birthday_group").css("display")==="none")$("#cnx_birthday_group").slideDown()}else if(tc===-1){$("#cnx_msg > p").text(Kxlib_getDolphinsValue("p_cnx_srv_err"));$("#cnx_msg").css("border-color",
"red");$("#cnx_msg").css("background-color","pink")}break}}$("#cnx_login_spinner").hide()}function cnxBirthdayDisplay(){$("#cnx_birthday_group").slideDown()}function cnxBirthdayHide(){$("#cnx_birthday_group").slideUp()}$("#cnx_form").bind("keyup keypress",function(e){var code=e.keyCode||e.which;if(code===13){e.preventDefault();return false}});$(document).on("click","#delcancel_keep",function(){location.href="http://www.trenqr.com"});$(document).on("click","#delcancel_abort",function(){ajaxCnxTodeleteCancel($("#cnx_form_login_input").val())});
