var regFullname=/^[a-zA-Z- \u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00c7\u00e7\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00ff\u00d1\u00f1]{2,40}$/;var regNickname=/^[a-zA-Z0-9-\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00c7\u00e7\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00ff\u00d1\u00f1]{2,20}$/;
var regMail=/^[a-zA-Z0-9-]{1,15}([.][a-zA-Z0-9-]{1,15})*@[a-zA-Z0-9-]{1,15}[.][a-z]{2,4}([.][a-z]{2})*$/;
function ajaxThirdCriteriaChecker(){var rtc=false;var jsonData=new Object;jsonData.urqid="hp_thirdCritCheck";jsonData.datas={"login":$("#dd_login").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(typeof dataset==="undefined")console.log("Erreur de retour JSON");else if(dataset.enabled===true){var htmlblock=dataset.htmlblock;$("#home1_scrolllock").append(htmlblock);
rtc=true}}catch(ex){console.log(ex)}},error:function(jqXHR,errorThrown,textStatus){console.log(jqXHR);console.log(errorThrown);console.log(textStatus)}});return rtc}
function ajaxSupergroupChecker(){var sgc=false;var jsonData=new Object;jsonData.urqid="hp_supergroupUserCheck";jsonData.datas={"login":$("#dd_login").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(typeof dataset==="undefined")console.log("erreur retour json");else{var htmlblock=dataset.htmlblock;$("#home1_scrolllock").append(htmlblock);switch(dataset.status){case "superuser_email":sgc=
1;break;case "superuser_pseudo":sgc=2;break;case "classical_user":sgc=3;break;default:sgc=0;break}}}catch(ex){console.log(ex)}}});return sgc}
function ajaxGCChecker(){var ret=false;var jsonData=new Object;jsonData.urqid="hp_overlayGCChecker";jsonData.datas={"login":$("#dd_login").val(),"passwd":$("#dd_passwd").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(typeof dataset!=="undefined")ret=dataset.gcc}catch(ex){console.log(ex)}}});return ret}
function ajaxLoginChecker(){var date=new Date;var s=date.getSeconds();var m=date.getMinutes();var h=date.getHours();var homeLoginLocker;var jsonData={};jsonData.urqid="hp_overlayConnectSubmit";jsonData.datas={"timeofday":h+":"+m+":"+s,"login":$("#dd_login").val(),"passwd":$("#dd_passwd").val(),"staycon":$("#session").prop("checked"),"locktype":"min"};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=
JSON.parse(data);if(dataset.connected===false){$("#dd_error").html(Kxlib_getDolphinsValue("p_home_cnxfailed"));$("#dd_login").addClass("form_error_border");$("#dd_passwd").addClass("form_error_border");var error=Kxlib_getDolphinsValue(dataset.err_ref);var redir_form_main=document.createElement("form");var login=document.createElement("input");var error_ref=document.createElement("input");redir_form_main.method="POST";redir_form_main.action="connection.php";login.name="login";login.value=$("#dd_login").val();
login.type="hidden";error_ref.name="error_ref";error_ref.value=error;error_ref.type="hidden";redir_form_main.appendChild(login);redir_form_main.appendChild(error_ref);document.body.appendChild(redir_form_main);redir_form_main.submit();homeLoginLocker=false}else if(dataset.connected===true){$("#dd_error").html("");$("#dd_login").removeClass("form_error_border");$("#dd_passwd").removeClass("form_error_border");var tdl=ajaxHomepageTodeleteCheck();if(tdl===true)homeLoginLocker=true;else homeLoginLocker=
false}}catch(ex){console.log(ex)}},error:function(jqXHR,textStatus,errorThrown){console.log("Error");console.log(errorThrown);console.log(textStatus)}});return homeLoginLocker}
function ajaxHomepageTodeleteCheck(){var rVal;var jsonData=new Object;jsonData.urqid="hp_todeleteAccountCheck";jsonData.datas={"login":$("#dd_login").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(typeof dataset!=="undefined")if(dataset.todelete===true){var path="../../public/css/delcancel_style.css";var link=document.createElement("link");link.setAttribute("rel",
"stylesheet");link.setAttribute("type","text/css");link.setAttribute("href",path);document.getElementsByTagName("head")[0].appendChild(link);var overlay=dataset.overlay;$("#home1_scrolllock").append(overlay);todeleteOverlay();rVal=false}else rVal=true}catch(ex){console.log(ex)}}});return rVal}
function ajaxHomepageTodeleteCancel(login){var jsonData=new Object;jsonData.urqid="hp_todeleteAccountCancel";jsonData.datas={"login":login};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){$("#dropdown_login_submit").trigger("click");ajaxLoginChecker()},error:function(jqXHR,textStatus,errorThrown){console.log("Error");console.log(errorThrown);console.log(textStatus)}})}
function ajaxHomepageDobCheck(){var date=new Date;var s=date.getSeconds();var m=date.getMinutes();var h=date.getHours();var jsonData=new Object;jsonData.urqid="hp_overlayConnectSubmit";if($("#home_overlay_superpw").length)jsonData.datas={"timeofday":h+":"+m+":"+s,"login":$("#dd_login").val(),"passwd":$("#dd_passwd").val(),"staycon":$("#session").prop("checked"),"birthday":$("#dd_hb").val(),"superpw":$("#home_overlay_superpw").val(),"locktype":"full"};else jsonData.datas={"timeofday":h+":"+m+":"+s,
"login":$("#dd_login").val(),"passwd":$("#dd_passwd").val(),"staycon":$("#session").prop("checked"),"birthday":$("#home_overlay_day").val()+"-"+$("#home_overlay_month").val()+"-"+$("#home_overlay_year").val(),"locktype":"dob"};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(typeof dataset==="undefined")console.log("Erreur de retour JSON");else if(dataset.connected===
false){var error=Kxlib_getDolphinsValue(dataset.err_ref);var redir_form=document.createElement("form");var login=document.createElement("input");var error_ref=document.createElement("input");redir_form.method="POST";redir_form.action="connection.php";login.name="login";login.value=$("#dd_login").val();login.type="hidden";error_ref.name="error_ref";error_ref.value=error;error_ref.type="hidden";redir_form.appendChild(login);redir_form.appendChild(error_ref);document.body.appendChild(redir_form);redir_form.submit()}else window.location.href=
"./landing.php"}catch(ex){console.log(ex)}},error:function(jqXHR,textStatus,errorThrown){console.log("Error");console.log(errorThrown);console.log(textStatus)}})}
function ajaxHomepageAccountExists(login){var rt;var jsonData=new Object;jsonData.urqid="hp_accountExists";jsonData.datas={"login":login};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(typeof dataset!=="undefined"){var exists=dataset.exists;if(exists===null)rt=false;else rt=true}}catch(ex){console.log(ex)}},error:function(jqXHR,textStatus,errorThrown){console.log("Error");
console.log(errorThrown);console.log(textStatus)}});return rt}
function ajaxPreInsChecker(e){var homePreinsLocker;var jsonData={};jsonData.urqid="hp_crprg";jsonData.datas={"fullname":$("#fullname").val(),"pseudo":$("#nickname").val(),"email":$("#email").val(),"passwd":$("#passwd").val()};var formURL="http://www.trenqr.com/forrest/index.php?page=signup&urqid=hp_crprg";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{console.log(data);var dataset=JSON.parse(data);if(dataset.preins_status===false){overlay_display();errorMessage(Kxlib_getDolphinsValue("p_home_taform_fail"));
homePreinsLocker=false}else if(dataset.preins_status!==false){overlay_hide();errorMessage("");homePreinsLocker=dataset.preins_status}}catch(ex){console.log(ex)}},error:function(jqXHR,textStatus,errorThrown){console.log("Error");console.log(errorThrown);console.log(textStatus)}});return homePreinsLocker}
function ajaxPseudoAvailability(){var regPseudo=/^[a-zA-Z0-9-_@ \u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00d2\u00d3\u00d4\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00c7\u00e7\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00ff\u00d1\u00f1]{2,20}$/;if(regPseudo.test($("#nickname").val())){var rValue;var jsonData=new Object;jsonData.urqid="hp_prgpsdchk";jsonData.datas=
{"pseudo":$("#nickname").val()};var formURL="http://www.trenqr.com/forrest/index.php?page=signup&urqid=hp_prgpsdchk";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dset=JSON.parse(data);if(dset.available!==false)rValue=dset.available;else rValue=false}catch(ex){console.log(ex)}}});return rValue}}
function ajaxMailAvailability(){var regMail=/^[a-zA-Z0-9-_]{1,15}([.][a-zA-Z0-9-_]{1,15})*@[a-zA-Z0-9-_]{1,15}([.][a-zA-Z0-9-_]{1,15})*([.][A-Za-z0-9]{2,4})+$/;if(regMail.test($("#email").val())){var rValue;var jsonData=new Object;jsonData.urqid="hp_prgemachk";jsonData.datas={"email":$("#email").val()};var formURL="http://www.trenqr.com/forrest/index.php?page=signup&urqid=hp_prgemachk";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{var dset=JSON.parse(data);if(dset.available!==
false)rValue=dset.available;else rValue=false}catch(ex){console.log(ex)}}});return rValue}}
function ajaxTrialMailChecker(e){var regMail=/^[a-zA-Z0-9-_]{1,15}([.][a-zA-Z0-9-_]{1,15})*@[a-zA-Z0-9-_]{1,15}([.][a-zA-Z0-9-_]{1,15})*([.][A-Za-z0-9]{2,4})+$/;var homeTrialLocker;var jsonData={};jsonData.urqid="hp_trialEmailCheck";jsonData.datas={"email":$("#mode_essai_mail").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{if(typeof data!=="undefined"){var dataset=JSON.parse(data);console.log(dataset);
if(dataset.availability===false){$("#mode_essai_error").html(Kxlib_getDolphinsValue("p_home_email_aiu"));$("#mode_essai_mail").addClass("form_error_border");homeTrialLocker=false}else if(regMail.test($("#mode_essai_mail").val())){$("#mode_essai_error").html("");$("#mode_essai_mail").removeClass("form_error_border");homeTrialLocker=true}else{$("#mode_essai_error").html("Adresse email invalide");$("#mode_essai_mail").addClass("form_error_border");homeTrialLocker=false}}else{$("#mode_essai_error").html("Erreur inconnue");
$("#mode_essai_mail").addClass("form_error_border");homeTrialLocker=false}}catch(ex){console.log(ex)}},error:function(jqXHR,textStatus,errorThrown){console.log("Error");console.log(errorThrown);console.log(textStatus)}});return homeTrialLocker}
function trialMailSaveRedirect(e){if(e.type!=="click"){console.log("lightbypass");return}var jsonData=new Object;jsonData.urqid="hp_trialMailRedirect";jsonData.datas={"email":$("#mode_essai_mail").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({url:formURL,type:"POST",data:jsonData,success:function(data){try{var dataset=JSON.parse(data);if(dataset.status==="ok"){var form=$('<form action="'+dataset.location+'" method="post">'+'<input type="text" name="email" value="'+
dataset.email+'" />'+'<input type="text" name="instype" value="tryaccount" />'+"</form>");$(form).submit()}else window.location.href=dataset.location+"?errno="+dataset.errcode}catch(ex){console.log(ex)}}})}
function ajaxPreregLoginCheck(e){var rVal=false;jsonData={};jsonData.urqid="hp_preinsLoginAttempt";jsonData.datas={"login":$("#dd_login").val(),"passwd":$("#dd_passwd").val()};var formURL="../../process_urq/welcome_project/urq_sandbox.php";$.ajax({async:false,url:formURL,type:"POST",data:jsonData,success:function(data){try{dataset=JSON.parse(data);if(dataset.isPreregAccount===true){rVal=true;e.preventDefault();preregLoginOverlay()}}catch(ex){console.log(ex)}},error:function(jqXHR,textStatus,errorThrown){console.log("Error");
console.log(errorThrown);console.log(textStatus)}});return rVal};
