function htmlEntities(str){return String(str).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;")}function duplicateOverseer(inputArray){var compteur=1;var len=inputArray.length;if(len===1)compteur=1;else for(var i=0;i<len;i++)if($.inArray(inputArray[i],inputArray,i+1)!==-1)compteur++;return compteur}
function selectDistinct(inputArray){var resultArray=new Array;var formatArray=new Array;var dupliArray=new Array;for(var i=0;i<inputArray.length;i++)if($.inArray(inputArray[i],resultArray)===-1)resultArray.push(inputArray[i]);else dupliArray.push(inputArray[i]);dupliArray.sort();var out=new Array;var currentElem=null;var cnt=0;for(var j=0;j<dupliArray.length;j++)if(dupliArray[j]!==currentElem){if(cnt>0)out.push([currentElem,cnt+1]);currentElem=dupliArray[j];cnt=1}else cnt++;if(cnt>0)out.push([currentElem,
cnt+1]);for(var k=0;k<resultArray.length;k++){var lock=false;for(var l=0;l<out.length;l++)if(resultArray[k]===out[l][0]){formatArray.push('<div data-fortable="multi" class="customlist_choices"><span class="nom_ville">'+resultArray[k]+'</span> <span class="nb_villes">'+out[l][1]+" "+Kxlib_getDolphinsValue("p_cities")+"</span></div>");lock=true}if(lock===false)formatArray.push('<div data-fortable="mono" class="customlist_choices">'+resultArray[k]+"</div>")}return formatArray}var globalArray=new Array;
var globalLight=new Array;var multiArray=new Array;
function insCityAutocomplete(tab){var cityDuplicates=0;var srcArray=new Array;var lightArray=new Array;var light2=new Array;globalArray.length=0;globalLight.length=0;multiArray.length=0;$.each(tab,function(index,value){srcArray.push(value);lightArray.push(value.asciiname)});for(var i=0;i<srcArray.length;i++){light2[i]=[srcArray[i].city_id,srcArray[i].asciiname];globalLight[i]=[srcArray[i].city_id,srcArray[i].asciiname];multiArray[i]=[srcArray[i].city_id,srcArray[i].asciiname,srcArray[i].ctr_name,
srcArray[i].city_pop];globalArray[srcArray[i].city_id]=[srcArray[i].asciiname,srcArray[i].ctr_name,srcArray[i].city_pop]}cityDuplicates=duplicateOverseer(lightArray);if(cityDuplicates>=1&&tab.length!==0){$("#customlist").hide();var light3=selectDistinct(lightArray);$("#customlistmulti").empty();$.each(light3,function(k,v){var $p=$("<a/>");$p.html(v);$p.addClass("jsbind-city-lis-elm");$p.addClass("city-lis-elm");if($("#customlistmulti > .jsbind-city-lis-elm").length<10){$($p).on("mousedown",function(e){e.stopPropagation();
$("#ins_input_city").data("temp","allowed");var target=$(e.target).closest(".customlist_choices");HandleSelectMulti(target);$("#city_tooltip_wrapper").fadeOut()});$("#customlistmulti").append($p)}});$("#customlistmulti").show();$("#ins_city_spinner").hide()}else{$("#customlist").hide();$("#customlistmulti").hide();$("#ins_city_spinner").hide()}}
function HandleSelectMulti(t){if(t.data("fortable")==="mono"){$("#ins_input_city").val(t.html());$("#customlistmulti").hide();$("#ins_city_table_wrapper").slideUp();for(var i=0;i<multiArray.length;i++)if(multiArray[i][1]===$("#ins_input_city").val())$("#ins_input_city").data("cc",multiArray[i][0]);ins_city_check($("#ins_input_city").val())}else if(t.data("fortable")==="multi"){var cName=t.find(".nom_ville").html();$("#ins_input_city").val(cName);$("#customlistmulti").hide();$("#city_table").html("<tr><th>"+
Kxlib_getDolphinsValue("p_city")+"</th><th>"+Kxlib_getDolphinsValue("p_country")+"</th><th>"+Kxlib_getDolphinsValue("p_population")+"</th></tr>");for(var j=0;j<multiArray.length;j++)if(multiArray[j][1]===cName)$("#city_table").append("<tr data-city='"+multiArray[j][0]+"' class='citylist'><td>"+multiArray[j][1]+"</td><td>"+multiArray[j][2]+"</td><td>"+multiArray[j][3]+"</td></tr>");$("#city_table_wrapper").slideDown(400,function(){$("#ins_input_city").focus()});$("#city_tooltip_wrapper").fadeOut()}else console.log("Error: HandleSelectMulti(t)")}
function manualInputChecker(lightTypeArray,manualInput){$.each(lightTypeArray,function(k,v){if(manualInput.toLowerCase()===v[1].toLowerCase()&&lightTypeArray.length===1)$("#ins_input_city").data("cc",v[0].toString());else if(manualInput.toLowerCase()===v[1].toLowerCase()&&lightTypeArray.length>1){$("#ins_input_city").data("cc","multi");$("#city_tooltip_wrapper").fadeIn()}})}$("#city_table, #city_table *").on("mousedown",".citylist",function(){$("#ins_input_city").data("check","false")});
$("#city_table").on("mousedown",".citylist",function(){var thisId=$(this).data("city");$("#ins_input_city").val(globalArray[thisId][0]+", "+globalArray[thisId][1]);$("#ins_input_city").data("cc",thisId);$("#city_table_wrapper").slideUp();$("#city_tooltip_wrapper").fadeOut();ins_city_check($("#ins_input_city").val())});
$(document).click(function(e){if($(e.target).is("#ins_birthday_wrapper, #ins_birthday_wrapper *"));else if($(e.target).is("#ins_input_city"));else if($(e.target).is("#city_tooltip_wrapper, #city_tooltip")){HandleSelectMulti($(".customlist_choices"));$("#city_tooltip_wrapper").fadeOut()}else if($(e.target).is("#ins_form, #ins_form *")){$("#customlist").hide();$("#customlistmulti").hide()}else;if($(e.target).not("#ins_input_city, #ins_input_city *"))$("#ins_input_city").data("temp","0")});
$("#ins_input_city").focus(function(){if($(this).data("cc")==="multi")$("#customlistmulti").show()});$("#ins_form").bind("keyup keypress",function(e){var key=e.which;if(key===13){e.preventDefault();e.stopPropagation()}else if(key===27){e.preventDefault();e.stopPropagation()}});var delay=function(){var timer=0;return function(callback,ms){clearTimeout(timer);timer=setTimeout(callback,ms)}}();var index=0;
$("#ins_input_city").keyup(function(e){delay(function(){$("#city_table_wrapper").slideUp();$("#ins_input_city").data("cc","-1");$("#ins_input_city").data("check","true");if($("#ins_input_city").val()===""){$("#customlist").hide();$("#customlistmulti").hide()}else{$("#ins_city_spinner").show();ajaxCitySuggestion()}},250)});
