function Trend(isload){var gt=this;var _datas;var _t;var _d;var _c;var _p;var _g;var _ti;var _f_Init=function(){try{if(typeof window.pageIsLoaded==="undefined"||window.pageIsLoaded===false){if($(".jb-mdl-tr-post-in-list").length&&$(".jb-mdl-tr-post-in-list").length===6&&parseInt($("#tr-h-t-d-20").data("length"))>6){$(".jb-whub-mx").addClass("this_hide");$(".jb-trpg-loadm-box").removeClass("this_hide")}else if($(".jb-mdl-tr-post-in-list").length&&$(".jb-mdl-tr-post-in-list").length<=6){$(".jb-whub-mx").addClass("this_hide");
$(".jb-trpg-loadm-box").addClass("this_hide")}else{$(".jb-trpg-loadm-box").addClass("this_hide");$(".jb-whub-mx").removeClass("this_hide")}if($(".jb-a-h-t-top-img").length)$(".afl_choice.bind-deltrcov").removeClass("this_hide");else $(".afl_choice.bind-deltrcov").addClass("this_hide");window.pageIsLoaded=true}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_OnLoad=function(il){try{var $sl=$(".jb-mdl-tr-post-in-list");gt._f_FrmtDsc($sl);_f_AdjtArtBx($sl);if(il!==false)_f_OrdArts($sl)}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};this._f_Shuffle=function($sl){try{$sl=KgbLib_CheckNullity($sl)?$(".jb-trpg-art-nest").find(".jb-mdl-tr-post-in-list"):$sl;_f_OrdArts($sl);_f_AdjtArtBx($sl)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};this._f_WColSlip=function($sl,dr){try{if(KgbLib_CheckNullity($sl)|!$sl.length|KgbLib_CheckNullity(dr)|$.inArray(dr,["top","btm"])===-1|$("#nwtrdart-box").height()===0)return;$.each($sl,function(i,e){if(i%2===0&&$(e).height()!==0&&!KgbLib_CheckNullity($(e).css("transform"))&&
typeof $(e).css("transform")==="string"){var x=parseInt($(e).css("transform").split(",")[4].substr(1));var y=$(e).css("transform").split(",")[5];y=parseInt(y.substr(1,y.length-1));if(dr==="btm"){y+=40;y+=$("#nwtrdart-box").height()}else if(dr==="top"){y-=40;y-=$("#nwtrdart-box").height()}$(e).css({transform:"translate3d("+x+"px, "+y+"px, 0px)"})}});var bxh=$(".jb-trpg-art-nest").height();if(dr==="btm")$(".jb-trpg-art-nest").height(bxh+$("#nwtrdart-box").height()+40);else if(dr==="top")$(".jb-trpg-art-nest").height(bxh-
$("#nwtrdart-box").height()-40)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};this._f_FrmtDsc=function($sl){try{if(KgbLib_CheckNullity($sl))return;if($sl.length){var is=[];var __=0;$.each($sl,function(x,am){var atxt=$(am).find(".jb-mdl-acc-post-txt").text();atxt=$("<div/>").html(atxt).text();var ajca_o=typeof $(am).data("ajcache")==="object"?$(am).data("ajcache"):JSON.parse(""+$(am).data("ajcache")+"");var ustgs=ajca_o.ustgs;var hashs=ajca_o.hashs;var rtxt=Kxlib_TextEmpow(atxt,
ustgs,hashs,null,{emoji:{"size":36,"size_css":20,"position_y":3}});$(am).find(".jb-mdl-acc-post-txt").text("").append(rtxt);$(am).find(".jb-mdl-acc-post-txt").hide().removeClass("this_invi").fadeIn()})}else Kxlib_DebugVars(["Pas d'ARTICLES"],true)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_AdjtArtBx=function($sl){try{if(KgbLib_CheckNullity($sl)|!$sl.length)return;var h__=0,mrg=20,ntab=[];if($($sl).length===1)h__=$($sl).first().height()+mrg;else $.each($sl,function(i,e){if(i%
2!==0&&$(e).height()!==0){var t__=$(e).prev().height()>=$(e).height()?$(e).prev().height():$(e).height();t__+=mrg;h__+=t__}if($(e).height()!==0)ntab.push(e)});if(ntab.length>1&&ntab.length%2!==0)h__+=$(ntab[ntab.length-1]).height()+mrg;h__+=3;$(".jb-trpg-art-nest").height(h__)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_OrdArts=function($sl){try{if(KgbLib_CheckNullity($sl)|!$sl.length)return;var x=0,y=0,cn=0,eh=0,wh=0;$.each($sl,function(i,a){if($(a).height()===0|$(a).hasClass("this_hide"))return;
var cx,cy;if(i===0){x=1;y=0;cx=0;cy=0}else if(i===1){x=373+20;y=0;cx=1;cy=0}else if(i%2===0){x=1;y=eh+20*(i/2)}else{x=373+20;y=wh+20*((i-1)/2)}$(a).css({transform:"translate3d("+x+"px, "+y+"px, 0px)"});if(KgbLib_CheckNullity(cx)&&KgbLib_CheckNullity(cy)){cx=i;cy=i%2===0?i/2:(i-1)/2}$(a).data("at","["+cx+","+cy+"]");if(i%2===0)eh+=$(a).height();else wh+=$(a).height();if($(a).hasClass("this_invi"))$(a).hide().removeClass("this_invi").fadeIn()})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],
true)}};var _f_ChkTrXst=function(t,s,m){_f_Srv_ChkTrXsts(t,s,m)};var _f_ChkTrLvs=function(t,s,m){_f_Srv_ChkTrLvs(t,s,m)};var _f_ChkUserFolg=function(u,t){};var AcqrTrFeats=function(t){};var _f_RelM_ChkTrdXsts=function(r,s,md){var dl="err_trpg_tr_donotexists_msg";var mode=KgbLib_CheckNullity(md)||md.length!==1?"b":md[0];if(!r){switch(mode){case "m":case "messsage":$(s).attr("return",Kxlib_getDolphinsValue(dl));break;case "boolean":case "bool":case "b":$(s).attr("return",false);break;default:$(s).attr("return",
false);break}$(s).trigger("datasready")}else if(mode==="b"||mode==="bool"||mode==="boolean"){$(s).attr("return",true);$(s).trigger("datasready")}};var _f_RelM_ChkTrdLives=function(r,s,md){var dl="err_trpg_tr_nonliving_msg";var mode=KgbLib_CheckNullity(md)||md.length!==1?"b":md[0];if(!r){switch(mode){case "m":case "messsage":$(s).attr("return",Kxlib_getDolphinsValue(dl));break;case "bool":case "b":$(s).attr("return",false);break;default:$(s).attr("return",false);break}$(s).trigger("datasready")}else if(mode===
"b"||mode==="bool"||mode==="boolean"){$(s).attr("return",true);$(s).trigger("datasready")}};this.checkTrExists_url="http://127.0.0.1/korgb/ajax_test.php";this.checkTrExists_uq="chk_tr_exists";var _Ax_ChkTrXsts=Kxlib_GetAjaxRules("CHK_TR_XST");var _f_Srv_ChkTrXsts=function(i,s,md){if(KgbLib_CheckNullity(i)|KgbLib_CheckNullity(i)|KgbLib_CheckNullity(md))return;var onsuccess=function(datas){if(!KgbLib_CheckNullity(datas))datas=JSON.parse(datas);var o=new ErrorBarVTop,i="#err_bar_in_trpg";if(typeof datas.err!==
"undefined"){var me=Kxlib_getDolphinsValue("err_com_failajax_sys");me=!KgbLib_CheckNullity(datas.err)?datas.err:me;o.EB_DeclareErr(i,me)}else if(typeof datas.return==="undefined"){var mr=Kxlib_getDolphinsValue("err_com_failajax_sys");o.EB_DeclareErr(i,mr,"m")}else{o.CloseBar(i);_f_RelM_ChkTrdXsts(datas.return,s,md)}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b)};var toSend={"urqid":_Ax_ChkTrXsts.urqid,"datas":{"trid":i}};Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_ChkTrXsts.url,
wcrdtl:_Ax_ChkTrXsts.wcrdtl})};var _f_Srv_ChkTrLvs=function(i,s,md){if(KgbLib_CheckNullity(i)|KgbLib_CheckNullity(s)|KgbLib_CheckNullity(md))return;var th=this;var onsuccess=function(datas){if(!KgbLib_CheckNullity(datas))datas=JSON.parse(datas);var o=new ErrorBarVTop,i="#err_bar_in_trpg";if(typeof datas.err!=="undefined"){var lm=Kxlib_getDolphinsValue("err_com_failajax_sys");var m=!KgbLib_CheckNullity(datas.err)?datas.err:lm;o.EB_DeclareErr(i,m)}else if(typeof datas.return==="undefined"){var rm=Kxlib_getDolphinsValue("err_com_failajax_sys");
o.EB_DeclareErr(i,rm,"m")}else{o.CloseBar(i);_f_RelM_ChkTrdLives(datas.return,s,md)}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b)};var toSend={"urqid":th.checkTrLives_uq,"datas":{"trid":i}};Kx_XHR_Send(toSend,"post",this.checkTrLives_url,onerror,onsuccess)};_f_Init();_f_OnLoad(isload)}new Trend;
