function ASDAPPS(){var _f_Gdf=function(){var ds={"aaa":["goguidebox","gosearchbox","gochatbox"],"_15psz":{h:770,w:1400}};return ds};var _f_Init=function(){$(".jb-aside-mods").data("lk",1);_f_SwImHigh()};var _f_SwApps=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action"))|$.inArray($(x).data("action"),_f_Gdf().aaa)===-1|!$(".jb-asd-apps-chc.selected").length|!$(".jb-asd-apps-chc.selected").data("action"))return;var a=$(x).data("action");if($(".jb-asd-apps-chc.selected").data("action")===
a)return;switch(a){case "goguidebox":_f_VwSwApps(x);break;case "gosearchbox":_f_VwSwApps(x);break;case "gochatbox":_f_VwSwApps(x);break;default:return}_f_VwSlctAppsCh(x)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_SwImHigh=function(x,shw,lk){try{if(!KgbLib_CheckNullity($(".jb-aside-mods").data("lk"))&&$(".jb-aside-mods").data("lk")===1)return;var t__=$(x).scrollTop()-369;if(shw&&typeof x!==undefined&&$(x).length)$("#aside").css({top:t__+"px"});else $("#aside").css({top:"0"})}catch(ex){}};
var _f_Unpin=function(x){try{if(KgbLib_CheckNullity(x))return;var t__=KgbLib_CheckNullity($(".jb-aside-mods").data("lk"))||$(".jb-aside-mods").data("lk")===0?1:0;$(".jb-aside-mods").data("lk",t__);var ilk;if(t__){ilk=false;$(".jb-asd-apps-pin-btn").attr("data-state","lock")}else{ilk=true;$(".jb-asd-apps-pin-btn").attr("data-state","ulock")}if($(window).scrollTop()>379)$("#aside").css({top:"0"});$(".jb-aside").removeAttr("style");$(".jb-aside").removeClass("flying");var $alst=$(".jb-arp-solo-in-acclist");
var $aoplst=$(".jb-tmlnr-mdl-std:not(:first)").find(".jb-arp-solo-in-acclist:not(.this_hide)");var $aclzlst=$(".jb-arp-solo-in-acclist.this_hide");if(screen&&(screen.height<_f_Gdf()._15psz.h|screen.width<_f_Gdf()._15psz.w&&$alst.length)){if($aoplst.length)if(ilk)$aoplst.switchClass("fit","edge",400);else $aoplst.switchClass("edge","fit",400);if($aclzlst.length)if(ilk)$aclzlst.switchClass("fit","edge");else $aclzlst.switchClass("edge","fit")}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],
true)}};var _f_gdbx_grpch=function(x){try{if(KgbLib_CheckNullity(x)|!$(x).length|!$(x).closest(".jb-asd-gdbx-l-bx").length|KgbLib_CheckNullity($(x).closest(".jb-asd-gdbx-l-bx").data("order")))return;var $gp=$(x).closest(".jb-asd-gdbx-l-bx"),gpo=$gp.data("order").toLowerCase();if(!$gp.find(".jb-asd-gdbx-l-cntt").length)return;var $ctt=$gp.find(".jb-asd-gdbx-l-cntt");switch(gpo){case "trenqr_what":case "trenqr_why":case "trenqr_next":case "trenqr_sure":case "trenqr_when":$gp.toggleClass("active");$ctt.toggleClass("active");
default:return}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_VwSwApps=function(x){try{if(KgbLib_CheckNullity(x))return;var a=$(x).data("action"),lp,$bnw,$bol;var $sn__,$so__;switch(a){case "goguidebox":$bnw=$(".jb-asdapp-modl[data-modl='guidebox']");$bol=$(".jb-asdapp-modl[data-modl='chatbox'], .jb-asdapp-modl[data-modl='searchbox']");$sn__=$(".jb-asd-apps-chc[data-action='goguidebox']");$so__=$(".jb-asd-apps-chc[data-action='gosearchbox'], .jb-asd-apps-chc[data-action='gochatbox']");
break;case "gosearchbox":$bnw=$(".jb-asdapp-modl[data-modl='searchbox']");$bol=$(".jb-asdapp-modl[data-modl='chatbox'], .jb-asdapp-modl[data-modl='guidebox']");$sn__=$(".jb-asd-apps-chc[data-action='gosearchbox']");$so__=$(".jb-asd-apps-chc[data-action='goguidebox'], .jb-asd-apps-chc[data-action='gochatbox']");break;case "gochatbox":$bnw=$(".jb-asdapp-modl[data-modl='chatbox']");$bol=$(".jb-asdapp-modl[data-modl='searchbox'], .jb-asdapp-modl[data-modl='guidebox']");$sn__=$(".jb-asd-apps-chc[data-action='gochatbox']");
$so__=$(".jb-asd-apps-chc[data-action='gosearchbox'], .jb-asd-apps-chc[data-action='goguidebox']");break;default:return}if(true){$bol.addClass("this_hide");$bnw.removeClass("this_hide")}$sn__.addClass("selected");$so__.removeClass("selected")}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_VwSlctAppsCh=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action"),sld,ico;sld=$(".jb-asd-apps-ch-illus.selected");if(!$(sld).length||
KgbLib_CheckNullity($(sld).data("scp"))||$(sld).data("scp")===$(ico).data("scp"))return;switch(a){case "goguidebox":ico=$(".jb-asd-apps-ch-illus[data-scp='guidebox']");break;case "gochatbox":ico=$(".jb-asd-apps-ch-illus[data-scp='chatbox']");break;case "gosearchbox":ico=$(".jb-asd-apps-ch-illus[data-scp='searchbox']");break;default:return}$(".jb-asd-apps-ch-illus").stop(true,true).fadeOut(500).addClass("this_hide");$(".jb-asd-apps-ch-illus").removeClass("selected");$(ico).stop(true,true).hide().removeClass("this_hide").fadeIn(500).addClass("selected")}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};var _f_VwHvrAppsCh=function(x,fe_ih){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action"),sld,ico;var ih=typeof fe_ih==="boolean"?fe_ih:function(){return $(x).is(":hover")?true:false};switch(a){case "goguidebox":ico=$(".jb-asd-apps-ch-illus[data-scp='guidebox']");break;case "gochatbox":ico=$(".jb-asd-apps-ch-illus[data-scp='chatbox']");break;case "gosearchbox":ico=$(".jb-asd-apps-ch-illus[data-scp='searchbox']");
break;default:return}sld=$(".jb-asd-apps-ch-illus.selected");Kxlib_DebugVars([!$(sld).length,KgbLib_CheckNullity($(sld).data("scp")),$(sld).data("scp")===$(ico).data("scp")],false);if(!$(sld).length||KgbLib_CheckNullity($(sld).data("scp"))||$(sld).data("scp")===$(ico).data("scp")){Kxlib_DebugVars(["FAILED !"],false);return}if(ih)$(ico).stop(true,true).hide().removeClass("this_hide").fadeIn(500);else $(ico).stop(true,true).fadeOut(500).addClass("this_hide")}catch(ex){Kxlib_DebugVars([ex,ex.fileName,
ex.lineNumber],true)}};_f_Init();$(".jb-asd-apps-chc").click(function(e){Kxlib_PreventDefault(e);_f_SwApps(this)});$(".jb-asd-apps-chc").hover(function(e){_f_VwHvrAppsCh(this,true)},function(){_f_VwHvrAppsCh(this,false)});$(".jb-asd-apps-pin-btn").click(function(e){Kxlib_PreventDefault(e);_f_Unpin(this)});$(".jb-asd-gdbx-l-tle").click(function(e){Kxlib_PreventDefault(e);_f_gdbx_grpch(this)})}new ASDAPPS;
