function FSTVST(){var _tbix;var _f_Gdf=function(){var dt={"tab_index":[{i:"_IX_HOME",rs:"#header-logo"},{i:"_IX_NEWSFEED",rs:".jb-global-nav-elt[data-target='nwfd']"},{i:"_IX_NOTIFICATION",rs:".jb-global-nav-elt[data-target='pm']"},{i:"_IX_FRDCENTER",rs:".jb-tqr-f-nav-hdr[data-target='friend']"},{i:"_IX_USERBOX",rs:"#user-id-card"},{i:"_IX_PFLPIC",rs:".jb-p-h-b-ui-trg"},{i:"_IX_ATHOME",rs:".jb-tmlnr-hdr-hmbx"},{i:"_IX_COVER",rs:".jb-c-c-start"},{i:"_IX_MENUS_MYP",rs:"#menu-li-post"},{i:"_IX_MENUS_MYT",
rs:"#menu-li-tr"},{i:"_IX_MENUS_FAV",rs:"#menu-li-fav"},{i:"_IX_HDRSTATS",rs:"#acc-header-down"},{i:"_IX_BRAIN",rs:".jb-brn-opn-tgr"},{i:"_IX_ADD_IN_IML_FRD",rs:"#brain_menu_new-ml"},{i:"_IX_ADD_IN_IML_SOD",rs:"#brain_menu_new-sod"},{i:"_IX_ADD_IN_TRD",rs:"#brain_menu_new-ml-tr"},{i:"_IX_TLKBRD",rs:".jb-tqr-testy-hdr-mx"},{i:"_IX_LASTA",rs:".jb-tqr-lasta-mx"},{i:"_IX_ASDBIO",rs:".jb-pflbio-bx"},{i:"_IX_ASDSTATS",rs:".jb-usr-socprt-bx"},{i:"_IX_ASDAPPS",rs:".jb-aside-mods"},{i:"_IX_TIA",rs:"#header-logo-discover"},
{i:"_IX_THEND",rs:""},{i:"_IX_START",rs:"#tmlnr-hdr-homebox"}]};return dt};var _f_Init=function(shpl,shat){try{if(!$(".jb-tqr-fry-hq-mx").hasClass("state-sleeping")){$(".jb-tqr-fry-hq-mx").removeClass("state-wakeup");$(".jb-tqr-fry-hq-mx").addClass("state-sleeping")}if($(".jb-tqr-fdry-invit-bmx").length){var ix__=Kxlib_ObjectChild_Count(_f_Gdf().tab_index);ix__-=1;_f_AcrtLoc(ix__);_f_CmfrtOffset("_IX_START");$(".jb-tqr-fdry-invit-bmx").hide().removeClass("this_hide").fadeIn().removeClass("style")}if(shpl)_f_Vw_ShPnl(true);
if(shat)_f_Vw_ShTips(true)}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Action=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action");switch(a.toLowerCase()){case "close":_f_Close(x);break;case "start":_f_Start(x);break;case "previous":_f_Prev(x);break;case "next":_f_Next(x);break;case "stop":_f_Stop(x);break;default:break}}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Close=function(x){try{if(KgbLib_CheckNullity(x))return;
if($(x).data("lk")===1)return;$(x).data("lk",1);$(".jb-tqr-fdry-invit-bmx").fadeOut().addClass("this_hide");if($(".jb-tqr-fdry-invt-dsma-chkbx").is(":checked")){var s=$("<span/>");var T=new MNFM;T.SetPrfrcs("_PFOP_FSTCNX","_DEC_DSMA",s);$(s).on("operended",function(e){$(".jb-tqr-fstdvry-elmts").remove()})}}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Start=function(x){try{if(!KgbLib_CheckNullity(x)&&$(x).data("action")==="start")$(".jb-tqr-fdry-invit-bmx").fadeOut().addClass("this_hide");
_f_Vw_ShPnl(true);_f_AcrtLoc(0);_f_CmfrtOffset(_f_Gdf().tab_index[0].i);_f_Vw_ShTips(true,_f_Gdf().tab_index[0].i);_tbix=0}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Stop=function(x){try{if(KgbLib_CheckNullity(x)|$(x).data("lk")===1)return;$(x).data("lk",1);_f_Vw_ShTips();_f_Vw_ShPnl();_tbix=0;$(x).data("lk",0)}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Prev=function(x){try{if(KgbLib_CheckNullity(x)|$(x).data("lk")===1)return;$(x).data("lk",1);_f_Vw_ShTips();_tbix=
_tbix===0?0:--_tbix;var i=_f_Gdf().tab_index[_tbix].i.toUpperCase();switch(i){case "_IX_BRAIN":case "_IX_TLKBRD":case "_IX_LASTA":if(!$("#slave_maximus").hasClass("this_hide"))$(".jb-brn-clz-tgr").click();break;case "_IX_ADD_IN_IML_FRD":case "_IX_ADD_IN_IML_SOD":case "_IX_ADD_IN_TRD":if($("#slave_maximus").hasClass("this_hide"))$(".jb-brn-opn-tgr").click();$(".jb-brn-bk").click();$("#brain_menu_new-ml").click();break;case "_IX_START":_tbix-=1;i=_f_Gdf().tab_index[_tbix].i.toUpperCase();break;default:break}_f_AcrtLoc(_tbix);
_f_CmfrtOffset(i);_f_Vw_ShTips(true,i);$(x).data("lk",0)}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Next=function(x){try{if(KgbLib_CheckNullity(x)|$(x).data("lk")===1)return;_f_Vw_ShTips();_tbix=_tbix===Kxlib_ObjectChild_Count(_f_Gdf().tab_index)-1?_tbix:++_tbix;var i=_f_Gdf().tab_index[_tbix].i.toUpperCase();Kxlib_DebugVars(["TUTO > ",i]);switch(i){case "_IX_BRAIN":case "_IX_TLKBRD":case "_IX_LASTA":if(!$("#slave_maximus").hasClass("this_hide"))$(".jb-brn-clz-tgr").click();break;
case "_IX_ADD_IN_IML_FRD":case "_IX_ADD_IN_IML_SOD":case "_IX_ADD_IN_TRD":if($("#slave_maximus").hasClass("this_hide"))$(".jb-brn-opn-tgr").click();$(".jb-brn-bk").click();$("#brain_menu_new-ml").click();break;case "_IX_START":_tbix-=1;i=_f_Gdf().tab_index[_tbix].i.toUpperCase();break;default:break}_f_AcrtLoc(_tbix);_f_CmfrtOffset(i);_f_Vw_ShTips(true,i);$(x).data("lk",0)}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_AcrtLoc=function(ix){try{if(KgbLib_CheckNullity(ix))return;var id=
_f_Gdf().tab_index[ix].i.toUpperCase();var $rs,t,r,b,l;switch(id){case "_IX_HOME":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top+$rs.height()+6+3;l=$rs.offset().left+$rs.width()/2-85;$(".jb-tqr-fry-bx-bmx[data-target='home']").css({top:t,left:l});break;case "_IX_NEWSFEED":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left+$rs.width()/2-300-8;l=$(".jb-tqr-fry-bx-bmx[data-target='newsfeed']").css({top:t+38,left:l});break;case "_IX_NOTIFICATION":$rs=$(_f_Gdf().tab_index[ix].rs);
t=$rs.offset().top;l=$rs.offset().left+$rs.width()/2-300-8;l=$(".jb-tqr-fry-bx-bmx[data-target='notification']").css({top:t+38,left:l});break;case "_IX_FRDCENTER":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left+$rs.width()/2-300;l=$(".jb-tqr-fry-bx-bmx[data-target='frdcenter']").css({top:t+34,left:l});break;case "_IX_USERBOX":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='userbox']").css({top:t+73+"px",left:l-224+
"px"});break;case "_IX_PFLPIC":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left+$rs.width()/2-300-8;l=$(".jb-tqr-fry-bx-bmx[data-target='pflpic']").css({top:t+55,left:l});break;case "_IX_ATHOME":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='athome']").css({top:t+39,left:parseInt(l-306)});break;case "_IX_COVER":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='cover']").css({top:t-
190,left:l+272});break;case "_IX_MENUS_MYP":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='hdrmn_myp']").css({top:t+54,left:l-9});break;case "_IX_MENUS_MYT":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='hdrmn_myt']").css({top:t+54,left:l-9});break;case "_IX_MENUS_FAV":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='hdrmn_fav']").css({top:t+
54+"px",left:l-9+"px"});break;case "_IX_HDRSTATS":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='hdrstats']").css({top:t+87,left:l+182});break;case "_IX_BRAIN":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='brain']").css({top:t-3,left:l-382});break;case "_IX_ADD_IN_IML_FRD":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left-371-8;l=$(".jb-tqr-fry-bx-bmx[data-target='iml_addin_frd']").css({top:t,
left:l});break;case "_IX_ADD_IN_IML_SOD":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left-371-8;l=$(".jb-tqr-fry-bx-bmx[data-target='iml_addin_sod']").css({top:t,left:l});break;case "_IX_ADD_IN_TRD":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left-371-8;l=$(".jb-tqr-fry-bx-bmx[data-target='iml_addin_trd']").css({top:t,left:l});break;case "_IX_TLKBRD":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='tlkbrd']").css({top:t+
1,left:l+383});break;case "_IX_LASTA":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='lasta']").css({top:t-236,left:l-0});break;case "_IX_ASDBIO":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='asdbio']").css({top:t+9,left:l-380});break;case "_IX_ASDSTATS":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='asdstats']").css({top:t+
13,left:l-380});break;case "_IX_ASDAPPS":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=$(".jb-tqr-fry-bx-bmx[data-target='asdapps']").css({top:t+18,left:l-381});break;case "_IX_TIA":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top+$rs.height()+6+3;l=$rs.offset().left+$rs.width()/2-20+2;$(".jb-tqr-fry-bx-bmx[data-target='tia']").css({top:t,left:l});break;case "_IX_THEND":break;case "_IX_START":$rs=$(_f_Gdf().tab_index[ix].rs);t=$rs.offset().top;l=$rs.offset().left;l=
$(".jb-tqr-fdry-invit-bmx").css({top:t+43,left:parseInt(l-333)});break;default:break}}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_CmfrtOffset=function(i){try{if(KgbLib_CheckNullity(i))return;var wpt=$(window).scrollTop();switch(i){case "_IX_HOME":case "_IX_NEWSFEED":case "_IX_NOTIFICATION":case "_IX_FRDCENTER":case "_IX_USERBOX":case "_IX_USERBOX":case "_IX_PFLPIC":case "_IX_ATHOME":case "_IX_TIA":if(wpt>=215)$("html, body").animate({scrollTop:"0px"});break;case "_IX_COVER":if(wpt>=
155)$("html, body").animate({scrollTop:"80px"});break;case "_IX_MENUS_MYP":case "_IX_MENUS_MYT":case "_IX_MENUS_FAV":if($(window).height()<640|(wpt<200||wpt>=685))$("html, body").animate({scrollTop:"280px"});break;case "_IX_HDRSTATS":if($(window).height()<340|($(window).height()<730&&wpt>640||wpt<200||wpt>=685))$("html, body").animate({scrollTop:"280px"});break;case "_IX_BRAIN":case "_IX_ADD_IN_IML_FRD":case "_IX_ADD_IN_IML_SOD":case "_IX_ADD_IN_TRD":if($(window).height()<640|wpt<200||wpt>=755)$("html, body").animate({scrollTop:"700px"});
break;case "_IX_TLKBRD":case "_IX_LASTA":if($(window).height()<640|(wpt<200||wpt>=685))$("html, body").animate({scrollTop:"280px"});break;case "_IX_ASDBIO":if($(window).height()<415|wpt>160)$("html, body").animate({scrollTop:"0px"});break;case "_IX_ASDSTATS":if($(window).height()<580|wpt>285)$("html, body").animate({scrollTop:"150px"});break;case "_IX_ASDAPPS":if($(window).height()<700|wpt>=450)$("html, body").animate({scrollTop:"360px"});break;case "_IX_START":$("html, body").animate({scrollTop:"0px"});
break;default:break}}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Vw_ShPnl=function(sh,wto){try{if((KgbLib_CheckNullity(sh)||sh===false)&&wto===true)_f_Vw_ShTips();if(sh)$(".jb-tqr-fry-hq-mx").switchClass("state-sleeping","state-wakeup");else $(".jb-tqr-fry-hq-mx").switchClass("state-wakeup","state-sleeping")}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};var _f_Vw_ShTips=function(sh,tgt){try{if(sh===true){$(".jb-tqr-fry-bx-bmx").not("[data-index='"+tgt+"']").stop(true,true).fadeOut().addClass("this_hide").removeProp("style");
if(!tgt)$(".jb-tqr-fry-bx-bmx").stop(true,true).hide().removeClass("this_hide").fadeIn().removeProp("style");else $(".jb-tqr-fry-bx-bmx[data-index='"+tgt+"']").stop(true,true).hide().removeClass("this_hide").fadeIn()}else if(!tgt)$(".jb-tqr-fry-bx-bmx").stop(true,true).fadeOut(100).addClass("this_hide").removeProp("style")}catch(ex){Kxlib_DebugVars([ex,ex.lineNumber],true)}};$(".jb-tqr-fdry-hq-opt-tgr, .jb-tqr-fdry-invt-start-tgr, .jb-tqr-fdry-invt-strt-alwz, .jb-tqr-fdry-invt-clz-tgr").click(function(e){Kxlib_PreventDefault(e);
_f_Action(this)});_f_Init()}new FSTVST;
