function POSTMAN(ko){var _xhr_plrps_top;var _xhr_plrps_btm;var _sbrps;var _f_Gdf=function(){var ds={"prpi":15500,"drl":["fst","top","btm"]};return ds};var _f_AdjustHInB=function(){var hnb=$(window).height();hnb-=10;$(".jb-pm-sprt").css("height",Kxlib_ToPxUnit(hnb))};var _f_Init=function(a){try{var sp=$(".jb-pm-sprt").data("svskip");if(!KgbLib_CheckNullity(sp)&&sp===1)return;var hnb=$(window).height();var mrg=hnb*-1;mrg=mrg.toString()+"px";$(".jb-pm-sprt").css("margin-top",mrg);$(".jb-pm-sprt").removeClass("this_hide");
$(".jb-pm-mx").removeClass("this_hide");$(".jb-pm-mx").fadeOut();_f_AdjustHInB();if(!KgbLib_CheckNullity(a)&&a)_f_Open()}catch(ex){}};var _f_Sentinel=function(a){try{if(!KgbLib_CheckNullity(a)&&!Kxlib_ObjectChild_Count(a)){Kxlib_DebugVars(["PM : Lock at Sentinel =>>> PARAMS"]);return}else if(a.hasOwnProperty("dir")&&!KgbLib_CheckNullity(a.dir)&&a.dir==="btm"&&$(".jb-pm-mx-odr-tgr").data("lk")===1&&!KgbLib_CheckNullity(_xhr_plrps_btm)){Kxlib_DebugVars(["PM : Lock at Sentinel => XHR_BTM : "+typeof _xhr_plrps_btm+
"; BTN : "+$(".jb-pm-mx-odr-tgr").data("lk")]);return}else if(a.hasOwnProperty("dir")&&!KgbLib_CheckNullity(a.dir)&&(a.dir==="top"||a.dir==="fst")&&!KgbLib_CheckNullity(_xhr_plrps_top)){Kxlib_DebugVars(["PM : Lock at Sentinel => XHR_TOP : "+typeof _xhr_plrps_top]);return}else if(!KgbLib_CheckNullity(plds)|!KgbLib_CheckNullity(rgrs)&&_sbrps){Kxlib_DebugVars(["PM : Lock at Sentinel =>>> REPORT TO SERVER"]);return}var dir=!KgbLib_CheckNullity(a)&&a.hasOwnProperty("dir")&&!KgbLib_CheckNullity(a.dir)&&
$.inArray(a.dir,_f_Gdf().drl)!==-1?a.dir:"top";var rgrs=!KgbLib_CheckNullity(a)&&a.hasOwnProperty("rgrs")&&!KgbLib_CheckNullity(a.rgrs)&&$.isArray(a.rgrs)&&a.rgrs.length?a.rgrs:null;var plds=!KgbLib_CheckNullity(a)&&a.hasOwnProperty("plds")&&!KgbLib_CheckNullity(a.plds)&&$.isArray(a.plds)&&a.plds.length?a.plds:null;var fm;if(dir.toLowerCase()==="top")if(!$(".jb-pm-mdl-mx").length)dir="fst";else{var rf=Kxlib_GetFirstDomSortedByTimeBy($(".jb-pm-mdl-mx[data-item]"),"data-ptm","FIRST");fm={i:$(rf).data("item"),
t:$(rf).data("ptm")}}else if(dir.toLowerCase()==="btm")if(!$(".jb-pm-mdl-mx").length)dir="fst";else{var rf=Kxlib_GetFirstDomSortedByTimeBy($(".jb-pm-mdl-mx[data-item]"),"data-ptm","LAST");fm={i:$(rf).data("item"),t:$(rf).data("ptm")}}if(!KgbLib_CheckNullity(plds)|!KgbLib_CheckNullity(rgrs))_sbrps=true;if(!(!KgbLib_CheckNullity(a)&&a.hasOwnProperty("isa")&&a.isa===true)&&dir==="btm")$(".jb-pm-mx-odr-tgr").data("lk",1);if(!_f_IsSprtFrmr()&&!_sbrps&&(!KgbLib_CheckNullity(a)&&KgbLib_CheckNullity(a.isa))&&
dir==="btm")_f_TglLdMrSpnr();var s=$("<span/>");_f_Srv_SbPl_Rps(rgrs,plds,dir,fm,s);$(s).on("datasready",function(e,d){if(KgbLib_CheckNullity(d))return;_f_ShwBpr(d.ds,dir);var nd=d.ds;var tsb=_f_ShwRps(nd,dir);if(_f_IsSprtFrmr())_f_VwSigRpt(d.gcn);if(!KgbLib_CheckNullity(tsb)&&Kxlib_ObjectChild_Count(tsb.rgrs)|Kxlib_ObjectChild_Count(tsb.plds)){_f_GoFree(dir,true);_f_Sentinel({rgrs:tsb.rgrs,plds:tsb.plds})}else{Kxlib_DebugVars(["SBRPS 258"]);_f_GoFree(dir)}_f_Spnr(false,"load_more");_f_TglLdMr(true);
return});$(s).on("operended",function(e,d){if(dir==="btm"){$(".jb-pm-mx-odr-tgr").addClass("this_hide");$(".jb-pm-mx-odr-tgr").data("sts","kill");_f_Spnr(false,"load_more")}else if(dir==="fst"){_f_Spnr(false,"body");_f_None(true);_f_TglLdMr(false)}else{_f_Spnr(false,"load_more");_f_TglLdMr(true)}_f_GoFree(dir,true);if(_f_IsSprtFrmr()&&!KgbLib_CheckNullity(d)&&!KgbLib_CheckNullity(d.gcn))_f_VwSigRpt(d.gcn)})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_PlOdr=function(x){try{if(KgbLib_CheckNullity(x))return;
_f_Sentinel({dir:"btm"})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_GoFree=function(dir,isc){try{if(!KgbLib_CheckNullity(dir)&&dir==="btm"){$(".jb-pm-mx-odr-tgr").data("lk",0);_xhr_plrps_btm=null;Kxlib_DebugVars(["PM : GOFREE BTM !"])}else if(!KgbLib_CheckNullity(dir)&&(dir==="top"||dir==="fst")){_xhr_plrps_top=null;Kxlib_DebugVars(["PM : GOFREE TOP !"])}if(typeof isc!=="undefined"&&isc===true){_sbrps=false;Kxlib_DebugVars(["PM : GOFREE SUBMIT !"])}}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};var _f_GoVoid=function(){if(!_f_IsVoid())$(".jb-pm-mx-bd-l-mx").find(".jb-pm-mdl-mx").remove()};var _f_IsVoid=function(){return $(".jb-pm-mx-bd-l-mx").find(".jb-pm-mdl-mx").length?false:true};var _f_IsSprtFrmr=function(){var akx=$(".jb-pm-sprt").data("access");return KgbLib_CheckNullity(akx)|akx===0?true:false};var _f_MrgDs=function(ds){if(KgbLib_CheckNullity(ds))return;try{var nds=[];$.each(ds,function(x,gds){switch(x){case "XRCT":if("UAT_XRCT_AD_oMA"in gds){var arr=
$.map(gds["UAT_XRCT_AD_oMA"],function(el){return el});nds=nds.concat(arr)}break;default:return false}});return nds}catch(ex){}};var _f_ShwBpr=function(d,dr){try{if(!$(".jb-pm-bpr-sprt")|!$(".jb-pm-bpr-sprt").length|KgbLib_CheckNullity(d)|typeof d!=="object"|!Kxlib_ObjectChild_Count(d)|KgbLib_CheckNullity(dr)|dr.toLowerCase()!=="top")return;var nb=Kxlib_ObjectChild_Count(d);$(".jb-pm-bpr-sprt").removeClass("this_hide");var nd=[];var us__=[];$.each(d,function(x,e){if($(".jb-pm-mdl-mx[data-item='"+e.id+
"'").length)return true;if(!us__.length||$.inArray(e.actid,us__)===-1){var u__={"ui":e.actid,"ufn":e.act_ufn,"upsd":e.act_upsd,"uppic":e.act_uppic,"uhref":"/@"+e.act_upsd};nd.push(u__);us__.push(e.actid)}});if(!KgbLib_CheckNullity(nd))_f_ShwBprMdl(nd,nb)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_ShwBprMdl=function(d,enb){try{if(KgbLib_CheckNullity(d)|KgbLib_CheckNullity(enb))return;var m='<div class="pm-bpr-mdl-mx jb-pm-bpr-mdl">';m+='<div class="pm-bpr-mdl-top">';m+=
'<span class="b jb-pm-bpr-nb">'+enb+"</span>";m+='<span class="b">&nbsp;nouvelles</span>';m+="<span>&nbsp;notificatons</span>";m+="</div>";m+='<div class="pm-bpr-mdl-btm">';m+='<ul class="pm-bpr-mdl-u-list-mx jb-pm-bpr-mdl-u-l-mx">';m+="</ul>";m+="</div>";m+="</div>";m=$.parseHTML(m);$.each(d,function(x,ut){var u_="";u_='<li class="pm-bpr-mdl-u-mx jb-pm-bpr-m-u-mx">';u_+='<a class="pm-bpr-mdl-u" title="'+ut.ufn+" - @"+ut.upsd+'">';u_+='<img class="" height="40" src="'+ut.uppic+'" >';u_+="</a>";u_+=
"</li>";u_=$.parseHTML(u_);$(m).find(".jb-pm-bpr-mdl-u-l-mx").append(u_)});$(m).hide().prependTo(".jb-pm-bpr-sprt").fadeIn();setTimeout(function(){$(m).fadeOut().remove()},1E4)}catch(ex){}};var _f_ShwRps=function(d,dir){if(KgbLib_CheckNullity(d))return;try{var inw=_f_IsVoid()?true:false;_f_Spnr(false,"body");_f_None(false);_f_VwRstRpt();if(KgbLib_CheckNullity(dir))dir=_f_IsSprtFrmr()|_f_IsVoid()?"fst":"top";else if($.inArray(dir,_f_Gdf().drl)===-1)return;if(inw&&!_f_IsVoid())_f_GoVoid();var tsb={rgrs:[],
plds:[]};d=dir!=="top"?d:$(d).get().reverse();$.each(d,function(x,rd){if($(".jb-pm-mdl-mx[data-item='"+rd.id+"']")&&$(".jb-pm-mdl-mx[data-item='"+rd.id+"']").length){Kxlib_DebugVars(["PM : NOTIF Exists => "+rd.id]);return}var e=_f_VwPprRpt(rd);e=_f_RbdRpt(e);if(dir==="top")$(".jb-pm-mx-bd-l-mx").prepend(e);else $(".jb-pm-mx-bd-l-mx").append(e);var t__={"i":rd.id,"t":(new Date).getTime()};tsb.rgrs=[];tsb.plds=[]});return tsb}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_RbdRpt=
function(b){try{if(KgbLib_CheckNullity(b))return;$(b).hover(function(e){if(!$(this).hasClass("visited"))_f_VwMdVstd(this,true);else _f_VwMdVstd(this)});$(b).click(function(e){Kxlib_PreventDefault(e);_f_HdlLineClick(this)});$(b).find("a").click(function(e){Kxlib_StopPropagation(e)});return b}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_AutoPushRps=function(){try{if(!KgbLib_CheckNullity(_xhr_plrps_top)|_sbrps){Kxlib_DebugVars(["PM : Lock at >AUTO< => XHR_TOP-FST : "+typeof _xhr_plrps_btm+
"; BTN : "+$(".jb-pm-mx-odr-tgr").data("lk")+"; SBRPS : "+_sbrps]);return}var d__=$(".jb-pm-mdl-mx").length?"top":"fst";_f_Sentinel({dir:d__,isa:true})}catch(ex){}};var _f_GoVstd=function(x){try{if(KgbLib_CheckNullity(x))return;if($(x).find(".jb-pm-mdl-gvstd-hfr").length){$(".jb-pm-mx-odr-tgr").data("lk",1);var h__=$(x).find(".jb-pm-mdl-gvstd-hfr").attr("href");window.location.href=h__}}catch(ex){}};var _f_HdlLineClick=function(x){try{if(KgbLib_CheckNullity(x))return;var $lnmx=$(x).is(".jb-pm-mdl-mx")?
$(x):$(x).closest(".jb-pm-mdl-mx");var thm=$lnmx.data("thm").toString().toUpperCase();var clicable=false,trgtyp;switch(thm){case "XRCT":case "XART_USTG":case "XEVL":clicable=true;trgtyp="ART";break;case "XTSM":case "XTSR":case "XTSL":case "XTST_USTG":clicable=true;trgtyp="TST";break;case "XUREL":break;case "XTRABO":break;default:return}if(clicable&&trgtyp==="ART")(new Unique).OnOpen("psmn",x);else if(clicable&&trgtyp==="TST")require(["r/csam/tkbvwr.csam"],function(Talkboard){var _VWR=new Talkboard;
_VWR.open({model:"AJCA-PSMN",trigger:x,action:"post-react-open"})})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_HndlUstg=function(bdy,us){if(KgbLib_CheckNullity(us)|!(!KgbLib_CheckNullity(bdy)&&typeof bdy==="string"))return;try{var t__;var ustgs=[];$.each(us,function(x,v){var rw__=[];$.map(v,function(e,x){rw__.push(e)});ustgs.push(rw__)});var ps=ustgs&&$.isArray(ustgs[0])?Kxlib_GetColumn(3,ustgs):[ustgs[3]];t__=Kxlib_UsertagFactory(bdy,ps,"tqr-unq-user");t__=Kxlib_SplitByUsertags(t__);
return t__}catch(ex){}};setInterval(function(){_f_AutoPushRps()},_f_Gdf().prpi);var _Ax_Sbpl_rps=Kxlib_GetAjaxRules("PM_SBPL_RPS");var _f_Srv_SbPl_Rps=function(rgrs,plds,dir,fm,s){if(KgbLib_CheckNullity(s)|KgbLib_CheckNullity(dir))return;var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=JSON.parse(d);else{_f_GoFree(dir,true);return}if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_OWNER_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();
break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":break;case "__ERR_VOL_FAILED":break;case "__ERR_VOL_DATAS_MSG":break;case "__ERR_VOL_WRG_DATAS":case "__ERR_VOL_WRG_HACK":break;default:break}_f_GoFree(dir,true);return}else if(d.hasOwnProperty("return"))if(!KgbLib_CheckNullity(d.return)&&d.return.hasOwnProperty("ds")&&d.return.hasOwnProperty("gcn")&&(!KgbLib_CheckNullity(d.return.ds)&&!KgbLib_CheckNullity(d.return.gcn))){rds=[d.return];$(s).trigger("datasready",rds)}else if(!KgbLib_CheckNullity(d.return)&&
d.return.hasOwnProperty("gcn")&&!KgbLib_CheckNullity(d.return.gcn)){rds=[d.return];$(s).trigger("operended",rds)}else $(s).trigger("operended");else{if(!KgbLib_CheckNullity(rgrs)|!KgbLib_CheckNullity(plds))_f_GoFree(dir,true);else _f_GoFree(dir);return}}catch(ex){if(!KgbLib_CheckNullity(rgrs)|!KgbLib_CheckNullity(plds))_f_GoFree(dir,true);else _f_GoFree(dir);return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);_f_GoFree(dir,true);return};var u=document.URL;var toSend={"urqid":_Ax_Sbpl_rps.urqid,
"datas":{"rgrs":rgrs,"plds":plds,"dir":dir,"fm":{i:!KgbLib_CheckNullity(fm)&&fm.hasOwnProperty("i")&&!KgbLib_CheckNullity(fm.i)?fm.i:null,t:!KgbLib_CheckNullity(fm)&&fm.hasOwnProperty("t")&&!KgbLib_CheckNullity(fm.t)?fm.t:null},"curl":u}};xhr__=Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_Sbpl_rps.url,wcrdtl:_Ax_Sbpl_rps.wcrdtl});if(dir.toLowerCase()==="top"||dir.toLowerCase()==="fst")_xhr_plrps_top=xhr__;else _xhr_plrps_btm=xhr__;return xhr__};var _f_None=function(shw){try{if(!$(".jb-pm-mx-bd-list-none-mx")|
!$(".jb-pm-mx-bd-list-none-mx").length)return;if(shw)$(".jb-pm-mx-bd-list-none-mx").removeClass("this_hide");else $(".jb-pm-mx-bd-list-none-mx").addClass("this_hide")}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Spnr=function(shw,scp){try{if(KgbLib_CheckNullity(scp))return;var $spnr;scp=scp.toLowerCase();switch(scp){case "load_more":$spnr=$(".jb-pm-mx-spnr");break;case "body":$spnr=$(".jb-pm-mx-bd-list-spnr-mx");break;default:return}if(!($spnr&&$spnr.length))return;if(shw)$spnr.removeClass("this_hide");
else $spnr.addClass("this_hide")}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_TglLdMr=function(shw){if(!$(".jb-pm-mx-odr-tgr")|!$(".jb-pm-mx-odr-tgr").length)return;if(shw&&$(".jb-pm-mx-odr-tgr").data("sts")!=="kill")$(".jb-pm-mx-odr-tgr").removeClass("this_hide");else $(".jb-pm-mx-odr-tgr").addClass("this_hide")};var _f_TglLdMrSpnr=function(){if(!($(".jb-pm-mx-spnr")&&$(".jb-pm-mx-spnr").length&&($(".jb-pm-mx-odr-tgr")&&$(".jb-pm-mx-odr-tgr").length)))return;if($(".jb-pm-mx-spnr").hasClass("this_hide")&&
$(".jb-pm-mx-odr-tgr").hasClass("this_hide"))return;else if($(".jb-pm-mx-odr-tgr").data("sts")==="kill")$(".jb-pm-mx-odr-tgr").toggleClass("this_hide");else if($(".jb-pm-mx-spnr").hasClass("this_hide")&&!$(".jb-pm-mx-odr-tgr").hasClass("this_hide")){$(".jb-pm-mx-spnr").removeClass("this_hide");$(".jb-pm-mx-odr-tgr").addClass("this_hide")}else if(!$(".jb-pm-mx-spnr").hasClass("this_hide")&&$(".jb-pm-mx-odr-tgr").hasClass("this_hide")){$(".jb-pm-mx-odr-tgr").removeClass("this_hide");$(".jb-pm-mx-spnr").addClass("this_hide")}};
var _f_Open=function(){try{Kxlib_WindOverflow(true);$(".jb-pm-mx").removeClass("this_hide");_f_AdjustHInB();$(".jb-pm-mx").addClass("this_hide");$(".jb-pm-sprt").animate({"margin-top":0},900,function(){$(".jb-pm-mx").hide().removeClass("this_hide").fadeIn().removeAttr("style");$(".jb-pm-sprt").data("access",1);$(".jb-sig-ev-cn").addClass("this_hide");$(".jb-sig-ev-cn").text("");Kxlib_DocTitleSwNb();var a={dir:"",rgrs:[]};if($(".jb-pm-mdl-mx").length){a.dir="top";$.each($(".jb-pm-mdl-mx"),function(x,
ne){var c__=$(ne).data("cache");var rt__=Kxlib_DataCacheToArray(c__)[0][3];if(!KgbLib_CheckNullity(rt__)&&parseInt(rt__)===0){var t__={"i":$(ne).data("item"),"t":(new Date).getTime()};a.rgrs.push(t__)}})}else a.dir="fst";_f_Sentinel(a)})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Close=function(){try{var h=$(window).height();h*=-1;h=h.toString()+"px";$(".jb-pm-sprt").animate({"margin-top":h},750,function(){$(".jb-pm-mx").addClass("this_hide").removeAttr("style");$(".jb-pm-sprt").data("access",
0);Kxlib_WindOverflow()})}catch(ex){}};var _f_VwSigRpt=function(ds){try{if(KgbLib_CheckNullity(ds))return;$.each(ds,function(x,r){switch(r.typ){case "PRT_NOTFY":if(r.cn===0){$(".jb-sig-ev-cn[data-scp='psmn']").addClass("this_hide");$(".jb-sig-ev-cn[data-scp='psmn']").text("");Kxlib_DocTitleSwNb()}else{$(".jb-sig-ev-cn[data-scp='psmn']").removeClass("_pmc_2_1y _pmc_3_1y _pmc_4_1y");if(r.cn.length>1)$(".jb-sig-ev-cn[data-scp='psmn']").addClass("_pmc_"+r.cn.length+"_1y");$(".jb-sig-ev-cn[data-scp='psmn']").text(r.cn);
$(".jb-sig-ev-cn[data-scp='psmn']").removeClass("this_hide");Kxlib_DocTitleSwNb(r.cn)}break;default:return}})}catch(ex){}};var _f_VwRstRpt=function(){$(".jb-sig-ev-cn[data-scp='psmn']").addClass("this_hide");$(".jb-sig-ev-cn[data-scp='psmn']").removeClass("_pmc_2_1y _pmc_3_1y _pmc_4_1y");$(".jb-sig-ev-cn[data-scp='psmn']").text("")};var _f_VwPprRpt=function(d){if(KgbLib_CheckNullity(d))return;try{var at=Kxlib_getDolphinsValue("PM_"+d.wha);var nat="";if($.inArray(d.wha.toUpperCase(),["UAT_XRCT_AD_OMA",
"UAT_XUSTG_ART","UAT_XUSTG_RCT","UAT_XMTRD_NWABO"])!==-1)nat=d.hasOwnProperty("slv_prmlk")&&!KgbLib_CheckNullity(d.slv_prmlk)?Kxlib_DolphinsReplaceDmd(at,"prmlk",d.slv_prmlk):at;else if($.inArray(d.wha.toUpperCase(),["UAT_XEVL_GOEVL_OMA"])!==-1){at=Kxlib_getDolphinsValue("PM_"+d.wha+d.pvw_tab.pvwbody);nat=d.hasOwnProperty("slv_prmlk")&&!KgbLib_CheckNullity(d.slv_prmlk)?Kxlib_DolphinsReplaceDmd(at,"prmlk",d.slv_prmlk):at}else nat=at;var dt=new KxDate(parseInt(d.tm));dt.SetUTC(true);var strtm=dt.WriteDate();
var strtm_hr=dt.getHours()+":"+("0"+dt.getMinutes()).substr(-2);var tm=d.tm===false?0:d.tm;var ptm=d.ptm===false?0:d.ptm;var tm_p=d.tm_pull===false?0:1;var tm_r=d.tm_rgr===false?0:1;var tm_v=d.tm_vstd===false?0:1;var e='<article class="pm-mdl-mx jb-pm-mdl-mx" data-item="'+d.id+'" data-time="'+d.tm+'" data-ptm="'+d.ptm+'" ';e+="data-cache=\"['"+tm+"','"+ptm+"','"+tm_p+"','"+tm_r+"','"+tm_v+"']\" ";e+=" >";e+='<div class="pm-mdl-lt">';e+='<a class="pm-mdl-upic-hf" href="/@'+d.act_upsd+'">';e+='<span class="pm-mdl-upic-i-fade"></span>';
e+='<img class="pm-mdl-upic-img jb-pm-mdl-upic-img" height="40" src="'+d.act_uppic+'" />';e+="</a>";e+="</div>";e+='<div class="pm-mdl-rt">';e+='<span class="pm-mdl-txt jb-pm-mdl-txt">';e+='<a class="pm-mdl-txt-psd" href="/@'+d.act_upsd+'">@'+d.act_upsd+"</a>&nbsp"+nat+"";e+="</span>";if(d.tm_rgr===true)e+='<span class="pm-mdl-vstd-hrf jb-pm-mdl-vstd-hrf" href="javascript:;" title="Vous avez d\u00e9j\u00e0 vu cette notification" alt=""></span>';e+="</div>";e+='<div class="pm-mdl-bt">';e+='<span class="pm-mdl-bt-time-athr">&nbsp;\u00e0&nbsp;'+
strtm_hr+"</span>";e+='<span class="pm-mdl-bt-time" title="">'+strtm+"</span>";e+="</div>";e+='<div class="pm-mdl-prvw-mx jb-mdl-prvw-mx"></div>';e+='<div class="pm-mdl-spcl-icns-mx jb-pm-mdl-spcl-icns-mx"></div>';e+="</article>";e=$.parseHTML(e);switch(d.wha.toUpperCase()){case "UAT_XRCT_AD_OMA":case "UAT_XUSTG_ART":case "UAT_XUSTG_RCT":case "UAT_XUSTG_MEOTSM":case "UAT_XUSTG_MEOTSR":case "UAT_XTSTY_AD_SBOMTBD":case "UAT_XTSTY_TSR_SBOMTSM":case "UAT_XTSTY_TSL_SBOMTSM":var wha__=d.wha.toUpperCase();
var obtp="";if($.inArray(wha__,["UAT_XRCT_AD_OMA","UAT_XUSTG_RCT"])!==-1)obtp="react";else if(wha__==="UAT_XUSTG_ART")obtp="article";else if($.inArray(wha__,["UAT_XUSTG_MEOTSM","UAT_XUSTG_MEOTSR","UAT_XTSTY_AD_SBOMTBD","UAT_XTSTY_TSR_SBOMTSM","UAT_XTSTY_TSL_SBOMTSM"])!==-1)obtp="testy";if(d.hasOwnProperty("pvw_tab")&&!KgbLib_CheckNullity(d.pvw_tab)&&!KgbLib_CheckNullity(d.pvw_tab.pvwbody)){var t__=d.pvw_tab.pvwbody;t__=Kxlib_Decode_After_Encode(t__);var ustgs,hashs;ustgs=d.pvw_tab.hasOwnProperty("ustgs")&&
!KgbLib_CheckNullity(d.pvw_tab.ustgs)&&Kxlib_ObjectChild_Count(d.pvw_tab.ustgs)?d.pvw_tab.ustgs:null;hashs=d.pvw_tab.hasOwnProperty("hashs")&&!KgbLib_CheckNullity(d.pvw_tab.hashs)&&Kxlib_ObjectChild_Count(d.pvw_tab.hashs)?d.pvw_tab.hashs:null;var rtxt=Kxlib_TextEmpow(t__,ustgs,hashs,null,{emoji:{"size":36,"size_css":18,"position_y":3},wrap_text:true});$(rtxt).addClass("pm-mdl-prvw jb-mdl-prvw").data("obtype",obtp).attr("data-obtype",obtp);$(e).find(".jb-mdl-prvw-mx").text("").append(rtxt)}if(obtp===
"testy")$(e).data("subj-ajcache",JSON.stringify(d.xdatas));var ai__=at__="";switch(wha__){case "UAT_XTSTY_AD_SBOMTBD":ai__=d.mstid;break;case "UAT_XRCT_AD_OMA":case "UAT_XUSTG_ART":ai__=d.slvid;at__=d.pvw_tab.time;break;case "UAT_XUSTG_MEOTSM":case "UAT_XTSTY_TSL_SBOMTSM":case "UAT_XTSTY_TSR_SBOMTSM":ai__=d.slvid;break;case "UAT_XUSTG_RCT":ai__=d.slvl1id;at__=d.pvw_tab.time;break;case "UAT_XUSTG_MEOTSR":ai__=d.slvl1id;break;default:break}$(e).data("ai",ai__).attr("data-ai",ai__);if(at__)$(e).data("at",
at__).attr("data-at",at__);break;case "UAT_XEVL_GOEVL_OMA":$(e).data("ai",d.slvid).attr("data-ai",d.slvid);$(e).data("at",d.pvw_tab.time).attr("data-at",d.pvw_tab.time);break;case "UAT_XREL_NWAB":case "UAT_XMTRD_NWABO":$(e).data("ai",null);break;default:return}if(tm_v===1)$(e).addClass("visited");if(tm_r===1)$(e).addClass("read");if(d.cnrd===false){var dolcd=obtp==="testy"?"PM_XTRA_TST_DNY_AKX_LCK_TLE":"PM_XTRA_ART_DNY_AKX_LCK_TLE";var ik=$("<span/>",{class:"pm-mdl-spcl-icn","data-type":"art_deny",
title:Kxlib_getDolphinsValue(dolcd)}).append(function(){var $t__=$("<i/>",{class:"fa fa-lock"});return $t__});$(e).find(".jb-pm-mdl-spcl-icns-mx").append(ik)}var icn;switch(d.wha.toUpperCase()){case "UAT_XRCT_AD_OMA":icn="XRCT";break;case "UAT_XUSTG_ART":case "UAT_XUSTG_RCT":icn="XART_USTG";break;case "UAT_XUSTG_MEOTSM":case "UAT_XUSTG_MEOTSR":icn="XTST_USTG";break;case "UAT_XEVL_GOEVL_OMA":icn="XEVL";break;case "UAT_XTSTY_AD_SBOMTBD":icn="XTSM";break;case "UAT_XTSTY_TSR_SBOMTSM":icn="XTSR";break;
case "UAT_XTSTY_TSL_SBOMTSM":icn="XTSL";break;case "UAT_XREL_NWAB":icn="XUREL";break;case "UAT_XMTRD_NWABO":icn="XTRABO";break;default:break}$(e).attr("data-thm",icn);return e}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_VwMdVstd=function(x,shw){if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x))|!$(x).length)return;if(!KgbLib_CheckNullity(shw))$(x).addClass("visited");else $(x).removeClass("visited")};_f_Init();$(".jb-pm-close").click(function(e){Kxlib_PreventDefault(e);
_f_Close()});$(".jb-global-nav-elt[data-target=pm]").hover(function(e){$(this).find(".menu-std").addClass("this_hide");$(this).find(".menu-hvr").removeClass("this_hide")},function(){$(this).find(".menu-hvr").addClass("this_hide");$(this).find(".menu-std").removeClass("this_hide")});$(".jb-global-nav-elt[data-target='pm']").click(function(e){Kxlib_PreventDefault(e);_f_Open()});$(".jb-pm-mdl-mx").hover(function(e){if(!$(this).hasClass("visited"))_f_VwMdVstd(this,true);else _f_VwMdVstd(this)});$(".jb-pm-mx-odr-tgr").click(function(e){Kxlib_PreventDefault(e);
_f_PlOdr(this)})}new POSTMAN;
