function SRHBOX(){var gt=this;var _xhr_srh;var _f_NoOne=function(scp){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-asd-sr-bdy":".jb-srh-hy-rslt-mx";var cn=$(b).find(".jb-srh-rslt-mdl").length;if(cn)$(b).find(".jb-srh-no1e").addClass("this_hide");else $(b).find(".jb-srh-no1e").removeClass("this_hide")};var _f_Gdf=function(){var dp={"at":["fil_menu","fil_datas","smr"],"fil_mn":["fil_mn_pfl","fil_mn_trd"],"fil_cat":["at","kw","pop","wn"],"qsp":["min","hvy"],"wtt":370};return dp};var _f_CkRqBas=
function(x){var a=$(x).data("action"),sc=$(x).data("qsp");if(KgbLib_CheckNullity(a)|KgbLib_CheckNullity(sc))return;if($.inArray(a,_f_Gdf().at)===-1)return;if($.inArray(sc,_f_Gdf().qsp)===-1)return;return{"a":a,"s":sc}};var _f_SwMn=function(x,icm){if(KgbLib_CheckNullity(x))return;var t=$(x).data("target"),sc=$(x).data("qsp");var b=sc==="min"?".jb-srh-asd-b":".jb-srh-hvy-b";_f_SwMr(sc);if(sc==="min"){var ldt=$(b).find(".jb-srh-rslt-list").data("dt");if(!ldt)return;var nldt=ldt==="pf"?"tr":"pf";$(b).find(".jb-srh-rslt-list").data("dt",
nldt);$(".jb-asd-sr-bdy-rlist").children().not(".jb-asd-sr-bdy-nvd").remove();$("#asd-srch-max").find(".jb-asd-sr-hdr").toggleClass("tr",250);$("#asd-srch-max").find(".jb-asd-sr-hdr").toggleClass("pfl",250);$("#asd-srch-max").find(".jb-srh-swh-mn[data-target='fil_mn_pfl']").toggleClass("this_hide");$("#asd-srch-max").find(".jb-srh-swh-mn[data-target='fil_mn_trd']").toggleClass("this_hide");Kxlib_getDolphinsValue("SRH_IPT_PLH_TRD");var tx=t==="fil_mn_pfl"?Kxlib_getDolphinsValue("SRH_IPT_PLH_PFL"):
Kxlib_getDolphinsValue("SRH_IPT_PLH_TRD");$("#asd-srch-max").find(".jb-srch-ipt").attr("placeholder",tx);var itg=$("#asd-srch-max").find(".jb-srch-ipt").data("target")==="fil_mn_pfl"?"fil_mn_trd":"fil_mn_pfl";$("#asd-srch-max").find(".jb-srch-ipt").data("target",itg);var t__=$(".jb-asd-sr-jump-tgr").data("action")==="jump_account"?"jump_trend":"jump_account";$(".jb-asd-sr-jump-tgr").data("action",t__)}else{if($(x).is(".jb-srh-swh-mn.focus")&&!icm)return;var fff=$(x).data("target")==="fil_mn_pfl"?
"pf":"tr";var bbb=$(".jb-srh-hy-ctr-r-mx").hasClass("pfl")?"pf":"tr";if(fff!==bbb){$(b).find(".jb-srh-hy-ctr-r-mx").toggleClass("tr",250);$(b).find(".jb-srh-hy-ctr-r-mx").toggleClass("pfl",250)}if($(".jb-srh-hy-fil").length){if(!$(x).is(".jb-srh-swh-mn.focus")){var tr=$(".jb-srh-hy-fil").first().data("target")==="fil_mn_pfl"?"fil_mn_trd":"fil_mn_pfl";$(".jb-srh-hy-fil").data("target",tr)}}else return;var ldt=$(b).find(".jb-srh-rslt-list").data("dt");if(!ldt)return;var nldt=ldt==="pf"?"tr":"pf";$(b).find(".jb-srh-rslt-list").data("dt",
nldt);$(b).find(".jb-srh-rslt-list").children().remove();if(t!==$(b).find(".jb-srh-swh-mn.focus").data("target"))$(b).find(".jb-srh-swh-mn").toggleClass("focus");Kxlib_getDolphinsValue("SRH_IPT_PLH_TRD");var tx=t==="fil_mn_pfl"?Kxlib_getDolphinsValue("SRH_IPT_PLH_PFL"):Kxlib_getDolphinsValue("SRH_IPT_PLH_TRD");$(b).find(".jb-srch-ipt").attr("placeholder",tx);var itg=$(b).find(".jb-srch-ipt").data("target")==="fil_mn_pfl"?"fil_mn_trd":"fil_mn_pfl";$(b).find(".jb-srch-ipt").data("target",itg)}$(b).find(".jb-srh-rslt-list").data("rng",
1);if(icm){var tb=sc==="min"?".jb-srh-hvy-b":".jb-srh-asd-b";var tqt=$(tb).find(".jb-srch-ipt").val();$(b).find(".jb-srch-ipt").val(tqt);if($(b).find(".jb-srch-ipt").data("target")!==$(x).data("target")){var foo=$(b).find(".jb-srch-ipt").data("target")==="fil_mn_pfl"?"fil_mn_trd":"fil_mn_pfl";$(b).find(".jb-srch-ipt").data("target",foo)}var tlt=$(x).data("target")==="fil_mn_pfl"?"pf":"tr";if($(b).find(".jb-srh-rslt-list").data("dt")!==tlt){var bar=$(b).find(".jb-srh-rslt-list").data("dt")==="pf"?
"tr":"pf";$(b).find(".jb-srh-rslt-list").data("dt",bar)}}var ipt=$(b).find(".jb-srch-ipt");var qt=$(ipt).val();if(qt.length){var o={"qsp":$(ipt).data("qsp"),"flm":$(ipt).data("target")==="fil_mn_pfl"?"pf":"tr","flc":$(ipt).data("qsp")==="min"?"at":$(".jb-srh-hy-fil.focus").data("obj")};o.rng=_f_GetRng(o.qsp,o.flc);oqt="";_f_SrhTrgr(qt,o)}};var to;var oqt;var _f_CatchQry=function(x){if(KgbLib_CheckNullity(x))return;var wi=_f_Gdf().wtt;if(to)clearTimeout(to);var qt=$(x).val();if(qt.length)to=setTimeout(function(){var o=
{"qsp":$(x).data("qsp"),"flm":$(x).data("target")==="fil_mn_pfl"?"pf":"tr","flc":$(x).data("qsp")==="min"?"at":$(".jb-srh-hy-fil.focus").data("obj")};o.rng=_f_GetRng(o.qsp,o.flc);_f_SrhTrgr(qt,o)},wi);else{oqt="";var qsp=$(x).data("qsp");_f_HidMr(qsp);_f_HidLdr(qsp);_f_WpSrhRes(qsp);_f_NoOne(qsp)}};var _f_SrhTrgr=function(qt,o,imr){try{if(KgbLib_CheckNullity(qt)|KgbLib_CheckNullity(o))return;if(qt===oqt)return false;var s=$("<span/>");oqt=qt;_f_HidAWS();_f_HidMr(o.qsp);_f_HidNoOne(o.qsp);_f_Srv_SrhTrgr(qt,
o.qsp,o.flm,o.flc,o.rng,s);if(!imr)_f_WpSrhRes(o.qsp);_f_ShwLdr(o.qsp,imr);$(s).on("datasready",function(e,d){if(KgbLib_CheckNullity(d))return;if(KgbLib_CheckNullity(_xhr_srh)){$(".jb-srch-ipt").val("");oqt="";var scp="min";_f_ShwAWS();_f_HidMr(scp);_f_HidLdr(scp);_f_HidNoOne(scp);_f_WpSrhRes(scp);return}_f_ShwRslt(o.flm,d,o.qsp,imr);_f_ShwMr(o.qsp)});$(s).on("operended",function(e){_f_HidMr(o.qsp);_f_HidLdr(o.qsp);_f_WpSrhRes(o.qsp);_f_NoOne(o.qsp)})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],
true)}};var _f_CkResExst=function(s,i){if(KgbLib_CheckNullity(s)|KgbLib_CheckNullity(i))return;var b=s==="min"?".jb-asd-sr-bdy-rlist":".jb-srh-hy-rslt-mx";var cn=$(b).find(".jb-srh-rslt-mdl[data-item="+i+"]").length;if(cn)return true;else return false};var _f_OpenHvy=function(x){if(KgbLib_CheckNullity(x))return;var o={"qsp":$(x).data("qsp"),"flm":$(x).data("target"),"flc":$(x).data("qsp")==="min"?"at":$(".jb-srh-hy-fil.focus").data("obj")};var b=$(x).data("qsp")==="min"?".jb-srh-hvy-b":".jb-srh-asd-b";
var mtg=$(b).find(".jb-srh-swh-mn[data-target='"+o.flm+"']");if(!$(mtg).length)return;$(b).find(".jb-srh-rslt-list").data("rng",1);_f_SwMn($(mtg),true);$(".jb-srh-hvy-sprt").removeClass("this_hide")};var _f_ClzHvy=function(){try{var b=$(".jb-srh-hvy-b");$(".jb-srh-hvy-sprt").addClass("this_hide");$(b).find(".jb-hvy-srch-ipt").val("");if($(".jb-srh-hy-fil.focus").data("obj")!=="kw"){$(".jb-srh-hy-fil.focus").removeClass("focus");$(".jb-srh-hy-fil[data-obj='kw']").addClass("focus")}$(b).find(".jb-srh-rslt-list").data("rng",
1);var mtg=$(b).find(".jb-srh-swh-mn[data-target='fil_mn_pfl']");if(!$(mtg).length)return;_f_SwMn($(mtg));oqt=""}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_FtchDpr=function(x){try{var qt="";if(!$(".jb-hvy-srch-ipt").length||!$(".jb-hvy-srch-ipt").val().length)return;qt=$(".jb-hvy-srch-ipt").val();var s="hvy";var c=$(".jb-srh-hy-fil.focus").data("obj");var r=$(".jb-srh-hvy-b").find(".jb-srh-rslt-list").data("rng");r+=1;$(".jb-srh-hvy-b").find(".jb-srh-rslt-list").data("rng",
r);var o={"qsp":s,"flm":$(".jb-srh-swh-mn.focus").data("target")==="fil_mn_pfl"?"pf":"tr","flc":c};o.rng=_f_GetRng(s,c);oqt="";_f_SrhTrgr(qt,o,true)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_GoFilt=function(x){if(KgbLib_CheckNullity(x))return;try{if(!$(".jb-srh-hy-fil.focus").length||$(".jb-srh-hy-fil.focus").length>1)return;else if(!$(x).is(".jb-srh-hy-fil.focus")){$(".jb-srh-hy-fil.focus").toggleClass("focus");$(x).toggleClass("focus")}$(".jb-srh-hvy-b").find(".jb-srh-rslt-list").data("rng",
1);var o={"qsp":$(x).data("qsp"),"flm":$(x).data("target")==="fil_mn_pfl"?"pf":"tr","flc":$(x).data("obj")};o.rng=_f_GetRng(o.qsp,o.flc);var qt=$(".jb-hvy-srch-ipt").val();if(qt.length){oqt="";_f_SrhTrgr(qt,o)}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_GetRng=function(s,c){if(KgbLib_CheckNullity(s)|KgbLib_CheckNullity(c))return;var r;if(c==="at")r=c+"_rng_1";else{var b=s==="min"?".jb-srh-asd-b":".jb-srh-hvy-b";var tr=$(b).find(".jb-srh-rslt-list").data("rng");var rn=
tr?tr:1;r=c+"_rng_"+rn}return r};var _f_CkGnOp=function(x){if(KgbLib_CheckNullity(x))return;try{var p=_f_CkRqBas(x);if(!p)return;switch(p.a.toString().toLowerCase()){case "fil_menu":_f_SwMn(x);break;case "smr":if($(x).data("qsp")==="min")_f_OpenHvy(x);else _f_FtchDpr(x);break;case "fil_datas":_f_GoFilt(x);break;case "clz":_f_ClzHvy();break;default:return}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Shbx_Jump=function(x){if(KgbLib_CheckNullity(x)|!$(x).length|KgbLib_CheckNullity($(x).data("action")))return;
try{if($(x).data("lk")===1)return;_f_JmpSpnr(x,true);var a=$(x).data("action"),o__;switch(a){case "jump_account":o__={object:"account",url:Document.URL};break;case "jump_trend":o__={object:"trend",url:Document.URL};break;default:return}var s=$("<span/>");_f_Srv_SrhJmp(obj,url,s);$(s).on("datasready",function(e,d){})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _Ax_SrhTrgr=Kxlib_GetAjaxRules("TQR_SEARCH");var _f_Srv_SrhTrgr=function(qt,qsp,flm,flc,rng,s){if(KgbLib_CheckNullity(qt)|
KgbLib_CheckNullity(qsp)|KgbLib_CheckNullity(flm)|KgbLib_CheckNullity(rng)|KgbLib_CheckNullity(s))return;var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_OWNER_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":Kxlib_AJAX_HandleDeny();
break;case "__ERR_VOL_FAILED":Kxlib_AJAX_HandleFailed();break;case "__ERR_VOL_DATAS_MISG":Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");break;case "__ERR_VOL_WRG_DATAS":return;case "__ERR_VOL_WRG_HACK":return;default:Kxlib_AJAX_HandleFailed();return}return}else if(d.hasOwnProperty("return"))if(!KgbLib_CheckNullity(d.return)){rds=[d.return];$(s).trigger("datasready",rds)}else $(s).trigger("operended");else return}catch(e){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return}};var onerror=function(a,
b,c){Kxlib_AjaxGblOnErr(a,b);return};var toSend={"urqid":_Ax_SrhTrgr.urqid,"datas":{"qt":qt,"qsp":qsp,"flm":flm,"flc":flc,"rng":rng}};_xhr_srh=Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_SrhTrgr.url,wcrdtl:_Ax_SrhTrgr.wcrdtl})};var _Ax_SrhJmp=Kxlib_GetAjaxRules("TQR_SRH_JMP");var _f_Srv_SrhJmp=function(qt,qsp,flm,flc,rng,s){if(KgbLib_CheckNullity(qt)|KgbLib_CheckNullity(qsp)|KgbLib_CheckNullity(flm)|KgbLib_CheckNullity(rng)|KgbLib_CheckNullity(s))return;var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=
JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_OWNER_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":Kxlib_AJAX_HandleDeny();break;case "__ERR_VOL_FAILED":Kxlib_AJAX_HandleFailed();break;case "__ERR_VOL_DATAS_MISG":Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");
break;case "__ERR_VOL_WRG_DATAS":return;case "__ERR_VOL_WRG_HACK":return;break;default:Kxlib_AJAX_HandleFailed();return;break}return}else if(d.hasOwnProperty("return"))if(!KgbLib_CheckNullity(d.return)){rds=[d.return];$(s).trigger("datasready",rds)}else $(s).trigger("operended");else return}catch(e){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);return};var toSend={"urqid":_Ax_SrhTrgr.urqid,"datas":{"qt":qt,"qsp":qsp,"flm":flm,"flc":flc,
"rng":rng}};Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_SrhTrgr.url,wcrdtl:_Ax_SrhTrgr.wcrdtl})};var _f_ShwRslt=function(rt,rd,scp,imr){if(KgbLib_CheckNullity(rt)|KgbLib_CheckNullity(rd)|KgbLib_CheckNullity(scp))return;_f_HidLdr(scp);_f_HidNoOne(scp);if(!imr)_f_WpSrhRes(scp);var b=scp==="min"?$(".jb-srh-asd-b").find(".jb-srh-rslt-list"):$(".jb-srh-hvy-b").find(".jb-srh-rslt-list");var e;$.each(rd,function(x,v){if(rt==="pf"){if(_f_CkResExst(scp,v.upsd))return;var md=$(b).data("dt");
if(rt!==md)return;e=_f_PprPflMdl(v,scp);$(e).hide().appendTo(b).fadeIn()}else{if(_f_CkResExst(scp,v.i))return;var md=$(b).data("dt");if(rt!==md)return;e=_f_PprTrdMdl(v,scp);$(e).hide().appendTo(b).fadeIn()}});return true};this._PrepareFullMdl=function(){};var _f_WpSrhRes=function(scp){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-asd-sr-bdy":".jb-srh-hy-rslt-mx";$(b).find(".jb-srh-rslt-list").find(".jb-srh-rslt-mdl").remove()};var _f_WipeSrhBar=function(x){try{if(KgbLib_CheckNullity(x))return;
if(!KgbLib_CheckNullity(_xhr_srh)){_xhr_srh.abort();_xhr_srh=null}$(x).val("");oqt="";var scp=$(x).data("qsp");_f_ShwAWS();_f_HidMr(scp);_f_HidLdr(scp);_f_HidNoOne(scp);_f_WpSrhRes(scp)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_ShwLdr=function(scp,imr){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-asd-sr-bdy":".jb-srh-hy-rslt-mx";var ldg=$(b).find(".jb-srh-ldg");var lt=$(b).find(".jb-srh-rslt-list");if(imr){$(ldg).parent().insertAfter(lt);$(ldg).parent().addClass("bt")}else{$(ldg).parent().insertBefore(lt);
$(ldg).parent().removeClass("bt")}$(ldg).removeClass("this_hide")};var _f_HidLdr=function(scp){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-asd-sr-bdy":".jb-srh-hy-rslt-mx";$(b).find(".jb-srh-ldg").addClass("this_hide")};var _f_SwMr=function(scp){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-srh-asd-b":".jb-srh-hvy-b";var x=$(b).find(".jb-srh-rslt-mr");var t=$(x).data("target");if(t){var nt=t==="fil_mn_pfl"?"fil_mn_trd":"fil_mn_pfl";$(x).data("target",nt)}};var _f_ShwMr=function(scp){if(KgbLib_CheckNullity(scp))return;
var b=scp==="min"?".jb-srh-asd-b":".jb-srh-hvy-b";$(b).find(".jb-srh-rslt-mr").removeClass("this_hide")};var _f_HidMr=function(scp){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-srh-asd-b":".jb-srh-hvy-b";$(b).find(".jb-srh-rslt-mr").addClass("this_hide")};var _f_HidNoOne=function(scp){if(KgbLib_CheckNullity(scp))return;var b=scp==="min"?".jb-asd-sr-bdy":".jb-srh-hy-rslt-mx";$(b).find(".jb-srh-no1e").addClass("this_hide")};var _f_ShwAWS=function(){$(".jb-asd-sr-bdy-nvd").removeClass("this_hide")};
var _f_HidAWS=function(){$(".jb-asd-sr-bdy-nvd").addClass("this_hide")};var _f_PprPflMdl=function(d,s){if(KgbLib_CheckNullity(d)|KgbLib_CheckNullity(s))return;var fn=Kxlib_Decode_After_Encode(d.ufn);var psd=Kxlib_Decode_After_Encode(d.upsd);var ur="";if(d.hasOwnProperty("urel")&&!KgbLib_CheckNullity(d.urel))switch(d.urel){case "nn":ur="";break;case "fl":ur=Kxlib_getDolphinsValue("REL_FL");break;case "df":ur=Kxlib_getDolphinsValue("REL_DFL1");break;case "fr":ur=Kxlib_getDolphinsValue("REL_FR");break;
default:break}var hrf="/"+d.upsd;var cl__="";if(d.hasOwnProperty("acctdl")&&!KgbLib_CheckNullity(d.acctdl))if(parseInt(d.acctdl)===1){hrf="javascript:;";cl__="gone"}if(s==="min"){var e='<div class="asd-sr-min-pfl-mdl jb-srh-rslt-mdl" data-item="'+d.upsd+'">';e+='<div class="asd-sr-min-ugrp">';e+='<a class="asd-sr-min-ugp-mn '+cl__+'" href="'+hrf+'" >';e+='<span class="asd-sr-min-ugp-i-fade"></span>';e+='<img class="asd-sr-min-ugp-img" src="'+d.uppic+'" width="60" />';e+='<span class="asd-sr-min-ugp-psd">@'+
psd+"</span>";e+="</a>";e+='<div class="asd-sr-min-ug-fn">';e+='<span class="asd-sr-min-ug-fn">'+fn+"</span>";e+="</div>";e+="</div>";e+='<div class="asd-sr-min-urel">';e+='<span class="">'+ur+"</span>";e+="</div>";e+="</div>";e=$.parseHTML(e)}return e};var _f_PprTrdMdl=function(d,s){if(KgbLib_CheckNullity(d)|KgbLib_CheckNullity(s))return;var hrf=d.hrf;var cl__="";if(d.hasOwnProperty("acctdl")&&!KgbLib_CheckNullity(d.acctdl))if(parseInt(d.acctdl)===1){hrf="javascript:;";cl__="gone"}if(s==="min"){var tle=
Kxlib_Decode_After_Encode(d.tle);var e='<div class="asd-sr-min-trd-mdl jb-srh-rslt-mdl" data-item="'+d.i+'">';e+='<div class="asd-sr-m-t-mdl-top clearfix2">';e+='<div class="asd-sr-m-t-mdl-t-rgt">';e+='<a class="asd-sr-m-t-mdl-tr-tle '+cl__+'" href="'+hrf+'"></a>';e+="</div>";e+='<div class="asd-sr-m-t-mdl-tr-dsc">'+d.dsc+"</div>";e+="</div>";e+='<div class="asd-sr-m-t-mdl-bot clearfix2">';e+='<span class="asd-sr-m-t-mdl-b-fol">';e+='<span class="asd-sr-m-t-mdl-b-fol-nb">'+d.fnb+"</span>";e+='<span class="asd-sr-m-t-mdl-b-fol-lib">Abo.</span>';
e+="</span>";e+='<span class="asd-sr-m-t-mdl-b-pst">';e+='<span class="asd-sr-m-t-mdl-b-pst-nb">'+d.pnb+"</span>";e+='<span class="asd-sr-m-t-mdl-b-pst-lib">Posts</span>';e+="</span>";e+="</div>";e+="</div>";e=$.parseHTML(e);$(e).find(".asd-sr-m-t-mdl-tr-tle").text(tle)}else{var tle=Kxlib_Decode_After_Encode(d.tle);var dsc=Kxlib_Decode_After_Encode(d.dsc);var e='<div class="srh-hy-tr-mdl-mx jb-srh-rslt-mdl" data-item="'+d.i+'">';e+='<div class="srh-hy-tr-mdl-top clearfix2">';e+='<div class="srh-hy-tr-lg">';
e+='<img src="" />';e+="</div>";e+='<div class="srh-hy-tr-spcs-mx">';e+='<div class="srh-hy-tr-mdl-spcs-mn-l">';e+='<div class="srh-hy-tr-mdl-s-mn-tle-bx">';e+='<a class="srh-hy-tr-mdl-s-mn-tle" href="'+d.hrf+'"></a>';e+="</div>";e+='<div class="clearfix2">';if(d.rl==="me"){e+='<div class="srh-hy-tr-mdl-spcs-mn-r">';e+='<span class="srh-hy-tr-mdl-spcs-cnx">';e+='<img width="22" height="22" src="'+Kxlib_GetExtFileURL("sys_url_img","r/tr_cntd.png")+" />";e+="<span>Connect\u00e9</span>";e+="</span>";
e+="</div>"}e+='<p class="srh-hy-tr-mdl-s-mn-desc">'+dsc+"</p>";e+="</div>";e+="</div>";e+="</div>";e+="</div>";e+='<div class="srh-hy-tr-mdl-bot">';e+='<a class="srh-hy-tr-mdl-s-x-psd" href="/@'+d.op+'" title="'+d.of+'">@'+d.op+"</a>";e+='<span class="srh-hy-tr-mdl-s-x-pst-grp">';e+='<span class="srh-hy-tr-mdl-s-x-pp-nb">'+d.pnb+"</span>";e+='<span class="srh-hy-tr-mdl-s-x-pp-lib">Posts</span>';e+="</span>";e+='<span class="srh-hy-tr-mdl-s-x-fol-grp">';e+='<span class="srh-hy-tr-mdl-s-x-fp-nb">'+
d.fnb+"</span>";e+='<span class="srh-hy-tr-mdl-s-x-fp-lib">Abonn\u00e9s</span>';e+="</span>";e+="</div>";e+="</div>";e=$.parseHTML(e);$(e).find(".srh-hy-tr-mdl-s-mn-tle").text(tle)}return e};var _f_JmpSpnr=function(x,shw){if(KgbLib_CheckNullity(x)|!$(x).find(".jb-asd-sr-j-txt")|KgbLib_CheckNullity($(x).find(".jb-asd-sr-j-txt").length))return;if(shw){$(x).find(".jb-asd-sr-j-txt").addClass("this_hide");$(x).addClass("loading");$(x).find(".jb-asd-sr-j-ldg").removeClass("this_hide")}else{$(x).find(".jb-asd-sr-j-ldg").removeClass("this_hide");
$(x).find(".jb-asd-sr-j-txt").removeClass("this_hide");$(x).removeClass("loading")}};$(".jb-asd-sr-ipt-rst").click(function(e){Kxlib_PreventDefault(e);_f_WipeSrhBar($(".jb-asd-srch-ipt"))});$(".jb-srh-hy-clz").click(function(e){Kxlib_PreventDefault(e);_f_ClzHvy()});$(".jb-srh-swh-mn").click(function(e){Kxlib_PreventDefault(e);_f_CkGnOp(this)});$(".jb-srh-hy-fil").click(function(e){Kxlib_PreventDefault(e);_f_CkGnOp(this)});$(".jb-srch-ipt").keyup(function(){_f_CatchQry(this)});$(".jb-asd-srch-ipt").hover(function(){$(".asd-sr-hdr-ipt-wrap").addClass("hover");
$(".jb-asd-sr-ipt-rst").addClass("hover")},function(){if(!$(this).is(":focus")){$(".asd-sr-hdr-ipt-wrap").removeClass("focus");$(".jb-asd-sr-ipt-rst").removeClass("focus")}$(".asd-sr-hdr-ipt-wrap").removeClass("hover");$(".jb-asd-sr-ipt-rst").removeClass("hover")});$(".jb-asd-srch-ipt").focus(function(){$(".asd-sr-hdr-ipt-wrap").addClass("focus");$(".jb-asd-sr-ipt-rst").addClass("focus")});$(".jb-asd-srch-ipt").blur(function(){$(".asd-sr-hdr-ipt-wrap").removeClass("focus");$(".jb-asd-sr-ipt-rst").removeClass("focus");
if(!$(this).is(":hover")){$(".asd-sr-hdr-ipt-wrap").removeClass("hover");$(".jb-asd-sr-ipt-rst").removeClass("hover")}});$(".jb-asd-sr-jump-tgr").click(function(e){Kxlib_PreventDefault(e);_f_Shbx_Jump(this)})}new SRHBOX;
