function TESTY(){this.triggerObj;this.overlayIdSel="#write_testy_max";this.targetBloc="#brain_list_gbck_r";this.yellowActionCl="action_a_gbck";this.actionBtnSl=".action_a";this.testyFavBdg=".testi_fav";this.confPo=".conf_po";this.confPoTimerSl="#conf_po_timer";this.confPoTimerMax=3;this.ubfurel;this.ubfuid;this.testyBlocId;this.testyType;this.testyIsFav;this.centerVert=function(){var h=$("#write_testy_black").height();var form_h=$("#write_testy_form").height();var top=h/2-form_h;top=top<0?0:top;var topx=
top+"px";$("#write_testy_form").css("top",topx)};this.IsTriggerAuthentic=function(th){$tarsel=$(th);this.testyBlocId=$tarsel.data("target");if(KgbLib_CheckNullity(this.testyBlocId)){Kxlib_DebugVars(["Error : Can't reach target"]);return}this.targetBloc=$tarsel.data("tarbloc");if(KgbLib_CheckNullity(this.targetBloc)){Kxlib_DebugVars(["Error : Can't reach targetBloc"]);return}this.uaction=$tarsel.data("action");if(KgbLib_CheckNullity(this.uaction)){Kxlib_DebugVars(["Error : Can't get access to uaction"]);
return}return 1};this.IsTargetReachableNAuthentic=function(bloc,id){var $o;try{$o=$("#"+bloc+" #"+id);this.bfuElSel="#"+bloc+" #"+id}catch(e){Kxlib_DebugVars(["Can't reach TESTY element !"]);return}var l=$o.html().length;if(!KgbLib_CheckNullity(l)){try{var _bfurel=$o.data("bfurel").toString();var _bfuid=$o.data("author").toString();var _testyType=$o.data("type").toString();var _fav=$o.data("fav")}catch(e){Kxlib_DebugVars(["TESTY defective ! Miss attr : bfurel, bfuid or type"]);return}if(!_bfurel||
!_bfuid||!_testyType||_fav===""){Kxlib_DebugVars(["Error : Element reached is not authentic. Miss bfurel, bfuid, fav, or type"]);return}this.ubfurel=_bfurel;this.ubfuid=_bfuid;this.testyType=_testyType;this.testyIsFav=_fav}return 1};this.TotalReverseTestyReversableChoice=function(o,action,no_rev_txt){var $o=$(o).find(".bind-testyfav-fav");try{if(!no_rev_txt){var _n=$o.data("revs");$o.data("revs",$o.html());$o.html(_n)}if(!KgbLib_CheckNullity(action))$o.data("action",action);$(o).data("fav",0);return 1}catch(e){return}};
this.HandleNewTesty=function(){};this.innerRemoveTesty=function(obj,ans){if(!KgbLib_CheckNullity(ans)){var _id=$(obj).parent().data("target");var $ol=$("#"+_id);window.clearInterval($ol.data("timer"));this.timerID=null;$op=$ol.find(this.confPo);$op.addClass("this_hide");$ol.fadeOut();window.setTimeout(function(){$ol.remove()},1E3)}else{$op=$("#"+this.testyBlocId).find(this.confPo);$op.removeClass("this_hide");var _time=this.confPoTimerMax;var $this=this;var timerID=setInterval(function(){$("#"+$this.testyBlocId).find($this.confPo+
" "+$this.confPoTimerSl+"").html("("+--_time+")");if(_time===-1){window.clearInterval(timerID);$("#"+$this.testyBlocId).find($this.confPo).addClass("this_hide");$this.timerID=null;_time=$this.confPoTimerMax;$("#"+$this.testyBlocId).find($this.confPo+" "+$this.confPoTimerSl+"").html("("+_time+")")}},1E3);$("#"+this.testyBlocId).data("timer",timerID)}};this.HandleDeleteWTesty=function(obj,ans){this.innerRemoveTesty(obj,ans)};this.HandleDeleteWFavTesty=function(){};this.HandlePulloutRTesty=function(obj,
ans){this.innerRemoveTesty(obj,ans)};this.HandlePulloutRFavTesty=function(){};this.HandleFavoriteRTesty=function(){if(this.testyType!=="r"){Kxlib_DebugVars(["ERROR, INCOHERENCE: Testy is not defined as 'r' but the process reached this function !"]);if(KgbLib_ReverseText(this.triggerObj,"revs")!==1)Kxlib_DebugVars(["ERROR: Le contre reverse n'a pas pu \u00eatre ex\u00e9cut\u00e9 !"]);return}if(this.testyIsFav){Kxlib_DebugVars(["ERROR, INCOHERENCE: Testy is already as defined but user wants to fav again !"]);
if(KgbLib_ReverseText(this.triggerObj,"revs")!==1)Kxlib_DebugVars(["ERROR: Le contre reverse n'a pas pu \u00eatre ex\u00e9cut\u00e9 !"]);return}var $ot;try{$ot=$("#"+this.targetBloc).find(".brain_gbkmsg_mdl[favorite]")}catch(e){}$ot.find(this.testyFavBdg).addClass("this_hide");$ot.find(this.actionBtnSl).removeClass("action_a_gbck");this.TotalReverseTestyReversableChoice($ot,"rhana_fav");$ot.removeAttr("favorite");$("#"+this.testyBlocId).find(this.testyFavBdg).removeClass("this_hide");$("#"+this.testyBlocId).find(this.actionBtnSl).addClass("action_a_gbck");
$("#"+this.testyBlocId).data("fav",1);$("#"+this.testyBlocId).attr("favorite","true");this.TotalReverseTestyReversableChoice($("#"+this.testyBlocId),"back_fav",true)};this.HandleUnfavoriteRTesty=function(){var $ot=$("#"+this.testyBlocId);$ot.find(this.testyFavBdg).addClass("this_hide");$ot.find(this.actionBtnSl).removeClass("action_a_gbck");this.TotalReverseTestyReversableChoice($ot,"rhana_fav",true);$ot.removeAttr("favorite")};this.ValidForm=function(){alert("Ici houston")};this.OpenCloseTWOverlay=
function(arg){switch(arg){case "c":$(this.overlayIdSel).addClass("this_hide");break;case "o":this.centerVert();$(this.overlayIdSel).removeClass("this_hide");break}};this.CheckOperation=function(th){if(!this.IsTriggerAuthentic(th)&&1)return;if($(th).hasClass("kgb_el_can_revs"))this.triggerObj=th;if(!this.IsTargetReachableNAuthentic(this.targetBloc,this.testyBlocId)&&1)return;switch(this.uaction){case "back_fav":this.HandleUnfavoriteRTesty();break;case "rhana_fav":this.HandleFavoriteRTesty();break;
case "del_wtesty":this.HandleDeleteWTesty();break;case "po_rtesty":this.HandlePulloutRTesty();break;default:break}};this.Init=function(arg){if(KgbLib_CheckNullity(arg))this.OpenCloseTWOverlay("c");else this.OpenCloseTWOverlay("o")}}
function Testy_Receiver(){var obj=new TESTY;obj.Init();$("#write_testy_black").click(function(e){obj.OpenCloseTWOverlay("c")});$("#write_testy_form_max").click(function(e){e.stopPropagation()});$("#asR_nav_start_writn_a").click(function(){obj.OpenCloseTWOverlay("o")});$("#w_t_f_post").click(function(e){e.preventDefault();obj.HandleNewTesty()});$(".bind-testyfav").click(function(e){e.preventDefault();obj.HandleNewTesty()});$(".conf_po").click(function(e){e.preventDefault();if($(e.target).parent().hasClass("conf_del"))obj.HandleDeleteWTesty(e.target,
true);else obj.HandlePulloutRTesty(e.target,true)});this.Routeur=function(th){if(KgbLib_CheckNullity(th))return;obj.CheckOperation(th)}};
