function WhiteBoardDialog(){this.DialogIsOpen=function(){if($("#stop_playin_wbackgr").length)return!$("#stop_playin_wbackgr").hasClass("this_hide");else return};this.CloseDialog=function(){$("#stop_playin").addClass("this_hide")};this._DisplayBackground=function(){$("#stop_playin").removeClass("this_hide")};this.Dialog=function(v){if(!KgbLib_CheckNullity(v)&&Kxlib_ObjectChild_Count(v)&&!KgbLib_CheckNullity(v.message)&&!KgbLib_CheckNullity(v.redir)){var $ws=$("#stop_playin").find("#stop_playin_wbackgr");
var $bs=$("#stop_playin").find("#stop_playin_blbackgr");if($ws.length){if(!KgbLib_CheckNullity(v.title))$ws.find("#s_p_d_title").removeClass("this_hide").html(v.title);else $ws.find("#s_p_d_title").addClass("this_hide");$ws.find("#s_p_d_msg").html(v.message);if(!KgbLib_CheckNullity(v.fly))switch(v.fly){case "uhome":var $mhs=$ws.find(".s_p_d_ch_redir[data-pg='"+v.fly+"']"),lk="http://www.trenqr.com";$mhs.attr("href",lk);$mhs.removeClass("this_hide");break;case "phome":var $phs=$ws.find(".s_p_d_ch_redir[data-pg='"+
v.fly+"']"),lk="http://www.trenqr.com";$phs.attr("href",lk);$phs.removeClass("this_hide");break;default:$ws.find(".s_p_d_ch_redir").addClass("this_hide");break}else $ws.find(".s_p_d_ch_redir").addClass("this_hide");switch(v.redir){case "reload":$("#s_p_d_ch_valid").attr("href",document.URL);break;case "phome":var lk="http://www.trenqr.com";$("#s_p_d_ch_valid").attr("href",lk);break;default:$("#s_p_d_ch_valid").attr("href",v.redir);break}$ws.removeClass("this_hide");this._DisplayBackground()}else if(!$ws.length&&
$bs.length){$bs.attr("id","stop_playin_wbackgr");$ws=$("#stop_playin").find("#stop_playin_wbackgr");if(!KgbLib_CheckNullity(v.title))$ws.find("#s_p_d_title").removeClass("this_hide").html(v.title);else $ws.find("#s_p_d_title").addClass("this_hide");$ws.find("#s_p_d_msg").html(v.message);if(!KgbLib_CheckNullity(v.fly))switch(v.fly){case "uhome":var $mhs=$ws.find(".s_p_d_ch_redir[data-pg='"+v.fly+"']"),lk="http://www.trenqr.com";$mhs.attr("href",lk);$mhs.removeClass("this_hide");break;case "phome":var $phs=
$ws.find(".s_p_d_ch_redir[data-pg='"+v.fly+"']"),lk="http://www.trenqr.com";$phs.attr("href",lk);$phs.removeClass("this_hide");break;default:$ws.find(".s_p_d_ch_redir").addClass("this_hide");break}else $ws.find(".s_p_d_ch_redir").addClass("this_hide");switch(v.redir){case "reload":$("#s_p_d_ch_valid").attr("href",document.URL);break;case "phome":var lk="http://www.trenqr.com";$("#s_p_d_ch_valid").attr("href",lk);break;default:$("#s_p_d_ch_valid").attr("href",v.redir);break}$ws.removeClass("this_hide");
this._DisplayBackground()}else return}return}}
function BlackBoardDialog(){this._DisplayBackground=function(){$("#stop_playin").removeClass("this_hide")};this.DialogIsOpen=function(){if($("#stop_playin_blbackgr").length)return!$("#stop_playin_blbackgr").hasClass("this_hide");else return};this.CloseDialog=function(){$("#stop_playin").addClass("this_hide")};this.Dialog=function(v){if(!KgbLib_CheckNullity(v)&&Kxlib_ObjectChild_Count(v)&&!KgbLib_CheckNullity(v.message)&&!KgbLib_CheckNullity(v.redir)){var $ws=$("#stop_playin").find("#stop_playin_wbackgr");
var $bs=$("#stop_playin").find("#stop_playin_blbackgr");if($bs.length){if(!KgbLib_CheckNullity(v.title))$bs.find("#s_p_d_title").removeClass("this_hide").html(v.title);else $bs.find("#s_p_d_title").addClass("this_hide");$bs.find("#s_p_d_msg").html(v.message);if(!KgbLib_CheckNullity(v.fly))switch(v.fly){case "uhome":var $mhs=$bs.find(".s_p_d_ch_redir[data-pg='"+v.fly+"']"),lk="http://www.trenqr.com";$mhs.attr("href",lk);$mhs.removeClass("this_hide");break;case "phome":var $phs=$bs.find(".s_p_d_ch_redir[data-pg='"+
v.fly+"']"),lk="http://www.trenqr.com";$phs.attr("href",lk);$phs.removeClass("this_hide");break;default:$bs.find(".s_p_d_ch_redir").addClass("this_hide");break}else $bs.find(".s_p_d_ch_redir").addClass("this_hide");switch(v.redir){case "reload":$("#s_p_d_ch_valid").attr("href",document.URL);break;case "phome":var lk="http://www.trenqr.com";$("#s_p_d_ch_valid").attr("href",lk);break;default:$("#s_p_d_ch_valid").attr("href",v.redir);break}$bs.removeClass("this_hide");this._DisplayBackground()}else if(!$bs.length&&
$ws.length){$ws.attr("id","stop_playin_blbackgr");$bs=$("#stop_playin").find("#stop_playin_blbackgr");if(!KgbLib_CheckNullity(v.title))$bs.find("#s_p_d_title").removeClass("this_hide").html(v.title);else $bs.find("#s_p_d_title").addClass("this_hide");$bs.find("#s_p_d_msg").html(v.message);if(!KgbLib_CheckNullity(v.fly))switch(v.fly){case "uhome":var $mhs=$bs.find(".s_p_d_ch_redir[data-pg='"+v.fly+"']"),lk="http://www.trenqr.com";$mhs.attr("href",lk);$mhs.removeClass("this_hide");break;case "phome":var $phs=
$bs.find(".s_p_d_ch_redir[data-pg='"+v.fly+"']"),lk="http://www.trenqr.com";$phs.attr("href",lk);$phs.removeClass("this_hide");break;default:$bs.find(".s_p_d_ch_redir").addClass("this_hide");break}else $bs.find(".s_p_d_ch_redir").addClass("this_hide");switch(v.redir){case "reload":$("#s_p_d_ch_valid").attr("href",document.URL);break;case "phome":var lk="http://www.trenqr.com";$("#s_p_d_ch_valid").attr("href",lk);break;default:$("#s_p_d_ch_valid").attr("href",v.redir);break}$bs.removeClass("this_hide");
this._DisplayBackground()}else return}return}}(function(){})();
