(function(){var _par=$(".menu-selected").parent();var _par_id=$(".menu-selected").parent().attr("id");switch(_par_id){case "menu-li-post":$(_par).addClass("hover-post");break;case "menu-li-tr":$(_par).addClass("hover-tr");break;case "menu-li-clb":$(_par).addClass("hover-clb");break;default:break}})();
function ACCHDR(){var _FnlImg;var _xhr_dlcvr;var _xhr_chcvr;var _f_GIR=function(){var ir={"ft":["png","jpg","jpeg"],"sz":2621440,"w_min":250,"w_max":5500,"h_min":250,"h_max":5500};return ir};var _f_Action=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).parent().attr("id")))return;var _pid=$(x).parent().attr("id");switch(_pid){case "menu-li-post":$(x).toggleClass("hover-post");break;case "menu-li-tr":$(x).toggleClass("hover-tr");break;default:break}}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};this.CheckOperation=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action");switch(a){case "firstvisit":$(".jb-tqr-fdry-invt-strt-alwz").click();_f_ShwAtHmMns();$(".jb-tmlnr-athm-mn-bmx").data("state","");break}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_AtHmMns=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action");
switch(a){case "open-menu":_f_HdlOpnAtHmMns();break}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_HdlOpnAtHmMns=function(e,x,frc){try{if(frc===false|$(".jb-tmlnr-athm-mn-bmx").data("state")==="activate"){_f_ShwAtHmMns();$(".jb-tmlnr-athm-mn-bmx").data("state","");if(KgbLib_CheckNullity(e)||e.type.toString().toLowerCase()!=="blur"&&e.type.toString().toLowerCase()!=="focusout")$(".jb-tmlnr-hdr-hmbx").blur()}else if(frc===true|KgbLib_CheckNullity($(".jb-tmlnr-athm-mn-bmx").data("state"))|
$(".jb-tmlnr-athm-mn-bmx").data("state")!=="activate"&&(!$(".jb-tqr-fdry-invit-bmx").length||$(".jb-tqr-fdry-invit-bmx").hasClass("this_hide"))&&$(".jb-tqr-fry-bx-bmx").not(".this_hide").length===0){_f_ShwAtHmMns(true);$(".jb-tmlnr-athm-mn-bmx").data("state","activate");$(".jb-tmlnr-hdr-hmbx").focus()}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_VrfyComfy=function(i,w,h){try{if(KgbLib_CheckNullity(i))return;var ir=_f_GIR();if(!i.type.match("image/*"))return"__COV_BAD_FILE";
if(!KgbLib_CheckNullity(w)&&!KgbLib_CheckNullity(h)){var filef=i.type.split("/").pop();if($.inArray(filef,ir.ft)===-1)return"__COV_BAD_TYPE";else if(i.size>ir.sz)return"__COV_BAD_SIZE";else{if(h<ir.h_min)return"__COV_BAD_DIMS_MIN";else if(h>ir.h_max)return"__COV_BAD_DIMS_MAX";if(w<ir.w_min)return"__COV_BAD_DIMS_MIN";else if(w>ir.w_max)return"__COV_BAD_DIMS_MAX"}}return true}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_OnError=function(c){try{if(KgbLib_CheckNullity(c))return;
c=c.toUpperCase();var m,t=0;switch(c){case "__COV_BAD_FILE":m=Kxlib_getDolphinsValue("ERR_COV_BAD_FILE");break;case "__COV_BAD_TYPE":m=Kxlib_getDolphinsValue("ERR_COV_BAD_TYPE");break;case "__COV_BAD_SIZE":m=Kxlib_getDolphinsValue("ERR_COV_BAD_SIZE");break;case "__COV_BAD_DIMS_MIN":m=Kxlib_getDolphinsValue("ERR_COV_BAD_DIMS_MIN");break;case "__COV_BAD_DIMS_MAX":m=Kxlib_getDolphinsValue("ERR_COV_BAD_DIMS_MAX");break;default:m=Kxlib_getDolphinsValue("ERR_GEN_FAILED");t=7E3;break}if(typeof t==="undefined"||
t===0)t=4E3;if($(".jb-cov-err-pan").hasClass("this_hide")){$(".jb-cov-err-inner").text(m);$(".jb-cov-err-pan").removeClass("this_hide");setTimeout(function(){var h=$(".jb-cov-err-pan-ctr").outerHeight();h=parseInt(h)*-1;$(".jb-cov-err-pan-ctr").animate({top:h},300,function(){$(".jb-cov-err-pan").addClass("this_hide");$(".jb-cov-err-inner").text("");$(".jb-cov-err-pan-ctr").removeAttr("style")})},t)}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Cvr_HdleChg=function(files){try{if(KgbLib_CheckNullity(files)||
files.lenght>1)return;var th=this,ca=false;$.each(files,function(k,v){if(!window.FileReader){var m=Kxlib_getDolphinsValue("ERR_BZR_OBSOLETE");alert(m);_f_Rst_Form(true);return}var gd=_f_VrfyComfy(v);if(gd!==true){_f_OnError(gd);_f_Rst_Form();return}if(gd){var reader=new FileReader;reader.onload=function(){var img=new Image;img.src=reader.result;img.onload=function(){var gd=_f_VrfyComfy(v,img.width,img.height);if(gd!==true){_f_OnError(gd);_f_Rst_Form();return}if($("#cov_img_buffer").length)$("#cov_img_buffer").remove();
$(".jb-a-h-t-top-img").addClass("this_hide");var $img=_f_CreateCvr(this);_FnlImg=_f_Locale_SvFnl($img);_FnlImg.name=v.name;th.OnGoing=true;_f_FnlDcBtns(true,"_ALTERING");$(".jb-a-h-t-top-fade").hide();$img.draggable({axis:"y",drag:function(e,ui){var _height=$(e.target).height();var _limit_down=260-_height;var _top=ui.position.top;if(_top>0)ui.position.top=0;else if(_top<_limit_down)ui.position.top=_limit_down}});$img.addClass("cover_move");$img.addClass("ui-widget-content");$img.attr("id","cov_img_buffer");
$(".jb-a-h-t-top-img-mx").prepend($img);$(".jb-cvr-fnl-chs[data-action='save']").data("action","_NEW_CVR")}};reader.onerror=function(){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return};reader.readAsDataURL(v)}})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_DelCvr=function(x){try{if(KgbLib_CheckNullity(x)|!$(x).length|KgbLib_CheckNullity($(x).data("action")))return;if(!KgbLib_CheckNullity(_xhr_dlcvr)|!KgbLib_CheckNullity(_xhr_chcvr))return;if(!$(".jb-a-h-t-top-img").length)return;
var a=$(x).data("action");switch(a){case "start_del_cover":$(".jb-tmlnr-cov-dlcf-dc-dc-tgr").data("lk",0);$(".jb-tmlnr-cov-dlcf-gninf-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-wait-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-dc-mx").removeClass("this_hide");$(".jb-tmlnr-cov-delconf-mx").removeClass("this_hide");return;case "abort_del_cover":$(".jb-tmlnr-cov-delconf-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-dc-mx").addClass("this_hide");return;case "confirm_del_cover":break;default:return}_f_Delete(x)}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};var _f_CreateCvr=function(img){try{var CR=new Cropper;var w=$(".jb-acc-hdr-top").width();var newImg=CR.Cropper_resizeWidthKeepHeightProrata(img,w);return $(newImg)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Locale_SvFnl=function(img){var Fi={img:img,name:img.name,top:""};return Fi};var _f_Rst_Form=function(frc){if(!$("#cov_img_buffer").length|frc){Kxlib_ResetFormElt("cover-file-input");return true}return false};var _f_FnlConfDecAct=function(x){try{if(KgbLib_CheckNullity(x)|
KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action");switch(a.toUpperCase()){case "_NEW_CVR":_f_Save(x);break;default:break}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Save=function(x){try{if($(".jb-cvr-fnl-chs").first().data("lk")===1)return;$(".jb-cvr-fnl-chs").data("lk",1);if(!KgbLib_CheckNullity(_xhr_dlcvr)|!KgbLib_CheckNullity(_xhr_chcvr))return;_f_CovPanel("_WAIT",true);$(".jb-a-h-t-top-img").remove();$("#cov_img_buffer").attr({"id":"a-h-t-top-img",
"class":"a-h-t-top-img jb-a-h-t-top-img"});_f_FnlDcBtns();$(".jb-a-h-t-top-fade").show();var final=_FnlImg.img;var ih=parseInt($(final).css("height").replace("px",""));var iw=parseInt($(final).css("width").replace("px",""));var it=$(final).css("top").replace("px","");it=it==="auto"?0:parseInt(it);var ds={img:$(final).attr("src"),in:_FnlImg.name,ih:ih,iw:iw,it:it};var s=$("<span/>");_f_Srv_SaveCvr(ds,s);_f_Rst_Form();$(s).on("datasready",function(e,d){if(KgbLib_CheckNullity(d))return;if($("#cov_img_buffer").length)return;
if(!$(".jb-a-h-t-top-img").length)return;var $im=$("<img/>",{"id":"a-h-t-top-img_new","src":d.cov_datas.acov_rpath,"style":"top: "+d.cov_datas.acov_top+"px; left: 0; position: absolute; z-index: 3;","height":d.cov_datas.acov_height,"width":d.cov_datas.acov_width});$(".jb-a-h-t-top-img-mx").prepend($im);$(".jb-a-h-t-top-fade").removeClass("this_hide");setTimeout(function(){$(".jb-a-h-t-top-img").remove();$("#a-h-t-top-img_new").attr({"id":"a-h-t-top-img","class":"a-h-t-top-img jb-a-h-t-top-img"});
$(".jb-a-h-t-t-noimg-i-mx").addClass("this_hide")},1E3);_f_HidChgCvrWtPnl();$(".jb-pfl-bio-bio").text(d.o_pbio);$(".jb-u-sp-cap-nb").text(d.o_cap);$(".jb-acc-spec-artnb").text(d.o_pnb);$(".jb-acc-spec-trnb").text(d.tr_nb);_f_CovPanel();var Nty=new Notifyzing;Nty.FromUserAction("ua_acov_set");$(".jb-cvr-fnl-chs").data("lk",0);_xhr_chcvr=null})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Delete=function(x){try{if($(".jb-tmlnr-cov-dlcf-dc-dc-tgr").first().data("lk")===1|$(".jb-chg-cvr-del-bx").data("lk")===
1)return;$(".jb-tmlnr-cov-dlcf-dc-dc-tgr").data("lk",1);$(".jb-chg-cvr-del-bx").data("lk",1);_f_CovPanel("_WAIT",true);var s=$("<span/>");_f_Srv_DelCvr(s);$(s).on("operended",function(e,d){if(KgbLib_CheckNullity(d))return;_f_CovPanel();$(".jb-a-h-t-top-img").remove();$(".jb-a-h-t-top-fade").addClass("this_hide");$(".jb-a-h-t-t-noimg-i-mx").removeClass("this_hide");var Nty=new Notifyzing;Nty.FromUserAction("ua_pflbio_set");$(".jb-c-c-start").removeClass("altering deleting");$(".jb-tmlnr-cov-dlcf-dc-dc-tgr").data("lk",
0);$(".jb-chg-cvr-del-bx").data("lk",0);_xhr_dlcvr=null;$(".jb-pfl-bio-bio").text(d.o_pbio);$(".jb-u-sp-cap-nb").text(d.o_cap);$(".jb-acc-spec-artnb").text(d.o_pnb);$(".jb-acc-spec-trnb").text(d.tr_nb)})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Abort=function(){$("#cov_img_buffer").remove();$(".jb-a-h-t-top-img").removeClass("this_hide");_f_FnlDcBtns();$(".jb-a-h-t-top-fade").show();Kxlib_ResetFormElt("cover-file-input")};var _f_Srv_SaveCvr=function(ds,s){if(KgbLib_CheckNullity(ds)|
KgbLib_CheckNullity(s)|!Kxlib_GetCurUserPropIfExist())return;var _Ax_SvCvr=Kxlib_GetAjaxRules("TMLNR_SET_COVER",Kxlib_GetCurUserPropIfExist().upsd);var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();break;case "__ERR_VOL_IMG_NOT_COMPLY":return;
case "__ERR_VOL_FAILED":var Nty=new Notifyzing;Nty.FromUserAction("ERR_COM_AJAX_GDT_FAIL",null,true);break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":Kxlib_AJAX_HandleDeny();break;default:Kxlib_AJAX_HandleFailed();break}return}else if(!KgbLib_CheckNullity(d.return)){var rds=[d.return];$(s).trigger("datasready",rds)}}catch(ex){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return};
var curl=document.URL;var toSend={"urqid":_Ax_SvCvr.urqid,"datas":{"img":encodeURIComponent(ds.img),"in":ds.in,"ih":ds.ih,"iw":ds.iw,"it":ds.it,"cl":curl}};Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_SvCvr.url,wcrdtl:_Ax_SvCvr.wcrdtl})};var _Ax_DelCvr=Kxlib_GetAjaxRules("TMLNR_RST_COVER",Kxlib_GetCurUserPropIfExist().upsd);var _f_Srv_DelCvr=function(s){if(KgbLib_CheckNullity(s)|!Kxlib_GetCurUserPropIfExist())return;var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=
JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();break;case "__ERR_VOL_IMG_NOT_COMPLY":break;case "__ERR_VOL_FAILED":var Nty=new Notifyzing;Nty.FromUserAction("ERR_COM_AJAX_GDT_FAIL",null,true);break;case "__ERR_VOL_MSM_RULES":Kxlib_AJAX_HandleFailed("ERR_COV_SRV_MSM_RLS");break;case "__ERR_VOL_NOTGT":m=
Kxlib_getDolphinsValue("ERR_COV_ONDEL_NOTGT");_f_CovPanel("_GEN_INFO",true,{info:m});break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":Kxlib_AJAX_HandleDeny();break;default:Kxlib_AJAX_HandleFailed();break}return}else if(!KgbLib_CheckNullity(d.return)){var rds=[d.return];$(s).trigger("operended",rds)}}catch(ex){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return};var curl=document.URL;
var toSend={"urqid":_Ax_DelCvr.urqid,"datas":{"cl":curl}};_xhr_dlcvr=Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_DelCvr.url,wcrdtl:_Ax_DelCvr.wcrdtl})};var _f_ShwChgCvrWtPnl=function(m){if(KgbLib_CheckNullity(m))return;$(".jb-a-h-t-top-wait").text(m);$(".jb-a-h-t-top-wait").stop(true,true).toggleClass("this_hide",300,"easeOutExpo")};var _f_HidChgCvrWtPnl=function(){$(".jb-a-h-t-top-wait").stop(true,true).toggleClass("this_hide",true,300,"easeOutExpo",function(){$(".jb-a-h-t-top-wait").text("")})};
var _f_FnlDcBtns=function(shw,scp){try{if(typeof shw!=="undefined"&&typeof scp==="undefined")return;if(shw){var cls=scp==="_DELETING"?"deleting":"altering";$(".jb-c-c-start").removeClass("altering deleting");$(".jb-c-c-start").addClass(cls);$(".jb-cvr-fnl-chs-mx").removeClass("this_hide")}else{$(".jb-c-c-start").removeClass("altering deleting");$(".jb-chg-cvr-del-bx").data("lk",0);$(".jb-cvr-fnl-chs-mx").addClass("this_hide")}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CvrHdBx=
function(shw){if(shw)$(".jb-chg-cvr-del-bx").removeClass("this_hide");else $(".jb-chg-cvr-del-bx").addClass("this_hide")};var _f_ShwAtHmMns=function(sh){try{if(sh){$(".jb-tmlnr-hdr-hmbx").stop(true,true).addClass("activate",250);$(".jb-tmlnr-athm-mn-bmx").stop(true,true).hide().fadeIn(240).removeClass("this_hide")}else{$(".jb-tmlnr-hdr-hmbx").stop(true,true).removeClass("activate",250);$(".jb-tmlnr-athm-mn-bmx").stop(true,true).fadeOut(270,function(){$(this).addClass("this_hide")})}}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};var _f_CovPanel=function(pan,sh,opts){try{switch(pan){case "_GEN_INFO":if(sh===true){if(!(!KgbLib_CheckNullity(opts)&&opts.hasOwnProperty("info")&&!KgbLib_CheckNullity(opts.info)&&typeof opts.info==="string"))return;$(".jb-tmlnr-cov-dlcf-gninf").text(opts.info);$(".jb-tmlnr-cov-dlcf-wait-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-dc-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-gninf-mx").removeClass("this_hide")}break;case "_WAIT":if(sh===true){$(".jb-tmlnr-cov-dlcf-gninf").text("");
$(".jb-tmlnr-cov-dlcf-dc-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-gninf-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-wait-mx").removeClass("this_hide")}break;case "_DIALOG":if(sh===true){$(".jb-tmlnr-cov-dlcf-gninf").text("");$(".jb-tmlnr-cov-dlcf-wait-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-dc-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-gninf-mx").removeClass("this_hide")}break;default:$(".jb-tmlnr-cov-delconf-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-wait-mx").addClass("this_hide");
$(".jb-tmlnr-cov-dlcf-dc-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-gninf").text("");$(".jb-tmlnr-cov-dlcf-gninf-mx").addClass("this_hide");return}if(sh===true)$(".jb-tmlnr-cov-delconf-mx").removeClass("this_hide");else{$(".jb-tmlnr-cov-dlcf-gninf-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-gninf").text("");$(".jb-tmlnr-cov-dlcf-wait-mx").addClass("this_hide");$(".jb-tmlnr-cov-dlcf-dc-mx").addClass("this_hide");$(".jb-tmlnr-cov-delconf-mx").addClass("this_hide")}}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};$(".jb-a-h-t-top").hover(function(){setTimeout(function(){if((!$(".jb-a-h-t-t-noimg-i-mx").length||$(".jb-a-h-t-t-noimg-i-mx").hasClass("this_hide"))&&!$(".jb-c-c-start").hasClass("altering")&&!$(".jb-c-c-start").hasClass("deleting")&&$(".jb-a-h-t-top-wait").hasClass("this_hide")&&$(".jb-a-h-t-top:hover").length&&(KgbLib_CheckNullity(_xhr_chcvr)&&KgbLib_CheckNullity(_xhr_dlcvr))){$(".jb-chg-cvr-del-bx").stop(true,true).hide().removeClass("this_hide").fadeIn();$(".jb-chg-cvr").stop(true,
true).hide().removeClass("this_hide").fadeIn()}else if(!(!$(".jb-a-h-t-t-noimg-i-mx").length||$(".jb-a-h-t-t-noimg-i-mx").hasClass("this_hide"))&&!$(".jb-c-c-start").hasClass("altering")&&!$(".jb-c-c-start").hasClass("deleting")&&$(".jb-a-h-t-top-wait").hasClass("this_hide")&&$(".jb-a-h-t-top:hover").length&&(KgbLib_CheckNullity(_xhr_chcvr)&&KgbLib_CheckNullity(_xhr_dlcvr)))$(".jb-chg-cvr").stop(true,true).hide().removeClass("this_hide").fadeIn();else if($(".jb-c-c-start").hasClass("altering")&&$(".jb-a-h-t-top:hover").length)$(".jb-chg-cvr").stop(true,
true).hide().removeClass("this_hide").fadeIn();else{$(".jb-chg-cvr-del-bx").stop(true,true).fadeOut(500,function(){$(this).addClass("this_hide")});$(".jb-chg-cvr").stop(true,true).fadeOut(500,function(){$(this).addClass("this_hide")})}},350)},function(){$(".jb-chg-cvr").stop(true,true).fadeOut(500,function(){$(this).addClass("this_hide")});$(".jb-chg-cvr-del-bx").stop(true,true).fadeOut(500,function(){$(this).addClass("this_hide")})});$(".jb-chg-cvr").click(function(e){});$(".jb-cvr-file-ipt").click(function(e){Kxlib_StopPropagation(e)});
$(".jb-cvr-file-ipt").change(function(e){Kxlib_StopPropagation(e);var files=this.files;_f_Cvr_HdleChg(files)});$(".jb-chg-cvr-del-bx, .jb-tmlnr-cov-dlcf-dc-dc-tgr").click(function(e){Kxlib_PreventDefault(e);_f_DelCvr(this)});$(".jb-cvr-fnl-chs[data-action='save']").click(function(e){Kxlib_PreventDefault(e);_f_FnlConfDecAct(this)});$(".jb-cvr-fnl-chs[data-action='cancel']").click(function(e){Kxlib_PreventDefault(e);_f_Abort()});$(".menu-noselected").hover(function(e){_f_Action(this)},function(e){_f_Action(this)});
$(".jb-tmlnr-hdr-hmbx, .jb-tmlnr-hdr-hmbx > *").hover(function(e){if((!$(".jb-tqr-fdry-invit-bmx").length||$(".jb-tqr-fdry-invit-bmx").hasClass("this_hide"))&&$(".jb-tqr-fry-bx-bmx").not(".this_hide").length===0)$(".jb-tmlnr-hdr-hmbx").removeClass("disable")},function(){});$(".jb-tmlnr-hdr-hmbx").off().click(function(e){Kxlib_PreventDefault(e);Kxlib_StopPropagation(e);_f_AtHmMns(this)});$(".jb-tmlnr-hdr-hmbx").focusout(function(e){Kxlib_StopPropagation(e);_f_HdlOpnAtHmMns(e,null,false)})}new ACCHDR;
function ACHR_Receiver(){var o=new ACCHDR;this.Routeur=function(th){if(KgbLib_CheckNullity(th))return;o.CheckOperation(th)}};
