function TMLNR_PFLHDR(){var gt=this;var _dftPic;var _newPic;var _newPic_fn;var _oldPic;var _f_ChkOpe=function(x,fl){try{if(KgbLib_CheckNullity(x))return;if(!KgbLib_CheckNullity(fl))_f_ChgPic(fl);if(KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action");switch(a.toString().toLowerCase()){case "change":break;case "delete":_f_ConfDfltPic(x);break}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Gdf=function(){var DT={"dt":Kxlib_GetExtFileURL("sys_url_img","r-dp/tqr_std_ppic_m.png"),
"__ZInMax":90,"__ZOutMax":45,"__MAXSize":2621440,"__Format":["png","jpeg"],"__Min_H":70,"__Max_H":1E3,"__Min_W":70,"__Max_W":1E3};return DT};var _f_ChgPic=function(f){try{if(KgbLib_CheckNullity(f)||f.length>1)return;$.each(f,function(x,v){var r=_f_VrfyComfy(v);if(!r||typeof r==="string"){_f_OnError(r);_f_Reset_Form();delete _newPic;return}_f_ReadFile(v)})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_VrfyComfy=function(i,w,h){try{if(KgbLib_CheckNullity(i))return;if(!i.type.match("image/*"))return"__PP_BAD_FILE";
if(!KgbLib_CheckNullity(w)&&!KgbLib_CheckNullity(h)){var filef=i.type.split("/").pop();if($.inArray(filef,_f_Gdf().__Format)===-1)return"__PP_BAD_TYPE";else if(i.size>_f_Gdf().__MAXSize)return"__PP_BAD_SIZE";else if(w!==h)return"__PP_BAD_FORMAT";else{if(h<_f_Gdf().__Min_H)return"__PP_BAD_DIMS_MIN";else if(h>_f_Gdf().__Max_H)return"__PP_BAD_DIMS_MAX";if(w<_f_Gdf().__Min_W)return"__PP_BAD_DIMS_MIN";else if(w>_f_Gdf().__Max_W)return"__PP_BAD_DIMS_MAX"}}return true}catch(ex){Kxlib_DebugVars([ex,ex.fileName,
ex.lineNumber],true)}};var _f_OnError=function(c){try{if(KgbLib_CheckNullity(c))return;var m,t=0;switch(c.toUpperCase()){case "__PP_BAD_FILE":m=Kxlib_getDolphinsValue("ERR_PPIC_BAD_FILE");break;case "__PP_BAD_TYPE":m=Kxlib_getDolphinsValue("ERR_PPIC_BAD_TYPE");break;case "__PP_BAD_SIZE":m=Kxlib_getDolphinsValue("ERR_PPIC_BAD_SIZE");break;case "__PP_BAD_FORMAT":m=Kxlib_getDolphinsValue("ERR_PPIC_BAD_FORMAT");break;case "__PP_BAD_DIMS_MIN":m=Kxlib_getDolphinsValue("ERR_PPIC_BAD_DIMS_MIN");break;case "__PP_BAD_DIMS_MAX":m=
Kxlib_getDolphinsValue("ERR_PPIC_BAD_DIMS_MAX");break;default:m=Kxlib_getDolphinsValue("ERR_GEN_FAILED");t=7E3;break}var ec;if(typeof t==="undefined"||t===0){t=4E3;ec=$(".jb-p-h-b-ui-trg").data("ec");ec=KgbLib_CheckNullity(ec)?0:parseInt(ec);ec=++ec;$(".jb-p-h-b-ui-trg").data("ec",ec)}if(!KgbLib_CheckNullity(ec)&&ec>=3)$(".jb-p-h-ui-hlp-pan").removeClass("this_hide");if($(".jb-h-ui-err-pan").hasClass("this_hide")){$(".jb-h-ui-err-pan").text(m);$(".jb-h-ui-err-pan").removeClass("this_hide");setTimeout(function(){$(".jb-h-ui-err-pan").fadeOut(250,
function(){$(this).addClass("this_hide");$(this).removeAttr("style")})},t)}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Reset_Form=function(){return Kxlib_ResetFormElt("p-h-b-ui-a-file")?true:false};var _f_ReadFile=function(fl){try{if(!window.FileReader){var m=Kxlib_getDolphinsValue("ERR_BZR_OBSOLETE");alert(m);_f_Reset_Form(true);return}if(KgbLib_CheckNullity(fl))return;var rd=new FileReader;rd.onload=function(){var img=new Image;img.src=rd.result;img.onload=function(){var gd=
_f_VrfyComfy(fl,img.width,img.height);if(!gd||typeof gd==="string"){_f_OnError(gd);_f_Reset_Form();return}var sp=$(this).data("is-default");_newPic_fn=fl.name;if(!sp)_f_CrtThumbnail(this);else _f_CrtThumbnail(this,true);_f_Reset_Form()}};rd.onerror=function(){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH")};rd.readAsDataURL(fl)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_IsSquare=function(h,w){return h/w===1?1:0};var _f_ImgIsDrgble=function(f){$("#p-h-b-ui-trg").addClass("this_overhid");
$(f).draggable({axis:"x,y",drag:function(e,ui){var _h=$(e.target).height(),_w=$(e.target).width();var _top=ui.position.top,_left=ui.position.left;var _limit_down=90-_h,_limit_right=90-_w;if(_top>0)ui.position.top=0;else if(_top<_limit_down)ui.position.top=_limit_down;if(_left>0)ui.position.left=0;else if(_left<_limit_right)ui.position.left=_limit_right}});$(f).addClass("cover_move");$(f).addClass("ui-widget-content");return f};var _f_CrtThumbnail=function(fl,dc){try{if(KgbLib_CheckNullity(fl))return;
if(!_f_IsSquare(fl.height,fl.width));else{var oo=new Cropper;fl=oo.Cropper_ResizeTo(fl,_f_Gdf().__ZInMax,_f_Gdf().__ZInMax);if(!dc){$(".jb-p-h-b-ui-img").off().fadeOut({complete:function(){$(".jb-p-h-b-ui-img-buffer").remove();_newPic=fl.src;var i__=$("<img/>").attr({"id":"p-h-b-ui-img-buffer","class":"jb-p-h-b-ui-img-buffer","width":"90px","height":"90px","src":fl.src});i__=_f_Rebind(i__);$(i__).appendTo(".jb-p-h-b-ui-trg")}});if($(".jb-p-h-b-ui-f-a-ch[data-always='y']").length){$(".jb-p-h-b-ui-f-a-ch[data-always='y']").data("action",
"save");$(".jb-p-h-b-ui-f-a-tle").text(Kxlib_getDolphinsValue("COMLG_save"))}_f_ShwFnlDecMns()}else $(fl).off()}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Rebind=function(e){try{if(KgbLib_CheckNullity(e))return;$(e).off("click").click(function(e){Kxlib_PreventDefault(e);_f_HdleDashMn(this)});$(e).off("hover").hover(function(){_f_ZmInPic(this)},function(){_f_ZmOutPic(this)});return e}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_CrtRbndIptFile=
function(){try{var O=new TMLNR_PFLHDR,e=$("<input/>").attr({id:"p-h-b-ui-a-file",type:"file",autocomplete:"off"});$(".jb-p-h-b-ui-a-file").remove();$(e).click(function(e){Kxlib_StopPropagation(e)});$(e).change(function(e){var f=this.files;_f_ChkOpe(this,f)});$(e).appendTo(".jb-p-h-b-ui-action[data-action=change]");return e}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_ConfDfltPic=function(x){try{if(KgbLib_CheckNullity(x))return;if($(".jb-p-h-b-ui-f-a-ch[data-always='y']").length){$(".jb-p-h-b-ui-f-a-ch[data-always='y']").data("action",
"delete");$(".jb-p-h-b-ui-f-a-tle").text(Kxlib_getDolphinsValue("COMLG_confirm"))}_f_ShwFnlDecMns()}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_SetDfltPic=function(){try{var s=$("<span/>");_f_CreateDfltPic(s);$(s).on("operended",function(){_f_CrtRbndIptFile();var i=_dftPic;$(".jb-p-h-b-ui-img").hide().remove();$(i).attr("id","p-h-b-ui-img");$(i).hide().appendTo(".jb-p-h-b-ui-trg").fadeIn();var s2=$("<span/>");_f_Srv_SetDefaultPic(s2);_f_HidFnlDecMns();$(".jb-p-h-b-ui-act-box").addClass("this_hide",
500,function(){});_f_ShwWtPnl();$(".jb-p-h-b-ui-trg").removeData("ec");$(s2).on("operended",function(e){_f_HdWtPnl();_f_HidDashMn(_dftPic);_f_ZmOutPic(_dftPic);$(".jb-p-h-b-ui-trg").data("lk",1);var code="ua_pp_set";var Nty=new Notifyzing;Nty.FromUserAction(code);if($(".jb-pg-sts").length){$(".jb-pg-sts-txt").text(Kxlib_getDolphinsValue("COMLG_Loading")+"...");$(".jb-pg-sts").removeClass("this_hide")}setTimeout(function(){location.reload()},2E3)})})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],
true)}};var _f_CreateDfltPic=function(s){try{$("<img/>").attr({"src":_f_Gdf().dt}).height(45).width(45).load(function(){$(this).off();$(this).css({height:"90px",width:"90px"});_f_Rebind($(this));_dftPic=$(this);$(s).trigger("operended");return}).error(function(){})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_Save=function(){try{var w=$(".jb-p-h-b-ui-img").css("width"),h=$(".jb-p-h-b-ui-img").css("height"),t=$(".jb-p-h-b-ui-img").css("top"),l=$(".jb-p-h-b-ui-img").css("left"),
s=$("<span/>");var ds={"img":_newPic,"name":_newPic_fn,"h":h.replace("px",""),"w":w.replace("px",""),"top":t==="auto"?"0":t.replace("px",""),"left":l==="auto"?"0":l.replace("px","")};_f_Srv_SetNewPic(ds,s);_f_HidFnlDecMns();$(".jb-p-h-b-ui-act-box").addClass("this_hide",500,function(){});_f_ShwWtPnl();$(".jb-p-h-b-ui-trg").removeData("ec");$(s).on("datasready",function(e,d){if(KgbLib_CheckNullity(d))return;_f_HdWtPnl();_f_HidDashMn();$(".jb-p-h-b-ui-img-buffer").fadeOut({complete:function(){var ni=
$("<img/>").attr({"id":"p-h-b-ui-img","width":90,"height":90,"src":d.pp_datas.pp_rpath});$(".jb-p-h-b-ui-img").replaceWith(ni);_f_ZmOutPic(ni);$(".jb-p-h-b-ui-trg").data("lk",1)}});var code="ua_pp_set";var Nty=new Notifyzing;Nty.FromUserAction(code);if($(".jb-pg-sts").length){$(".jb-pg-sts-txt").text(Kxlib_getDolphinsValue("COMLG_Loading")+"...");$(".jb-pg-sts").removeClass("this_hide")}setTimeout(function(){location.reload()},2E3)})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};
var _f_ChkFnlOpe=function(x){try{if(KgbLib_CheckNullity(x)|KgbLib_CheckNullity($(x).data("action")))return;var a=$(x).data("action");switch(a.toLowerCase()){case "cancel":_f_Abort();break;case "save":_f_Save();break;case "delete":_f_SetDfltPic();_f_HidFnlDecMns();break}}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _Ax_SetDfltPic=Kxlib_GetAjaxRules("TMLNR_SET_DFTPIC",Kxlib_GetCurUserPropIfExist().upsd);var _f_Srv_SetDefaultPic=function(s){if(KgbLib_CheckNullity(s))return;var onsuccess=
function(d){try{if(!KgbLib_CheckNullity(d))d=JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_U_G":case "__ERR_VOL_CU_GONE":Kxlib_HandleCurrUserGone();break;case "__ERR_VOL_IMG_NOT_COMPLY":return;case "__ERR_VOL_FAILED":return;break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":return;break;default:Kxlib_AJAX_HandleFailed();break}return}else if(!KgbLib_CheckNullity(d.return))$(s).trigger("operended")}catch(ex){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");
return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return};var curl=document.URL;var toSend={"urqid":_Ax_SetDfltPic.urqid,"datas":{"cl":curl}};Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_SetDfltPic.url,wcrdtl:_Ax_SetDfltPic.wcrdtl})};var _Ax_NewPflPic=Kxlib_GetAjaxRules("TMLNR_SET_PFLPIC",Kxlib_GetCurUserPropIfExist().upsd);var _f_Srv_SetNewPic=function(ds,s){if(KgbLib_CheckNullity(ds)|KgbLib_CheckNullity(s))return;
var onsuccess=function(d){try{if(!KgbLib_CheckNullity(d))d=JSON.parse(d);else return;if(!KgbLib_CheckNullity(d.err)){if(Kxlib_AjaxIsErrVolatile(d.err))switch(d.err){case "__ERR_VOL_ACC_GONE":case "__ERR_VOL_USER_GONE":case "__ERR_VOL_CU_GONE":case "__ERR_VOL_U_GONE":case "__ERR_VOL_U_G":Kxlib_HandleCurrUserGone();break;case "__ERR_VOL_IMG_NOT_COMPLY":break;case "__ERR_VOL_FAILED":break;case "__ERR_VOL_DENY":case "__ERR_VOL_DENY_AKX":break;default:Kxlib_AJAX_HandleFailed();break}return}else if(!KgbLib_CheckNullity(d.return)){var rds=
[d.return];$(s).trigger("datasready",rds)}else return}catch(ex){Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return}};var onerror=function(a,b,c){Kxlib_AjaxGblOnErr(a,b);Kxlib_AJAX_HandleFailed("ERR_COM_AJAX_FAIL_TECH");return};var curl=document.URL;var toSend={"urqid":_Ax_NewPflPic.urqid,"datas":{"img":encodeURIComponent(ds.img),"in":ds.name,"iw":ds.w,"ih":ds.h,"it":ds.top,"cl":curl}};Kx_XHR_Send(toSend,null,null,onsuccess,onerror,{type:"post",url:_Ax_NewPflPic.url,wcrdtl:_Ax_NewPflPic.wcrdtl})};
this.ShowPflipicRulesPanel=function(){$(".jb-p-h-ui-hlp-pan").hide().removeClass("this_hide").fadeIn();$(".jb-p-h-ui-hlp-pan").removeAttr("style")};var _f_HidPflipicRulesPanel=function(){$(".jb-p-h-ui-hlp-pan").addClass("this_hide")};var _f_ZmInPic=function(a,force){try{if(KgbLib_CheckNullity(a)|$(".jb-p-h-b-ui-trg").data("lk")===1)return;setTimeout(function(){if(!$(".jb-p-h-b-ui-i-fade").is(":hover")&&KgbLib_CheckNullity(force))return;$(a).stop(true,true).animate({height:_f_Gdf().__ZInMax,width:_f_Gdf().__ZInMax},
function(){})},250)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_ZmOutPic=function(v,impt){try{var a=KgbLib_CheckNullity(v)?$(".jb-p-h-b-ui-img"):v;if($(".jb-p-h-b-ui-trg").data("lk")===1&&!(!KgbLib_CheckNullity(impt)&&impt===true))return;$(a).stop(true,true).animate({height:_f_Gdf().__ZOutMax,width:_f_Gdf().__ZOutMax},function(){})}catch(ex){Kxlib_DebugVars([ex,ex.fileName,ex.lineNumber],true)}};var _f_ShwDashMn=function(x){try{$(x).parent().data("lk",1);if($(".jb-p-h-b-uimg").data("dm-status")===
0){if($(".jb-p-h-b-ui-trg").data("dft")===1)$(".jb-p-h-b-ui-action[data-action='delete']").addClass("this_hide");else $(".jb-p-h-b-ui-action[data-action='delete']").removeClass("this_hide");$(x).parent().parent().addClass("p-h-b-ui-trg-box-zm",500);$(x).parent().parent().parent().addClass("p-h-b-uimg-zm",500);$(".jb-p-h-b-ui-act-box").removeClass("this_hide",500);setTimeout(function(){if($(x).parent().data("lk")===1)$(x).parent().addClass("p-h-b-ui-trg-zm",500)},500)}}catch(ex){Kxlib_DebugVars([ex,
ex.fileName,ex.lineNumber],true)}};var _f_HidDashMn=function(x){try{var o=KgbLib_CheckNullity(x)?$(".jb-p-h-b-ui-img"):x;if(!$(o).length)return;$(".jb-p-h-b-ui-act-box").addClass("this_hide",500,function(){});$(o).parent().parent().removeClass("p-h-b-ui-trg-box-zm",500);$(o).parent().removeClass("p-h-b-ui-trg-zm",500);$(".jb-p-h-b-uimg").removeClass("p-h-b-uimg-zm",500);$(o).parent().data("lk",0);_f_HidPflipicRulesPanel();$(".jb-p-h-b-ui-trg").removeData("ec")}catch(ex){Kxlib_DebugVars([ex,ex.fileName,
ex.lineNumber],true)}};var _f_HdleDashMn=function(x){if(!$(".jb-p-h-b-ui-fnl-act").hasClass("this_hide")|!$(".jb-p-h-b-ui-wt").hasClass("this_hide"))return;if($(x).parent().data("lk")===0){_f_ZmInPic(x,true);_f_ShwDashMn(x)}else _f_HidDashMn(x)};var _f_ShwFnlDecMns=function(){$(".jb-p-h-b-ui-fnl-act").hide().removeClass("this_hide").fadeIn(500)};var _f_HidFnlDecMns=function(){$(".jb-p-h-b-ui-fnl-act").animate({duration:100,height:"0px"},function(){$(this).addClass("this_hide");$(this).removeAttr("style")})};
var _f_ShwWtPnl=function(){$(".jb-p-h-b-ui-wt").removeClass("this_hide")};var _f_HdWtPnl=function(){$(".jb-p-h-b-ui-wt").addClass("this_hide")};var _f_Abort=function(){try{$(".jb-p-h-b-ui-img-buffer").fadeOut({complete:function(){$(".jb-p-h-b-ui-img").fadeIn();$(this).off().remove()}});$(".jb-p-h-b-ui-fnl-act").addClass("this_hide");var id;id=setTimeout(function(){_f_HidDashMn();_f_ZmOutPic();_f_CrtRbndIptFile();$(".jb-p-h-b-ui-trg").removeData("ec")},600)}catch(ex){Kxlib_DebugVars([ex,ex.fileName,
ex.lineNumber],true)}};$(".jb-p-h-b-ui-action").click(function(e){Kxlib_PreventDefault(e);_f_ChkOpe(this)});$(".jb-p-h-b-ui-i-fade").off("click").click(function(e){Kxlib_PreventDefault(e);var _this=$(this).closest(".jb-p-h-b-ui-trg").find(".jb-p-h-b-ui-img");_f_HdleDashMn(_this)});$(".jb-p-h-b-ui-trg > *").off("hover").hover(function(e){var _this=$(this).closest(".jb-p-h-b-ui-trg").find(".jb-p-h-b-ui-img");_f_ZmInPic(_this)},function(){var _this=$(this).closest(".jb-p-h-b-ui-trg").find(".jb-p-h-b-ui-img");
_f_ZmOutPic(_this)});$(".jb-p-h-b-ui-a-file").click(function(e){Kxlib_StopPropagation(e)});$(".jb-p-h-b-ui-a-file").change(function(e){var fl=this.files;_f_ChkOpe(this,fl)});$(".jb-p-h-b-ui-f-a-ch").off("click").click(function(e){Kxlib_PreventDefault(e);_f_ChkFnlOpe(this)})}new TMLNR_PFLHDR;
